// Italiano
I18N.addLang('it', {
  help: {
    title: '64 Pad Explorer',
    description: 'Uno strumento per esplorare scale, accordi e voicings su una griglia di 64 pad.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Scegliere tra 12 tonalità',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonica, minore armonica, minore melodica, pentatonica, Bebop e altro \u2014 31 tipi',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Mostra gli accordi diatonici della scala selezionata. Clicca per entrare in modalità Chord',
    chord_mode: 'Chord Mode (3 passaggi)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selezionare la fondamentale sulla tastiera del pianoforte',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Scegliere il tipo di accordo (Maj, m, aug, dim, sus, ecc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Aggiungere tensioni (9, b9, #9, 11, #11, 13, b13, ecc.). Selezione multipla consentita',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usare il pulsante "/" per accordi con basso diverso (accordo / nota di basso)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettere note',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 per aggiungere note)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Rivolti (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tocca per scorrere le disposizioni sui pad (badge pulsante = disposizioni alternative disponibili)',
    display: 'Visualizzazione',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Attivare/disattivare tastiera di chitarra, pianoforte e pentagramma indipendentemente',
    display_label: '<strong>Nome / Grado</strong> \u2014 Alternare tra nomi delle note (C, D, E) e gradi (R, 2, 3) su chitarra e pad',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Spostare l\'estensione dei pad di un\'ottava',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 preset (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 preset (Rhodes, FM, ecc.)',
    sound_fx: '<strong>Effetti</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Clicca su un pad o una voicing box per riprodurre il suono',
    midi: 'MIDI',
    midi_detect: 'Rilevamento automatico dei dispositivi compatibili WebMIDI',
    midi_push: 'Supporto per l\'uscita MIDI seriale di Ableton Push',
    midi_chord: 'Identificazione automatica degli accordi dalle note suonate',
    color_title: 'Legenda colori',
    color_root: '<strong>Root</strong> \u2014 Nota fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Note della scala / Note dell\'accordo',
    color_char: '<strong>Caratteristica</strong> \u2014 Note che definiscono la scala/l\'accordo',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (terza)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (settima)',
    color_tension: '<strong>Tension</strong> \u2014 Note di tensione',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota della scala un semitono sopra una nota dell\'accordo (in modalità Chord)',
    color_palette: 'Palette colori: Okabe-Ito (accessibile per daltonici)',
    input_title: 'Ingresso Guitar / Piano',
    input_desc1: 'Clicca sulla tastiera della chitarra o del pianoforte per inserire le note',
    input_desc2: 'Gli accordi vengono identificati automaticamente dall\'input e riflessi sul pad',
    input_desc3: '<strong>Clear</strong> \u2014 Cancella input, <strong>Play \u25B6</strong> \u2014 Riproduci le note inserite',
    input_title: 'Input Mode',
    input_desc1: 'Clicca liberamente sui pad per selezionare le note \u2192 Identificazione accordi in tempo reale',
    input_desc2: 'Senza filtro teorico. Esplora \u2192 scopri \u2192 impara la teoria dopo',
    input_desc3: 'Quando viene rilevato un accordo, etichette di grado (R, 3, 5, b7, ecc.) appaiono sui pad. Chitarra, basso, pianoforte e pentagramma si aggiornano automaticamente',
    input_memory: '<strong>Memory</strong> \u2014 Salva e richiama accordi in 16 slot',
    input_export: '<strong>MIDI Export</strong> \u2014 Esporta gli accordi in memoria come file MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> pulsante o tasto <kbd>p</kbd> per cambiare',
    perform_desc1: 'Suona gli accordi dei Memory Slot in tempo reale con un layout a 16 pad',
    perform_desc2: 'Attiva tramite tastiera (griglia 4\u00D74) o pad MIDI',
    perform_desc3: 'Trascina e rilascia gli Slot per riordinare',
    shortcut_title: 'Scorciatoie da tastiera',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Selezionare accordo diatonico (scale a 7 note)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Selezionare voicing box (scorrere le alternative)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Scorrere i rivolti (modalità Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Trasposizione cromatica della fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Attivare/disattivare Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Attivare/disattivare Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclare Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclare Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Cancella accordo (modalità Chord)',
    sc_pad_explore: '<b>Pad (modo Chord)</b> \u2014 Clic per attivare/disattivare nota \u2014 il costruttore si aggiorna automaticamente',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Avviare Capture / salvare nello slot successivo',
    sp_end: '<kbd>e</kbd> \u2014 Terminare Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Richiamare slot di memoria (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Trasposizione cromatica (tutte le note \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Rivolto (più bassa \u21911ott / più alta \u21931ott)',
    sp_clear: '<kbd>x</kbd> \u2014 Cancella tutto',
    sp_transfer: '<b>Chord switch</b> \u2014 Trasferire l\'accordo rilevato in modalità Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Griglia 4\u00D74 attiva Slot 1\u201316',
    pf_midi: 'I pad MIDI (note 36\u201354) attivano anche gli Slot',
    shortcut_common: 'Comune (tutte le modalit\u00E0)',
    sc_perform: '<kbd>p</kbd> \u2014 Attivare/disattivare la vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annulla Memory Slot (fino a 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Salvare nello slot di memoria Input (da qualsiasi modalità)',
    sc_space: '<kbd>Space</kbd> \u2014 Riprodurre accordo attuale',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselezionare voicing box / chiudere la guida',
    sc_help: '<kbd>?</kbd> \u2014 Mostrare/nascondere la guida',
    footer: '64 Pad Explorer V2.10 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caratteristica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Chiudi',
    slot_hint: 'Clicca per selezionare \u2192 Save(c) / Shift+clic per cancellare',
    save_settings: 'Salva impostazioni',
    sound_hint: 'Seleziona ORGAN o E.PIANO per attivare il suono',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grado',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
    guide: 'Guida',
  },
  input: {
    status_idle: 'Premi Capture per iniziare a costruire accordi',
    status_capturing: 'Cattura: Slot {slot}/16 \u2014 Clicca sui pad, poi Capture per salvare',
    status_editing: 'Modifica: Slot {slot} \u2014 Clicca sui pad per modificare',
    notes_label: 'Note: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selezionato',
    slot_cleared: 'Slot {slot} cancellato',
    undo: 'Annulla',
    settings_saved: 'Impostazioni salvate',
    no_chords: 'Nessun accordo negli slot di memoria',
  },
  info: {
    note_count: '{n} note',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Seleziona la fondamentale',
  },
  midi: {
    all_devices: 'Tutti i dispositivi',
  },
  memory: {
    slot_empty: 'Slot {slot}: Vuoto',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Clicca per rinominare',
    rename: 'Rinomina',
    duplicate: 'Duplica',
    delete: 'Elimina',
    rename_prompt: 'Nome del banco:',
    confirm_delete: 'Eliminare "{name}"?',
    limit_reached: 'Massimo 16 banchi',
    cannot_delete_last: 'Impossibile eliminare l\'ultimo banco',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostra tutto',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guida',
    tagline: 'Uno strumento nel browser per esplorare scale, accordi e voicings su una griglia di 64 pad.<br>Non serve alcuna sorgente sonora \u2014 basta Chrome.',
    cta: 'Apri App',
    features: 'Funzionalit\u00E0',
    feat_sound: '<strong>Nessuna sorgente sonora necessaria</strong> \u2014 Il suono viene riprodotto direttamente in Chrome. 4 preset organo + 7 preset pianoforte elettrico integrati. Effetti (reverb, phaser, flanger, tremolo, filtro) inclusi',
    feat_input: '<strong>Nessuna abilit\u00E0 sui pad richiesta</strong> \u2014 Costruisci accordi in 3 passaggi. Tensioni visualizzate. Clicca sui pad per inserire direttamente',
    feat_detect: '<strong>Rilevamento accordi</strong> \u2014 Rilevamento del nome dell\'accordo in tempo reale dalle note cliccate. Supporta omit, accordi con basso diverso e candidati multipli',
    feat_instruments: '<strong>Visualizzazione Guitar / Bass / Keyboard</strong> \u2014 Mostra le note dell\'accordo sulla tastiera della chitarra, del basso e del pianoforte. L\'input dalla diteggiatura della chitarra si riflette automaticamente sui pad',
    feat_scales: '<strong>Visualizzazione scale</strong> \u2014 31 scale \u00D7 12 tonalit\u00E0. Diatonica, minore armonica, minore melodica, pentatonica, Bebop e altro',
    feat_diatonic: '<strong>Visualizzazione accordi diatonici</strong> \u2014 Gli accordi diatonici della scala selezionata sono mostrati su una barra. Clicca o usa le scorciatoie per suonare subito',
    feat_voicing: '<strong>Operazioni di voicing</strong> \u2014 Inversion, Drop 2/3, Shell Voicing, Omit, Rootless. Tasti freccia per i rivolti, pulsanti per diteggiature multiple',
    feat_memory: '<strong>Memoria accordi</strong> \u2014 Salva i tuoi accordi preferiti in 16 slot. Esporta come file MIDI per il tuo DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Suona gli accordi in memoria in tempo reale usando 16 pad o la tastiera del PC',
    feat_parent: '<strong>Ricerca inversa Available Scale</strong> \u2014 Trova le scale che contengono il tuo accordo. Vedi le Available Tensions a colpo d\'occhio. Alternanza Practical/Diatonic',
    feat_pivot: '<strong>Pensiero accordo pivot</strong> \u2014 Inserisci un accordo manualmente e la barra diatonica scompare, mostrando tutte le tonalit\u00E0 a cui il tuo accordo potrebbe appartenere. Ideale per l\'analisi della modulazione',
    feat_dimming: '<strong>Visualizzazione pratica delle Tensions</strong> \u2014 Per gli accordi di 7\u00AA non dominante, le tensioni poco comuni (b9, #9, b13, ecc.) sono attenuate. Ancora selezionabili',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 lingue (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshot',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Seleziona una tonalit\u00E0 e una scala per vedere le note della scala colorate sulla griglia di 64 pad. Scegli gli accordi dalla barra diatonica.',
    ss_scale_alt: 'Scale Mode \u2014 Visualizzazione della scala di C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (arancione), note della scala (blu), note caratteristiche (giallo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Costruisci accordi in 3 passaggi: Root \u2192 Quality \u2192 Tension. Regola i voicing con Inversion, Drop, Shell e Omit. Usa il pannello Parent Scale per la ricerca inversa delle scale.',
    ss_chord_alt: 'Chord Mode \u2014 Visualizzazione dell\'accordo Dm7 con griglia delle tensioni',
    ss_chord_caption: 'Dm7 \u2014 Note dell\'accordo, 3rd (rosa), 7th (verde). Controlla le opzioni di disposizione nei voicing box',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Clicca liberamente sui pad per il rilevamento degli accordi in tempo reale. Comprendi gli accordi anche senza conoscere la teoria.',
    ss_input_alt: 'Input Mode \u2014 Rilevamento in tempo reale di C7',
    ss_input_caption: 'C7 \u2014 Clicca sui pad per rilevare automaticamente i nomi degli accordi. Candidati multipli mostrati',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Posiziona gli accordi salvati su 16 pad per suonare in tempo reale usando la tastiera o i pad MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 slot con accordi',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 salvati negli slot. Suona usando la griglia 4\u00D74 della tastiera',
    ss_parent: 'Available Scale + Accordo Pivot',
    ss_parent_desc: 'Ricerca inversa delle scale che contengono il tuo accordo. Alterna tra ordinamento Practical (per usabilit\u00E0) e Diatonic (per teoria). L\'inserimento manuale di accordi nasconde la barra diatonica per l\'analisi degli accordi pivot.',
    ss_parent_alt: 'Pannello Parent Scale e visualizzazione tastiera chitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), ecc. Available Tensions visualizzate',
    ss_parent_note: '\u203B Le scale pentatoniche/blues sono modali (approccio orizzontale) e appartengono a un sistema diverso dalla teoria delle scale per accordo (mappatura verticale), quindi non sono incluse in Available Scale. Nella pratica, la pentatonica \u00E8 spesso la prima scelta.',
    usecases: 'Casi d\'uso',
    uc1_q: '"Voglio trovare come disporre questo accordo sui pad"',
    uc1_a: '\u2192 Seleziona Root, Quality e Tension in modalit\u00E0 <span class="mode-badge chord">Chord</span> \u2192 Controlla le disposizioni nei voicing box',
    uc2_q: '"Voglio vedere una scala della mia lezione sui pad"',
    uc2_a: '\u2192 Seleziona tonalit\u00E0 e scala in modalit\u00E0 <span class="mode-badge scale">Scale</span>. 31 scale disponibili',
    uc3_q: '"Voglio creare una progressione di accordi per il mio DAW"',
    uc3_a: '\u2192 Salva gli accordi negli slot di memoria \u2192 MIDI Export per importare nel tuo DAW',
    uc4_q: '"A quale tonalit\u00E0 appartiene questo accordo?"',
    uc4_a: '\u2192 Ricerca inversa nel pannello Available Scale. Alterna tra ordinamento Practical/Diatonic',
    uc7_q: '"Voglio trovare accordi pivot per la modulazione"',
    uc7_a: '\u2192 Inserisci un accordo manualmente in modalit\u00E0 <span class="mode-badge chord">Chord</span>. La barra diatonica scompare e Available Scale mostra tutte le tonalit\u00E0 possibili',
    uc5_q: '"Voglio controllare le progressioni di accordi suonandole"',
    uc5_a: '\u2192 Salva gli accordi negli slot di memoria, poi suonali con un controller MIDI o la tastiera del PC',
    uc6_q: '"Voglio verificare un accordo di chitarra sui pad"',
    uc6_a: '\u2192 Clicca sulla tastiera della chitarra per inserire \u2192 Visualizzazione automatica sui pad \u2192 Nome dell\'accordo rilevato',
    quickstart: 'Guida rapida',
    qs_modes: '3 modalit\u00E0',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Visualizza scale e accordi diatonici<br><span class="mode-badge chord">Chord</span> Costruisci accordi in 3 passaggi. Operazioni di voicing disponibili<br><span class="mode-badge input">Input</span> Clicca liberamente sui pad \u2192 Rileva automaticamente i nomi degli accordi',
    qs_first: 'Per iniziare',
    qs_step1: 'Scegli una tonalit\u00E0 (es. C)',
    qs_step2: 'Scegli una scala (es. Major) \u2192 Le note della scala appaiono sui pad',
    qs_step3: 'Clicca un accordo sulla barra diatonica (es. Dm7) \u2192 Note dell\'accordo visualizzate',
    qs_step4: 'Clicca sui pad per riprodurre i suoni. Cambia disposizione nei voicing box',
    qs_step5: 'Salva gli accordi preferiti con <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Scorciatoie da tastiera',
    qs_shortcuts_desc: 'Premi <kbd>?</kbd> per l\'elenco completo delle scorciatoie.<br><kbd>Space</kbd> per riprodurre accordo. <kbd>1</kbd>\u2013<kbd>7</kbd> per accordi diatonici, <kbd>\u2191</kbd><kbd>\u2193</kbd> per rivolti, <kbd>\u2190</kbd><kbd>\u2192</kbd> per movimento cromatico.<br>In Perform mode, usa <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> come griglia 4\u00D74.',
    footer_open: 'Apri 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Scopri di pi\u00F9 sul blog \u2192',
  },
});
