// Français
I18N.addLang('fr', {
  help: {
    title: '64 Pad Explorer V2.12',
    description: 'Un outil pour explorer les gammes, accords et voicings sur une grille de 64 pads.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choisir parmi 12 tonalités',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonique, mineur harmonique, mineur mélodique, pentatonique, Bebop et plus \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Affiche les accords diatoniques de la gamme sélectionnée. Cliquer pour passer en mode Chord',
    chord_mode: 'Chord Mode (3 étapes)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Sélectionner la fondamentale sur le clavier',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choisir le type d\'accord (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Ajouter des tensions (9, b9, #9, 11, #11, 13, b13, etc.). Sélection multiple possible',
    chord_onchord: '<strong>On Chord</strong> \u2014 Utiliser le bouton "/" pour les accords sur basse (accord / note de basse)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettre des notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 pour ajouter des notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Renversements (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Appuyer pour parcourir les dispositions sur le pad (badge pulsant = dispositions alternatives disponibles)',
    display: 'Affichage',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Activer/désactiver le manche de guitare, le clavier et la portée indépendamment',
    display_label: '<strong>Nom / Degré</strong> \u2014 Basculer entre noms de notes (C, D, E) et degrés (R, 2, 3) sur la guitare et les pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Décaler la tessiture des pads par octave',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 presets (Rhodes, FM, etc.)',
    sound_fx: '<strong>Effets</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Cliquer sur un pad ou une voicing box pour jouer le son',
    midi: 'MIDI',
    midi_detect: 'Détection automatique des appareils compatibles WebMIDI',
    midi_push: 'Support de la sortie MIDI série Ableton Push',
    midi_chord: 'Identification automatique des accords à partir des notes jouées',
    color_title: 'Légende des couleurs',
    color_root: '<strong>Root</strong> \u2014 Fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notes de la gamme / Notes de l\'accord',
    color_char: '<strong>Caractéristique</strong> \u2014 Notes qui définissent la gamme/l\'accord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (tierce)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (septième)',
    color_tension: '<strong>Tension</strong> \u2014 Notes de tension',
    color_avoid: '<strong>Avoid</strong> \u2014 Note de la gamme un demi-ton au-dessus d\'une note d\'accord (en mode Chord)',
    color_palette: 'Palette de couleurs : Okabe-Ito (accessible aux daltoniens)',
    input_title: 'Entrée Guitar / Piano',
    input_desc1: 'Cliquer sur le manche de guitare ou le clavier pour saisir des notes',
    input_desc2: 'Les accords sont identifiés automatiquement et reflétés sur le pad',
    input_desc3: '<strong>Clear</strong> \u2014 Effacer la saisie, <strong>Play \u25B6</strong> \u2014 Jouer les notes saisies',
    plain_title: 'Plain Mode',
    plain_desc1: 'Cliquer librement sur les pads pour sélectionner des notes \u2192 Identification d\'accord en temps réel',
    plain_desc2: 'Sans filtre th\u00E9orique. Explorer \u2192 d\u00E9couvrir \u2192 apprendre la th\u00E9orie ensuite',
    plain_desc3: 'Lorsqu\'un accord est d\u00E9tect\u00E9, des \u00E9tiquettes de degr\u00E9 (R, 3, 5, b7, etc.) s\'affichent sur les pads. Guitare, basse, piano et port\u00E9e se mettent \u00E0 jour automatiquement',
    plain_memory: '<strong>Memory</strong> \u2014 Sauvegarder et rappeler des accords dans 16 emplacements',
    plain_export: '<strong>MIDI Export</strong> \u2014 Exporter les accords en m\u00E9moire en fichier MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> bouton ou touche <kbd>p</kbd> pour basculer',
    perform_desc1: 'Jouez les accords des Memory Slots en temps r\u00E9el avec un layout de 16 pads',
    perform_desc2: 'D\u00E9clenchez via le clavier (grille 4\u00D74) ou des pads MIDI',
    perform_desc3: 'Glissez-d\u00E9posez les Slots pour r\u00E9ordonner',
    shortcut_title: 'Raccourcis clavier',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Sélectionner un accord diatonique (gammes à 7 notes)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Sélectionner une voicing box (parcourir les alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Parcourir les renversements (mode Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposer chromatiquement la fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Activer/désactiver Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Activer/désactiver Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycler Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycler Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Effacer l\'accord (mode Chord)',
    sc_pad_explore: '<b>Pad (mode Chord)</b> \u2014 Clic pour activer/désactiver une note \u2014 constructeur mis à jour',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Démarrer Capture / sauvegarder dans l\'emplacement suivant',
    sp_end: '<kbd>e</kbd> \u2014 Terminer Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Rappeler un emplacement mémoire (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposition chromatique (toutes les notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Renversement (la plus basse \u21911oct / la plus haute \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Tout effacer',
    sp_transfer: '<b>Chord switch</b> \u2014 Transférer l\'accord détecté en mode Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Grille 4\u00D74 d\u00E9clenche les Slots 1\u201316',
    pf_midi: 'Les pads MIDI (notes 36\u201354) d\u00E9clenchent aussi les Slots',
    shortcut_common: 'Commun (tous les modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Basculer la vue Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annuler les Memory Slots (jusqu\u0027\u00E0 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Sauvegarder dans un emplacement Plain (depuis n\'importe quel mode)',
    sc_space: '<kbd>Space</kbd> \u2014 Jouer un accord',
    sc_esc: '<kbd>Esc</kbd> \u2014 Désélectionner la voicing box / fermer l\'aide',
    sc_help: '<kbd>?</kbd> \u2014 Afficher/masquer l\'aide',
    footer: '64 Pad Explorer V2.10 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caractéristique',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Fermer',
    slot_hint: 'Cliquer pour sélectionner \u2192 Save(c) / Shift+clic pour effacer',
  },
  label: {
    note_name: 'Note',
    degree: 'Degré',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
    guide: 'Guide',
  },
  plain: {
    status_idle: 'Appuyer sur Capture pour commencer à construire des accords',
    status_capturing: 'Capture : Slot {slot}/16 \u2014 Cliquer sur les pads, puis Capture pour sauvegarder',
    status_editing: 'Édition : Slot {slot} \u2014 Cliquer sur les pads pour modifier',
    notes_label: 'Notes : ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} sélectionné',
    slot_cleared: 'Slot {slot} effacé',
    undo: 'Annuler',
    no_chords: 'Aucun accord dans les emplacements mémoire',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Sélectionner la fondamentale',
  },
  midi: {
    all_devices: 'Tous les appareils',
  },
  memory: {
    slot_empty: 'Slot {slot} : Vide',
    midi_selected: 'MIDI : {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS : {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play : {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Tout afficher',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guide',
    tagline: 'Un outil navigateur pour explorer les gammes, accords et voicings sur une grille de 64 pads.<br>Aucune source sonore requise \u2014 juste Chrome.',
    cta: 'Ouvrir l\u0027appli',
    features: 'Fonctionnalit\u00E9s',
    feat_sound: '<strong>Aucune source sonore requise</strong> \u2014 Le son est jou\u00E9 directement dans Chrome. 4 presets orgue + 7 presets piano \u00E9lectrique int\u00E9gr\u00E9s. Effets (reverb, phaser, flanger, tremolo, filtre) inclus',
    feat_input: '<strong>Aucune comp\u00E9tence de pad requise</strong> \u2014 Construisez des accords en 3 \u00E9tapes. Tensions affich\u00E9es. Cliquez sur les pads pour saisir directement',
    feat_detect: '<strong>D\u00E9tection d\u0027accords</strong> \u2014 D\u00E9tection en temps r\u00E9el du nom d\u0027accord \u00E0 partir des notes cliqu\u00E9es. Supporte omit, accords sur basse et candidats multiples',
    feat_instruments: '<strong>Affichage Guitar / Bass / Keyboard</strong> \u2014 Affiche les notes d\u0027accord sur le manche de guitare, la basse et le piano. La saisie sur le manche de guitare se r\u00E9percute automatiquement sur les pads',
    feat_scales: '<strong>Affichage des gammes</strong> \u2014 31 gammes \u00D7 12 tonalit\u00E9s. Diatonique, mineur harmonique, mineur m\u00E9lodique, pentatonique, Bebop et plus',
    feat_diatonic: '<strong>Affichage des accords diatoniques</strong> \u2014 Les accords diatoniques sont affich\u00E9s sur une barre pour la gamme s\u00E9lectionn\u00E9e. Cliquez ou utilisez les raccourcis pour jouer instantan\u00E9ment',
    feat_voicing: '<strong>Op\u00E9rations de voicing</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Fl\u00E8ches pour les inversions, boutons pour les doigt\u00E9s multiples',
    feat_memory: '<strong>M\u00E9moire d\u0027accords</strong> \u2014 Sauvegardez vos accords favoris dans 16 emplacements. Exportez en fichiers MIDI pour votre DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Jouez les accords en m\u00E9moire en temps r\u00E9el avec 16 pads ou votre clavier PC',
    feat_parent: '<strong>Recherche invers\u00E9e Available Scale</strong> \u2014 Trouvez les gammes contenant votre accord. Voyez les Available Tensions d\u0027un coup d\u0027\u0153il. Basculement Practical/Diatonic',
    feat_pivot: '<strong>Pens\u00E9e accord pivot</strong> \u2014 Saisissez un accord manuellement et la barre diatonique dispara\u00EEt, affichant toutes les tonalit\u00E9s auxquelles votre accord pourrait appartenir. Id\u00E9al pour l\u0027analyse de modulation',
    feat_dimming: '<strong>Affichage pratique des Tensions</strong> \u2014 Pour les accords de 7\u00E8me non dominante, les tensions peu courantes (b9, #9, b13, etc.) sont att\u00E9nu\u00E9es. Toujours s\u00E9lectionnables',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 langues (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Captures d\u0027\u00E9cran',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'S\u00E9lectionnez une tonalit\u00E9 et une gamme pour voir les notes de gamme color\u00E9es sur la grille de 64 pads. Choisissez des accords depuis la barre diatonique.',
    ss_scale_alt: 'Scale Mode \u2014 Affichage de la gamme de C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (orange), notes de gamme (bleu), notes caract\u00E9ristiques (jaune)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construisez des accords en 3 \u00E9tapes : Root \u2192 Quality \u2192 Tension. Ajustez les voicings avec inversions, Drop, Shell et Omit. Utilisez le panneau Parent Scale pour la recherche invers\u00E9e.',
    ss_chord_alt: 'Chord Mode \u2014 Affichage de l\u0027accord Dm7 avec grille de tensions',
    ss_chord_caption: 'Dm7 \u2014 Notes d\u0027accord, 3rd (rose), 7th (vert). V\u00E9rifiez les dispositions dans les voicing boxes',
    ss_plain: '<span class="mode-badge plain">Plain</span> Plain Mode',
    ss_plain_desc: 'Cliquez librement sur les pads pour une d\u00E9tection d\u0027accords en temps r\u00E9el. Comprenez les accords m\u00EAme sans conna\u00EEtre la th\u00E9orie.',
    ss_plain_alt: 'Plain Mode \u2014 D\u00E9tection en temps r\u00E9el de C7',
    ss_plain_caption: 'C7 \u2014 Cliquez sur les pads pour d\u00E9tecter automatiquement les noms d\u0027accords. Candidats multiples affich\u00E9s',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Placez les accords sauvegard\u00E9s sur 16 pads pour une performance en temps r\u00E9el via clavier ou pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 emplacements avec accords',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 sauvegard\u00E9s dans les emplacements. Jouez avec la grille clavier 4\u00D74',
    ss_parent: 'Available Scale + Accord Pivot',
    ss_parent_desc: 'Recherche invers\u00E9e des gammes contenant votre accord. Basculez entre tri Practical (par utilit\u00E9) et Diatonic (par th\u00E9orie). La saisie manuelle d\u0027accord masque la barre diatonique pour l\u0027analyse d\u0027accords pivot.',
    ss_parent_alt: 'Panneau Parent Scale et affichage du manche de guitare',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions affich\u00E9es',
    ss_parent_note: '\u203B Les gammes pentatoniques/blues sont modales (approche horizontale) et appartiennent \u00E0 un syst\u00E8me diff\u00E9rent de la th\u00E9orie des gammes par accord (correspondance verticale), elles ne sont donc pas incluses dans Available Scale. En pratique, la pentatonique est souvent le premier choix.',
    usecases: 'Cas d\u0027utilisation',
    uc1_q: '\u00AB Je veux trouver comment voicer cet accord sur les pads \u00BB',
    uc1_a: '\u2192 S\u00E9lectionnez Root, Quality et Tension en mode <span class="mode-badge chord">Chord</span> \u2192 V\u00E9rifiez les dispositions dans les voicing boxes',
    uc2_q: '\u00AB Je veux voir une gamme de ma le\u00E7on sur les pads \u00BB',
    uc2_a: '\u2192 S\u00E9lectionnez tonalit\u00E9 et gamme en mode <span class="mode-badge scale">Scale</span>. 31 gammes disponibles',
    uc3_q: '\u00AB Je veux cr\u00E9er une progression d\u0027accords pour mon DAW \u00BB',
    uc3_a: '\u2192 Sauvegardez les accords dans les emplacements m\u00E9moire \u2192 MIDI Export pour importer dans votre DAW',
    uc4_q: '\u00AB \u00C0 quelle tonalit\u00E9 appartient cet accord ? \u00BB',
    uc4_a: '\u2192 Recherche invers\u00E9e dans le panneau Available Scale. Basculez entre tri Practical/Diatonic',
    uc7_q: '\u00AB Je veux trouver des accords pivot pour la modulation \u00BB',
    uc7_a: '\u2192 Saisissez un accord manuellement en mode <span class="mode-badge chord">Chord</span>. La barre diatonique dispara\u00EEt et Available Scale affiche toutes les tonalit\u00E9s possibles',
    uc5_q: '\u00AB Je veux v\u00E9rifier des progressions d\u0027accords en les jouant \u00BB',
    uc5_a: '\u2192 Sauvegardez les accords dans les slots m\u00E9moire, puis jouez-les avec un contr\u00F4leur MIDI ou le clavier du PC',
    uc6_q: '\u00AB Je veux v\u00E9rifier un accord de guitare sur les pads \u00BB',
    uc6_a: '\u2192 Cliquez sur le manche de guitare pour saisir \u2192 Affichage automatique sur les pads \u2192 Nom d\u0027accord d\u00E9tect\u00E9',
    quickstart: 'D\u00E9marrage rapide',
    qs_modes: '3 modes',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Afficher les gammes et accords diatoniques<br><span class="mode-badge chord">Chord</span> Construire des accords en 3 \u00E9tapes. Op\u00E9rations de voicing disponibles<br><span class="mode-badge plain">Plain</span> Cliquer librement sur les pads \u2192 D\u00E9tection automatique des noms d\u0027accords',
    qs_first: 'Pour commencer',
    qs_step1: 'Choisissez une tonalit\u00E9 (ex : C)',
    qs_step2: 'Choisissez une gamme (ex : Major) \u2192 Les notes de gamme apparaissent sur les pads',
    qs_step3: 'Cliquez sur un accord dans la barre diatonique (ex : Dm7) \u2192 Notes d\u0027accord affich\u00E9es',
    qs_step4: 'Cliquez sur les pads pour jouer les sons. Changez les dispositions dans les voicing boxes',
    qs_step5: 'Sauvegardez vos accords favoris avec <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Raccourcis clavier',
    qs_shortcuts_desc: 'Appuyez sur <kbd>?</kbd> pour la liste compl\u00E8te des raccourcis.<br><kbd>Space</kbd> pour jouer un accord. <kbd>1</kbd>\u2013<kbd>7</kbd> pour les accords diatoniques, <kbd>\u2191</kbd><kbd>\u2193</kbd> pour les inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> pour le mouvement chromatique.<br>En Perform mode, utilisez <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> comme grille 4\u00D74.',
    footer_open: 'Ouvrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer V2.12 \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'En savoir plus sur le blog \u2192',
  },
});
