// English (fallback)
I18N.addLang('en', {
  help: {
    title: '64 Pad Explorer',
    description: 'A tool for exploring scales, chords, and voicings on a 64-pad grid.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choose from 12 keys',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Shows diatonic chords for the selected scale. Click to enter Chord mode',
    chord_mode: 'Chord Mode (3 Steps)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Select root on the piano keyboard',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choose chord type (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Add tensions (9, b9, #9, 11, #11, 13, b13, etc.). Multiple selections OK',
    chord_onchord: '<strong>On Chord</strong> \u2014 Use the "/" button for slash chords (chord over bass note)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omit notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 to add notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversions (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tap to cycle through pad layout options (pulsing badge = alternative layouts available)',
    display: 'Display',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Toggle guitar fretboard, piano keyboard, and staff notation independently',
    display_label: '<strong>Note Name / Degree</strong> \u2014 Switch between note names (C, D, E) and degrees (R, 2, 3) on guitar and pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Shift pad range by octave',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Toggle sound on/off with the speaker icon',
    sound_select: '<strong>ORGAN / E.PIANO</strong> \u2014 Select a sound engine. Press \u25BC to open the detail panel for presets and effects',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 9 presets (Rhodes 1-5, FM EP 1-2, jRhodes3c Sampler)',
    sound_fx: '<strong>Effects</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Click a pad or voicing box to play sound',
    midi: 'MIDI',
    midi_detect: 'Auto-detects WebMIDI-compatible devices',
    midi_push: 'Supports Ableton Push serial MIDI output',
    midi_chord: 'Auto-identifies chords from input notes',
    color_title: 'Color Legend',
    color_root: '<strong>Root</strong> \u2014 Root note',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Scale notes / Chord tones',
    color_char: '<strong>Characteristic</strong> \u2014 Notes that define the scale/chord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (3rd)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (7th)',
    color_tension: '<strong>Tension</strong> \u2014 Tension notes',
    color_avoid: '<strong>Avoid</strong> \u2014 Scale note a half step above a chord tone (in Chord mode)',
    color_palette: 'Color palette: Okabe-Ito (color vision accessible)',
    input_title: 'Guitar / Piano Input',
    input_desc1: 'Click the guitar fretboard or piano keyboard to input notes',
    input_desc2: 'Chords are auto-identified from input and reflected on the pad',
    input_desc3: '<strong>Clear</strong> \u2014 Clear input, <strong>Play \u25B6</strong> \u2014 Play input notes',
    input_title: 'Input Mode',
    input_desc1: 'Click pads freely to select notes \u2192 Real-time chord identification',
    input_desc2: 'No theory filter. Explore \u2192 discover \u2192 learn theory afterward',
    input_desc3: 'When a chord is detected, degree labels (R, 3, 5, b7, etc.) appear on pads. Guitar, bass, piano, and staff update automatically',
    input_memory: '<strong>Memory</strong> \u2014 Save and recall chords in 16 slots',
    input_export: '<strong>MIDI Export</strong> \u2014 Export memory chords as a MIDI file',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> button or <kbd>p</kbd> key to switch',
    perform_desc1: 'Play memory slot chords in real-time with a 16-pad layout',
    perform_desc2: 'Trigger via keyboard (4\u00D74 grid) or MIDI pads',
    perform_desc3: 'Drag & drop slots to reorder',
    shortcut_title: 'Keyboard Shortcuts',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Select diatonic chord (7-note scales)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Select voicing box (cycles alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Cycle inversions (Chord mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic root transpose',
    sc_omit: '<kbd>o</kbd> \u2014 Toggle Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Toggle Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycle Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycle Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Clear chord (Chord mode)',
    sc_pad_explore: '<b>Pad (Chord mode)</b> \u2014 Click pad to toggle note \u2014 builder updates automatically',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Start Capture / save to next slot',
    sp_end: '<kbd>e</kbd> \u2014 End Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recall memory slot (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic transpose (all notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversion (lowest \u21911oct / highest \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Clear all',
    sp_transfer: '<b>Chord switch</b> \u2014 Transfer detected chord to Chord mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74 grid triggers slots 1\u201316',
    pf_midi: 'MIDI pads (notes 36\u201354) also trigger slots',
    shortcut_common: 'Common (All Modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Toggle Perform view',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Undo memory slots (up to 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Save to Input memory slot (from any mode)',
    sc_space: '<kbd>Space</kbd> \u2014 Play current chord',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselect voicing box / close Help',
    sc_help: '<kbd>?</kbd> \u2014 Toggle Help',
    footer: '64 Pad Explorer V2.10 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Characteristic',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Close',
    slot_hint: 'Click\u2192Save(c) / Shift+#: save / Shift+Click: delete / Opt+Drag: copy',
    save_settings: 'Save Settings',
    sound_hint: 'Select ORGAN or E.PIANO to enable sound',
    tap_to_start: 'Tap to enable sound',
    load_vst: 'Load VST/AU Plugin...',
    affiliate_label: '',
  },
  label: {
    note_name: 'Note',
    degree: 'Degree',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'My Blog',
    guide: 'Guide',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Press Capture to start building chords',
    status_capturing: 'Capturing: Slot {slot}/16 \u2014 Click pads, then Capture to save',
    status_editing: 'Editing: Slot {slot} \u2014 Click pads to modify',
    notes_label: 'Notes: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selected',
    slot_cleared: 'Slot {slot} cleared',
    undo: 'Undo',
    settings_saved: 'Settings saved',
    no_chords: 'No chords in memory slots',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Select root',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Slot {slot}: Empty',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Click to rename bank',
    rename: 'Rename',
    duplicate: 'Duplicate',
    delete: 'Delete',
    rename_prompt: 'Enter bank name:',
    confirm_delete: 'Delete "{name}"?',
    limit_reached: 'Maximum 16 banks',
    cannot_delete_last: 'Cannot delete the last bank',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Show all',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guide',
    tagline: 'A browser tool for exploring scales, chords, and voicings on a 64-pad grid.<br>No sound source needed \u2014 just Chrome.',
    cta: 'Open App',
    features: 'Features',
    feat_sound: '<strong>No sound source needed</strong> \u2014 Sound plays right in Chrome. 4 organ + 7 electric piano presets built in. Effects (reverb, phaser, flanger, tremolo, filter) included',
    feat_input: '<strong>No pad skills required</strong> \u2014 Build chords in 3 steps. Tensions displayed. Click pads to input directly',
    feat_detect: '<strong>Chord detection</strong> \u2014 Real-time chord name detection from clicked notes. Supports omit, slash chords, and multiple candidates',
    feat_instruments: '<strong>Guitar / Bass / Keyboard display</strong> \u2014 Shows chord tones on guitar fretboard, bass, and piano. Guitar fingering input auto-reflects on pads',
    feat_scales: '<strong>Scale display</strong> \u2014 31 scales \u00D7 12 keys. Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more',
    feat_diatonic: '<strong>Diatonic chord display</strong> \u2014 Diatonic chords shown on a bar for the selected scale. Click or use shortcuts to play instantly',
    feat_voicing: '<strong>Voicing operations</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Arrow keys for inversions, buttons for multiple fingerings',
    feat_memory: '<strong>Chord memory</strong> \u2014 Save favorite chords to 16 slots. Export as MIDI files for your DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Play memory chords in real-time using 16 pads or your PC keyboard',
    feat_parent: '<strong>Available Scale reverse lookup</strong> \u2014 Find scales that contain your chord. See available tensions at a glance. Practical/Diatonic sort toggle',
    feat_pivot: '<strong>Pivot chord thinking</strong> \u2014 Manually input a chord and the diatonic bar disappears, showing all keys your chord could belong to. Perfect for modulation analysis',
    feat_dimming: '<strong>Tension practical display</strong> \u2014 For non-dominant 7th chords, uncommon tensions (b9, #9, b13, etc.) are dimmed. Still selectable',
    feat_i18n: '<strong>Multilingual</strong> \u2014 9 languages (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshots',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Select a key and scale to see scale notes color-coded on the 64-pad grid. Choose chords from the diatonic bar.',
    ss_scale_alt: 'Scale Mode \u2014 C Major (Ionian) scale display',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (orange), scale notes (blue), characteristic notes (yellow)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Build chords in 3 steps: Root \u2192 Quality \u2192 Tension. Adjust voicings with inversions, Drop, Shell, and Omit. Use the Parent Scale panel to reverse-lookup scales.',
    ss_chord_alt: 'Chord Mode \u2014 Dm7 chord display with tension grid',
    ss_chord_caption: 'Dm7 \u2014 Chord tones, 3rd (pink), 7th (green). Check layout options in voicing boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Click pads freely for real-time chord detection. Understand chords even without knowing theory.',
    ss_input_alt: 'Input Mode \u2014 C7 real-time chord detection',
    ss_input_caption: 'C7 \u2014 Click pads to auto-detect chord names. Multiple candidates shown',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Place saved chords on 16 pads for real-time performance using keyboard or MIDI pads.',
    ss_perform_alt: 'Perform Mode \u2014 16 slots with chords',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 saved to slots. Play using 4\u00D74 keyboard grid',
    ss_parent: 'Available Scale + Pivot Chord',
    ss_parent_desc: 'Reverse-lookup scales that contain your chord. Toggle between Practical (by usability) and Diatonic (by theory) sorting. Manual chord input hides the diatonic bar for pivot chord analysis.',
    ss_parent_alt: 'Parent Scale panel and guitar fretboard display',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions displayed',
    ss_parent_note: '\u203B Pentatonic/Blues scales are modal (horizontal approach) and belong to a different system from chord-scale theory (vertical mapping), so they are not included in Available Scale. In practice, pentatonic is often the first choice.',
    usecases: 'Use Cases',
    uc1_q: '"I want to find how to voice this chord on pads"',
    uc1_a: '\u2192 Select Root, Quality, and Tension in <span class="mode-badge chord">Chord</span> mode \u2192 Check layouts in voicing boxes',
    uc2_q: '"I want to see a scale from my lesson on the pads"',
    uc2_a: '\u2192 Select key and scale in <span class="mode-badge scale">Scale</span> mode. 31 scales available',
    uc3_q: '"I want to create a chord progression for my DAW"',
    uc3_a: '\u2192 Save chords to memory slots \u2192 MIDI Export to import into your DAW',
    uc4_q: '"Which key does this chord belong to?"',
    uc4_a: '\u2192 Reverse-lookup in the Available Scale panel. Switch between Practical/Diatonic sort for usability ordering',
    uc7_q: '"I want to find pivot chords for modulation"',
    uc7_a: '\u2192 Manually input a chord in <span class="mode-badge chord">Chord</span> mode. The diatonic bar disappears and Available Scale shows all keys your chord could belong to',
    uc5_q: '"I want to check chord progressions by playing them"',
    uc5_a: '\u2192 Save chords to memory slots, then play them with a MIDI controller or PC keyboard',
    uc6_q: '"I want to check guitar chords on the pads"',
    uc6_a: '\u2192 Click guitar fretboard to input \u2192 Auto-displayed on pads \u2192 Chord name detected',
    quickstart: 'Quick Start',
    qs_modes: '3 Modes',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Display scales and diatonic chords<br><span class="mode-badge chord">Chord</span> Build chords in 3 steps. Voicing operations available<br><span class="mode-badge input">Input</span> Click pads freely \u2192 Auto-detect chord names',
    qs_first: 'Getting Started',
    qs_step1: 'Choose a key (e.g., C)',
    qs_step2: 'Choose a scale (e.g., Major) \u2192 Scale notes appear on pads',
    qs_step3: 'Click a chord on the diatonic bar (e.g., Dm7) \u2192 Chord tones displayed',
    qs_step4: 'Click pads to play sounds. Change layouts in voicing boxes',
    qs_step5: 'Save favorite chords with <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Keyboard Shortcuts',
    qs_shortcuts_desc: 'Press <kbd>?</kbd> for the full shortcut list.<br><kbd>Space</kbd> to play chord. <kbd>1</kbd>\u2013<kbd>7</kbd> for diatonic chords, <kbd>\u2191</kbd><kbd>\u2193</kbd> for inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> for chromatic movement.<br>In Perform mode, use <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> as a 4\u00D74 grid.',
    footer_open: 'Open 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Learn more on the blog \u2192',
    version_history: 'Version History',
    vh_37: '<b>V3.7</b> \u2014 Voicing position preservation (auto-maintain fingering shape on chromatic movement). Pad grid, staff, and chord detection during playback. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 MIDI file playback \u2192 pad lighting (timeline playback, chord name display, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 E.PIANO sampler (Rhodes Mark I). 7 EP presets. Sound ON/OFF toggle. iPad support',
    vh_31: '<b>V3.1</b> \u2014 Velocity sensitivity (4 parameters + curve visualization). Push 3 octave button support. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 Multiple memory banks (16 slots \u00D7 up to 16 banks, switch/duplicate/rename)',
    vh_218: '<b>V2.18</b> \u2014 Auto save/restore all settings (key/scale/sound/MIDI/memory)',
    vh_213: '<b>V2.13</b> \u2014 Instrument scale overlay (guitar/bass/piano show Available Scale). Pad degree labels. Octave-linked playback',
    vh_27: '<b>V2.7</b> \u2014 Tension addition mode (pad/guitar/bass/keyboard chord synthesis \u2192 Available Scale filtering)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, scale overlay on pads)',
    vh_19: '<b>V1.9</b> \u2014 9 languages',
    vh_18: '<b>V1.8</b> \u2014 Perform mode, 16 memory slots, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Plain mode, MIDI/CHS export',
    vh_10: '<b>V1.0</b> \u2014 Initial release (Scale/Chord/Voicing/Sound/MIDI)',
  },
});
