// English (fallback)
I18N.addLang('en', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: 'A tool for exploring scales, chords, and voicings on a 64-pad grid.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choose from 12 keys',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Shows diatonic chords for the selected scale. Click to enter Chord mode',
    chord_mode: 'Chord Mode (3 Steps)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Select root on the piano keyboard',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choose chord type (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Add tensions (9, b9, #9, 11, #11, 13, b13, etc.). Multiple selections OK',
    chord_onchord: '<strong>On Chord</strong> \u2014 Use the "/" button for slash chords (chord over bass note)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omit notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 to add notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversions (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tap to cycle through pad layout options (pulsing badge = alternative layouts available)',
    display: 'Display',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Toggle guitar fretboard, piano keyboard, and staff notation independently',
    display_label: '<strong>Note Name / Degree</strong> \u2014 Switch between note names (C, D, E) and degrees (R, 2, 3) on guitar and pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Shift pad range by octave',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 presets (Rhodes, FM, etc.)',
    sound_fx: '<strong>Effects</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Click a pad or voicing box to play sound',
    midi: 'MIDI',
    midi_detect: 'Auto-detects WebMIDI-compatible devices',
    midi_push: 'Supports Ableton Push serial MIDI output',
    midi_chord: 'Auto-identifies chords from input notes',
    color_title: 'Color Legend',
    color_root: '<strong>Root</strong> \u2014 Root note',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Scale notes / Chord tones',
    color_char: '<strong>Characteristic</strong> \u2014 Notes that define the scale/chord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (3rd)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (7th)',
    color_tension: '<strong>Tension</strong> \u2014 Tension notes',
    color_avoid: '<strong>Avoid</strong> \u2014 Scale note a half step above a chord tone (in Chord mode)',
    color_palette: 'Color palette: Okabe-Ito (color vision accessible)',
    input_title: 'Guitar / Piano Input',
    input_desc1: 'Click the guitar fretboard or piano keyboard to input notes',
    input_desc2: 'Chords are auto-identified from input and reflected on the pad',
    input_desc3: '<strong>Clear</strong> \u2014 Clear input, <strong>Play \u25B6</strong> \u2014 Play input notes',
    plain_title: 'Plain Mode',
    plain_desc1: 'Click pads freely to select notes \u2192 Real-time chord identification',
    plain_desc2: 'No theory filter. Explore \u2192 discover \u2192 learn theory afterward',
    plain_memory: '<strong>Memory</strong> \u2014 Save and recall chords in 16 slots',
    plain_export: '<strong>MIDI Export</strong> \u2014 Export memory chords as a MIDI file',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> button or <kbd>p</kbd> key to switch',
    perform_desc1: 'Play memory slot chords in real-time with a 16-pad layout',
    perform_desc2: 'Trigger via keyboard (4\u00D74 grid) or MIDI pads',
    perform_desc3: 'Drag & drop slots to reorder',
    shortcut_title: 'Keyboard Shortcuts',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Select diatonic chord (7-note scales)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Select voicing box (cycles alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Cycle inversions (Chord mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic root transpose',
    sc_omit: '<kbd>o</kbd> \u2014 Toggle Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Toggle Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycle Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycle Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Clear chord (Chord mode)',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Start Capture / save to next slot',
    sp_end: '<kbd>e</kbd> \u2014 End Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recall memory slot (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic transpose (all notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversion (lowest \u21911oct / highest \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Clear all',
    sp_transfer: '<b>Chord switch</b> \u2014 Transfer detected chord to Chord mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74 grid triggers slots 1\u201316',
    pf_midi: 'MIDI pads (notes 36\u201354) also trigger slots',
    shortcut_common: 'Common (All Modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Toggle Perform view',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Undo memory slots (up to 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Save to Plain memory slot (from any mode)',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselect voicing box / close Help',
    sc_help: '<kbd>?</kbd> \u2014 Toggle Help',
    footer: '64 Pad Explorer V1.9 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Characteristic',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Close',
    slot_hint: 'Click to select \u2192 Save(c) / Shift+click to clear',
  },
  label: {
    note_name: 'Note',
    degree: 'Degree',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
  },
  plain: {
    status_idle: 'Press Capture to start building chords',
    status_capturing: 'Capturing: Slot {slot}/16 \u2014 Click pads, then Capture to save',
    status_editing: 'Editing: Slot {slot} \u2014 Click pads to modify',
    notes_label: 'Notes: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selected',
    slot_cleared: 'Slot {slot} cleared',
    undo: 'Undo',
    no_chords: 'No chords in memory slots',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Select root',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Slot {slot}: Empty',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
});
