// Français
I18N.addLang('fr', {
  help: {
    title: '64 Pad Explorer',
    description: 'Un outil pour explorer les gammes, accords et voicings sur une grille de 64 pads.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choisir parmi 12 tonalités',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonique, mineur harmonique, mineur mélodique, pentatonique, Bebop et plus \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Affiche les accords diatoniques de la gamme sélectionnée. Cliquer pour passer en mode Chord',
    chord_mode: 'Chord Mode (3 étapes)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Sélectionner la fondamentale sur le clavier',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choisir le type d\'accord (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Ajouter des tensions (9, b9, #9, 11, #11, 13, b13, etc.). Sélection multiple possible',
    chord_text: '<strong>Saisie texte</strong> \u2014 Appuyez sur "/" pour activer. Tapez Cm7, G7(b9,#11), Am7/G etc. directement. Suggestions automatiques',
    chord_onchord: '<strong>On Chord</strong> \u2014 Utiliser le bouton "/" pour les accords sur basse (accord / note de basse)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettre des notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 pour ajouter des notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Renversements (Root, 1st, 2nd, 3rd)',
    inv_1: '1er renversement',
    inv_2: '2e renversement',
    inv_3: '3e renversement',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Appuyer pour parcourir les dispositions sur le pad (badge pulsant = dispositions alternatives disponibles)',
    display: 'Affichage',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Activer/désactiver le manche de guitare, la basse, le clavier et la portée indépendamment. Note : Les positions guitare/basse montrent des doigtés jouables sur l\u2019instrument, elles ne correspondent pas à la disposition du pad',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Affiche le cycle des quintes. Lié à la sélection de tonalité, affichant les accords diatoniques et les fonctions (T/SD/D). Changement en mode mineur pris en charge',
    display_label: '<strong>Nom / Degré</strong> \u2014 Basculer entre noms de notes (C, D, E) et degrés (R, 2, 3) sur la guitare et les pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Décaler la tessiture des pads par octave',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 presets (Rhodes, FM, Clavinet, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtre enveloppe (Auto-Wah). 3 types : Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Saturation analogique. Ajoute une distorsion chaleureuse au son',
    sound_fx: '<strong>Effets</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Cliquer sur un pad ou une voicing box pour jouer le son',
    midi: 'MIDI',
    midi_detect: 'Détection automatique des appareils compatibles WebMIDI',
    midi_push: 'Support de la sortie MIDI série Ableton Push',
    midi_chord: 'Identification automatique des accords à partir des notes jouées',
    color_title: 'Légende des couleurs',
    color_root: '<strong>Root</strong> \u2014 Fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notes de la gamme / Notes de l\'accord',
    color_char: '<strong>Caractéristique</strong> \u2014 Notes qui définissent la gamme/l\'accord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (tierce)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (septième)',
    color_tension: '<strong>Tension</strong> \u2014 Notes de tension',
    color_avoid: '<strong>Avoid</strong> \u2014 Note de la gamme un demi-ton au-dessus d\'une note d\'accord (en mode Chord)',
    color_palette: 'Palette de couleurs : Okabe-Ito (accessible aux daltoniens)',
    input_title: 'Entrée Guitar / Piano',
    input_desc1: 'Cliquer sur le manche de guitare ou le clavier pour saisir des notes',
    input_desc2: 'Les accords sont identifiés automatiquement et reflétés sur le pad',
    input_desc3: '<strong>Clear</strong> \u2014 Effacer la saisie, <strong>Play \u25B6</strong> \u2014 Jouer les notes saisies',
    plain_title: 'Input Mode',
    plain_desc1: 'Cliquer librement sur les pads pour sélectionner des notes \u2192 Identification d\'accord en temps réel',
    plain_desc2: 'Sans filtre th\u00E9orique. Explorer \u2192 d\u00E9couvrir \u2192 apprendre la th\u00E9orie ensuite',
    plain_desc3: 'Lorsqu\'un accord est d\u00E9tect\u00E9, des \u00E9tiquettes de degr\u00E9 (R, 3, 5, b7, etc.) s\'affichent sur les pads. Guitare, basse, piano et port\u00E9e se mettent \u00E0 jour automatiquement',
    plain_memory: '<strong>Memory</strong> \u2014 Sauvegarder et rappeler des accords dans 16 emplacements',
    input_banks: '<strong>Banks</strong> \u2014 16 emplacements \u00D7 jusqu\u0027à 16 banques. Changer avec <kbd>[</kbd> <kbd>]</kbd>. Duplication et renommage pris en charge',
    plain_export: '<strong>MIDI Export</strong> \u2014 Exporter les accords en m\u00E9moire en fichier MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> bouton ou touche <kbd>p</kbd> pour basculer',
    perform_desc1: 'Jouez les accords des Memory Slots en temps r\u00E9el avec un layout de 16 pads',
    perform_desc2: 'D\u00E9clenchez via le clavier (grille 4\u00D74) ou des pads MIDI',
    perform_desc3: 'Glissez-d\u00E9posez les Slots pour r\u00E9ordonner',
    shortcut_title: 'Raccourcis clavier',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Sélectionner un accord diatonique (gammes à 7 notes)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Sélectionner une voicing box (parcourir les alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Parcourir les renversements (mode Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposer chromatiquement la fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Activer/désactiver Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Activer/désactiver Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycler Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycler Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: '<kbd>v</kbd> \u2014 Refléter sur pad / cycler disposition (style guitare \u2194 compact)',
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Cycler position de guitare (précédent / suivant)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Changer la position de basse (précédent / suivant)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON / voicing suivant, <kbd>Shift</kbd>+<kbd>t</kbd> \u2014 précédent',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON / voicing suivant, <kbd>Shift</kbd>+<kbd>k</kbd> \u2014 précédent',
    sc_clear: '<kbd>x</kbd> \u2014 Effacer l\'accord (mode Chord)',
    sc_pad_explore: '<b>Pad (mode Chord)</b> \u2014 Clic pour activer/désactiver une note \u2014 constructeur mis à jour',
    shortcut_plain: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Démarrer Capture / sauvegarder dans l\'emplacement suivant',
    sp_end: '<kbd>e</kbd> \u2014 Terminer Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Rappeler un emplacement mémoire (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposition chromatique (toutes les notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Renversement (la plus basse \u21911oct / la plus haute \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Tout effacer',
    sp_transfer: '<b>Chord switch</b> \u2014 Transférer l\'accord détecté en mode Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Grille 4\u00D74 d\u00E9clenche les Slots 1\u201316',
    pf_midi: 'Les pads MIDI (notes 36\u201354) d\u00E9clenchent aussi les Slots',
    shortcut_common: 'Commun (tous les modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Basculer la vue Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annuler les Memory Slots (jusqu\u0027\u00E0 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Sauvegarder dans un emplacement Input (depuis n\'importe quel mode)',
    sc_space: '<kbd>Space</kbd> \u2014 Jouer un accord',
    sc_esc: '<kbd>Esc</kbd> \u2014 Désélectionner la voicing box / fermer l\'aide',
    sc_help: '<kbd>?</kbd> \u2014 Afficher/masquer l\'aide',
    tips_toggle: 'Afficher les astuces au démarrage',
    footer: '64 Pad Explorer V2.10 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caractéristique',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Fermer',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Shift+#</b> save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Sauvegarder',
    sound_hint: 'Sélectionnez ORGAN ou E.PIANO pour activer le son',
    tap_to_start: 'Appuyez pour activer le son',
    tap_pads: 'Appuyez sur un pad pour jouer !',
    load_vst: 'Charger un plugin VST/AU...',
    affiliate_label: '',
    circle: 'Cycle',
    help: 'Aide',
    oct_down: 'Baisser d\u0027une octave',
    oct_up: 'Monter d\u0027une octave',
    toggle_guitar: 'Afficher/masquer le manche de guitare (Shift+G)',
    toggle_bass: 'Afficher/masquer le manche de basse (Shift+B)',
    toggle_piano: 'Afficher/masquer le clavier de piano (Shift+P)',
    mode_scale: 'Mode Scale \u2014 voir les notes de gamme sur les pads (Tab pour changer)',
    mode_chord: 'Mode Chord \u2014 construire des accords avec voicings (Tab pour changer)',
    mode_input: 'Mode Input \u2014 cliquer librement sur les pads pour d\u00E9tecter les accords (Tab pour changer)',
    play_chord: 'Jouer l\u0027accord actuel (Space)',
    toggle_staff: 'Afficher/masquer la port\u00E9e (Shift+S)',
    toggle_circle: 'Afficher/masquer le cycle des quintes (Shift+C)',
    toggle_sound: 'Afficher/masquer les contr\u00F4les de son',
    sound_mute: 'Son ON/OFF',
    sound_expand: 'Afficher/masquer les r\u00E9glages de son d\u00E9taill\u00E9s',
    input_keys_disabled: 'La s\u00E9lection de tonalit\u00E9 n\u0027est pas utilis\u00E9e en mode Input',
  },
  label: {
    note_name: 'Note',
    degree: 'Degré',
    chord_input: 'Saisir un accord',
    chord_hint: 'Tensions entre ( ): C7(b9,#11) | dim, h=m7♭5 acceptés',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mon Blog',
    guide: 'Guide',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Appuyer sur Capture pour commencer à construire des accords',
    status_capturing: 'Capture : Slot {slot}/16 \u2014 Cliquer sur les pads, puis Capture pour sauvegarder',
    status_editing: 'Édition : Slot {slot} \u2014 Cliquer sur les pads pour modifier',
    notes_label: 'Notes : ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} sélectionné',
    slot_cleared: 'Slot {slot} effacé',
    undo: 'Annuler',
    settings_saved: 'Paramètres sauvegardés',
    no_chords: 'Aucun accord dans les emplacements mémoire',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Sélectionner la fondamentale',
  },
  midi: {
    all_devices: 'Tous les appareils',
  },
  memory: {
    slot_empty: 'Slot {slot} : Vide',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS : {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play : {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Cliquer pour renommer',
    rename: 'Renommer',
    duplicate: 'Dupliquer',
    delete: 'Supprimer',
    rename_prompt: 'Nom de la banque :',
    confirm_delete: 'Supprimer "{name}" ?',
    limit_reached: 'Maximum 16 banques',
    cannot_delete_last: 'Impossible de supprimer la derni\u00E8re banque',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Tout afficher',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guide',
    tagline: 'Un outil navigateur pour explorer les gammes, accords et voicings sur une grille de 64 pads.<br>Aucune source sonore requise \u2014 juste Chrome.',
    cta: 'Ouvrir l\u0027appli',
    features: 'Fonctionnalit\u00E9s',
    feat_sound: '<strong>Aucune source sonore requise</strong> \u2014 Le son est jou\u00E9 directement dans Chrome. 4 presets orgue + 8 presets piano \u00E9lectrique int\u00E9gr\u00E9s. Effets (reverb, phaser, flanger, tremolo, auto filter) inclus',
    feat_input: '<strong>Aucune comp\u00E9tence de pad requise</strong> \u2014 Construisez des accords en 3 \u00E9tapes. Tensions affich\u00E9es. Cliquez sur les pads pour saisir directement',
    feat_text_input: '<strong>Saisie texte d\'accords</strong> \u2014 Appuyez "/" pour saisir Cm7, G7(b9,#11), Am7/G etc. directement. Auto-complétion. Abréviations dim, h(=m7\u266D5) acceptées',
    feat_detect: '<strong>D\u00E9tection d\u0027accords</strong> \u2014 D\u00E9tection en temps r\u00E9el du nom d\u0027accord \u00E0 partir des notes cliqu\u00E9es. Supporte omit, accords sur basse et candidats multiples',
    feat_instruments: '<strong>Affichage Guitar / Bass / Keyboard</strong> \u2014 Affiche les notes d\u0027accord sur le manche de guitare, la basse et le piano. La saisie sur le manche de guitare se r\u00E9percute automatiquement sur les pads. En mode Chord, les positions sont group\u00E9es par corde fondamentale',
    feat_scales: '<strong>Affichage des gammes</strong> \u2014 31 gammes \u00D7 12 tonalit\u00E9s. Diatonique, mineur harmonique, mineur m\u00E9lodique, pentatonique, Bebop et plus',
    feat_diatonic: '<strong>Affichage des accords diatoniques</strong> \u2014 Les accords diatoniques sont affich\u00E9s sur une barre pour la gamme s\u00E9lectionn\u00E9e. Cliquez ou utilisez les raccourcis pour jouer instantan\u00E9ment. Basculement triades/t\u00E9trades',
    feat_voicing: '<strong>Op\u00E9rations de voicing</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Fl\u00E8ches pour les inversions, boutons pour les doigt\u00E9s multiples',
    feat_memory: '<strong>M\u00E9moire d\u0027accords</strong> \u2014 Sauvegardez vos accords favoris dans 16 emplacements. Exportez en fichiers MIDI pour votre DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Jouez les accords en m\u00E9moire en temps r\u00E9el avec 16 pads ou votre clavier PC',
    feat_parent: '<strong>Recherche invers\u00E9e Available Scale</strong> \u2014 Trouvez les gammes contenant votre accord. Voyez les Available Tensions d\u0027un coup d\u0027\u0153il. Basculement Practical/Diatonic',
    feat_pivot: '<strong>Pens\u00E9e accord pivot</strong> \u2014 Saisissez un accord manuellement et la barre diatonique dispara\u00EEt, affichant toutes les tonalit\u00E9s auxquelles votre accord pourrait appartenir. Id\u00E9al pour l\u0027analyse de modulation',
    feat_dimming: '<strong>Affichage pratique des Tensions</strong> \u2014 Pour les accords de 7\u00E8me non dominante, les tensions peu courantes (b9, #9, b13, etc.) sont att\u00E9nu\u00E9es. Toujours s\u00E9lectionnables',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 langues (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Captures d\u0027\u00E9cran',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'S\u00E9lectionnez une tonalit\u00E9 et une gamme pour voir les notes de gamme color\u00E9es sur la grille de 64 pads. Choisissez des accords depuis la barre diatonique.',
    ss_scale_alt: 'Scale Mode \u2014 Affichage de la gamme de C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (orange), notes de gamme (bleu), notes caract\u00E9ristiques (jaune)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construisez des accords en 3 \u00E9tapes : Root \u2192 Quality \u2192 Tension. Ajustez les voicings avec inversions, Drop, Shell et Omit. Utilisez le panneau Parent Scale pour la recherche invers\u00E9e.',
    ss_chord_alt: 'Chord Mode \u2014 Affichage de l\u0027accord Dm7 avec grille de tensions',
    ss_chord_caption: 'Dm7 \u2014 Notes d\u0027accord, 3rd (rose), 7th (vert). V\u00E9rifiez les dispositions dans les voicing boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Cliquez librement sur les pads pour une d\u00E9tection d\u0027accords en temps r\u00E9el. Comprenez les accords m\u00EAme sans conna\u00EEtre la th\u00E9orie.',
    ss_input_alt: 'Input Mode \u2014 D\u00E9tection en temps r\u00E9el de C7',
    ss_input_caption: 'C7 \u2014 Cliquez sur les pads pour d\u00E9tecter automatiquement les noms d\u0027accords. Candidats multiples affich\u00E9s',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Placez les accords sauvegard\u00E9s sur 16 pads pour une performance en temps r\u00E9el via clavier ou pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 emplacements avec accords',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 sauvegard\u00E9s dans les emplacements. Jouez avec la grille clavier 4\u00D74',
    ss_parent: 'Available Scale + Accord Pivot',
    ss_parent_desc: 'Recherche invers\u00E9e des gammes contenant votre accord. Basculez entre tri Practical (par utilit\u00E9) et Diatonic (par th\u00E9orie). La saisie manuelle d\u0027accord masque la barre diatonique pour l\u0027analyse d\u0027accords pivot.',
    ss_parent_alt: 'Panneau Parent Scale et affichage du manche de guitare',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions affich\u00E9es',
    ss_parent_note: '\u203B Les gammes pentatoniques/blues sont modales (approche horizontale) et appartiennent \u00E0 un syst\u00E8me diff\u00E9rent de la th\u00E9orie des gammes par accord (correspondance verticale), elles ne sont donc pas incluses dans Available Scale. En pratique, la pentatonique est souvent le premier choix.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'Fonctions de Voicing exclusives HPS',
    ss_hps_voicing_intro: 'Les membres HPS disposent de 3 outils de voicing. Chacun propose des voicings issus d\u0027un instrument et d\u0027une classification diff\u00E9rents, et tous peuvent \u00EAtre refl\u00E9t\u00E9s sur la disposition 64 pads avec \u00AB To Pad \u00BB.',
    ss_tasty: 'TASTY Voicing \u2014 Class\u00E9 par note sup\u00E9rieure',
    ss_tasty_desc: '129 voicings professionnels affich\u00E9s sous forme de tableaux de degr\u00E9s. S\u00E9lectionnez un accord, appuyez sur <kbd>T</kbd> pour activer, et appuyez \u00E0 nouveau pour parcourir les recettes. S\u00E9lection automatique de la position optimale sur les pads.',
    ss_tasty_target: 'Cible : Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'La zone d\u0027info affiche l\u0027ordre d\u0027empilement des degr\u00E9s (ex. : <code>m9 (b3-b7-9-5-1)</code>). C\u0027est la structure du voicing \u2014 quelles notes sont empil\u00E9es du bas vers le haut.',
    ss_tasty_labels_title: 'Signification des \u00E9tiquettes',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Fondamentale (1er degr\u00E9) omise. Courant en jazz/R&B/neo-soul o\u00F9 le bassiste couvre la fondamentale.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5te omise. La 5te a peu de caract\u00E8re tonal, elle est donc remplac\u00E9e par une tension pour un son plus riche.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3ce omise. Se rapproche d\u0027un son sus ou Quartal.',
    ss_tasty_ops_title: 'Commandes',
    ss_stock: 'STOCK Voicing \u2014 Collection de Voicings piano',
    ss_stock_desc: '154 voicings de piano issus de mat\u00E9riels p\u00E9dagogiques, affich\u00E9s en notation de degr\u00E9s. Couvre Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Visualisez les positions r\u00E9elles sur l\u0027affichage clavier, puis utilisez \u00AB To Pad \u00BB pour mapper sur la disposition des pads.',
    ss_stock_ops_title: 'Commandes',
    ss_guitar_pos: 'Guitar Position \u2014 Voicings guitare',
    ss_guitar_pos_desc: 'Calcul automatique des positions d\u0027accords sur le manche de guitare. Cliquez sur le manche pour une saisie manuelle. Utilisez <kbd>V</kbd> \u00AB To Pad \u00BB pour convertir les voicings guitare en disposition de pads. Choix entre disposition style guitare (1 note par rang\u00E9e) et compacte.',
    usecases: 'Cas d\u0027utilisation',
    uc1_q: '\u00AB Je veux trouver comment voicer cet accord sur les pads \u00BB',
    uc1_a: '\u2192 S\u00E9lectionnez Root, Quality et Tension en mode <span class="mode-badge chord">Chord</span> \u2192 V\u00E9rifiez les dispositions dans les voicing boxes',
    uc2_q: '\u00AB Je veux voir une gamme de ma le\u00E7on sur les pads \u00BB',
    uc2_a: '\u2192 S\u00E9lectionnez tonalit\u00E9 et gamme en mode <span class="mode-badge scale">Scale</span>. 31 gammes disponibles',
    uc3_q: '\u00AB Je veux cr\u00E9er une progression d\u0027accords pour mon DAW \u00BB',
    uc3_a: '\u2192 Sauvegardez les accords dans les emplacements m\u00E9moire \u2192 MIDI Export pour importer dans votre DAW',
    uc4_q: '\u00AB \u00C0 quelle tonalit\u00E9 appartient cet accord ? \u00BB',
    uc4_a: '\u2192 Recherche invers\u00E9e dans le panneau Available Scale. Basculez entre tri Practical/Diatonic',
    uc7_q: '\u00AB Je veux trouver des accords pivot pour la modulation \u00BB',
    uc7_a: '\u2192 Saisissez un accord manuellement en mode <span class="mode-badge chord">Chord</span>. La barre diatonique dispara\u00EEt et Available Scale affiche toutes les tonalit\u00E9s possibles',
    uc5_q: '\u00AB Je veux v\u00E9rifier des progressions d\u0027accords en les jouant \u00BB',
    uc5_a: '\u2192 Sauvegardez les accords dans les slots m\u00E9moire, puis jouez-les avec un contr\u00F4leur MIDI ou le clavier du PC',
    uc6_q: '\u00AB Je veux v\u00E9rifier un accord de guitare sur les pads \u00BB',
    uc6_a: '\u2192 Cliquez sur le manche de guitare pour saisir \u2192 Affichage automatique sur les pads \u2192 Nom d\u0027accord d\u00E9tect\u00E9',
    uc8_q: '\u00AB Je veux apprendre des voicings professionnels \u00BB',
    uc8_a: '\u2192 Construisez un accord en mode <span class="mode-badge chord">Chord</span>, puis appuyez sur <kbd>T</kbd> pour TASTY (classification par note sup\u00E9rieure) ou <kbd>K</kbd> pour STOCK (voicings piano). Visualisez avec la notation de degr\u00E9s, utilisez \u00AB To Pad \u00BB pour mapper sur les pads, sauvegardez en m\u00E9moire et exportez vers le DAW',
    quickstart: 'D\u00E9marrage rapide',
    qs_modes: '3 modes',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Afficher les gammes et accords diatoniques<br><span class="mode-badge chord">Chord</span> Construire des accords en 3 \u00E9tapes. Op\u00E9rations de voicing disponibles<br><span class="mode-badge input">Input</span> Cliquer librement sur les pads \u2192 D\u00E9tection automatique des noms d\u0027accords',
    qs_first: 'Pour commencer',
    qs_step1: 'Choisissez une tonalit\u00E9 (ex : C)',
    qs_step2: 'Choisissez une gamme (ex : Major) \u2192 Les notes de gamme apparaissent sur les pads',
    qs_step3: 'Cliquez sur un accord dans la barre diatonique (ex : Dm7) \u2192 Notes d\u0027accord affich\u00E9es',
    qs_step4: 'Cliquez sur les pads pour jouer les sons. Changez les dispositions dans les voicing boxes',
    qs_step5: 'Sauvegardez vos accords favoris avec <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Raccourcis clavier',
    qs_shortcuts_desc: 'Appuyez sur <kbd>?</kbd> pour la liste compl\u00E8te des raccourcis.<br><kbd>Space</kbd> pour jouer un accord. <kbd>1</kbd>\u2013<kbd>7</kbd> pour les accords diatoniques, <kbd>\u2191</kbd><kbd>\u2193</kbd> pour les inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> pour le mouvement chromatique.<br>En Perform mode, utilisez <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> comme grille 4\u00D74.',
    footer_open: 'Ouvrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'En savoir plus sur le blog \u2192',
    version_history: 'Historique des versions',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing : 154 voicings piano avec affichage clavier sp\u00E9cifique MIDI + reflet \u00AB To Pad \u00BB. Guide mis \u00E0 jour avec la section fonctions de voicing HPS',
    vh_32427: '<b>V3.25.0</b> \u2014 Voicing guitare \u2192 reflet sur pad (touche <kbd>V</kbd>). Basculement disposition style guitare (1 note par rang\u00E9e) / compact. Filtre "Tous" des positions de guitare en premier',
    vh_324: '<b>V3.24</b> \u2014 Presets Clavinet ajout\u00E9s (2 dans E.PIANO). Effet Auto Filter (filtre enveloppe / auto-wah) ajout\u00E9',
    vh_323: '<b>V3.23</b> \u2014 Saisie texte d\'accords avec auto-compl\u00E9tion. "/" pour activer, abr\u00E9viations (dim, h=m7\u266D5), tri par tensions',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Basculement triade/t\u00E9trade diatonique. Positions guitare/basse group\u00E9es par corde fondamentale',
    vh_37: '<b>V3.7</b> \u2014 Pr\u00E9servation de la position de voicing (maintien automatique de la forme du doigt\u00E9 lors des mouvements chromatiques). Grille de pads, port\u00E9e et d\u00E9tection d\u0027accords pendant la lecture. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Vid\u00E9o</a>',
    vh_35: '<b>V3.5</b> \u2014 Lecture de fichier MIDI \u2192 \u00E9clairage des pads (lecture en timeline, affichage du nom d\u0027accord, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Rhodes Mark I). 7 presets EP. Interrupteur Sound ON/OFF. Support iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilit\u00E9 v\u00E9locit\u00E9 (4 param\u00E8tres + visualisation de courbe). Support du bouton d\u0027octave Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Vid\u00E9o</a>',
    vh_250: '<b>V2.50</b> \u2014 Plusieurs banques m\u00E9moire (16 slots \u00D7 jusqu\u0027\u00E0 16 banques, changer/dupliquer/renommer)',
    vh_218: '<b>V2.18</b> \u2014 Sauvegarde/restauration automatique de tous les param\u00E8tres (tonalit\u00E9/gamme/son/MIDI/m\u00E9moire)',
    vh_213: '<b>V2.13</b> \u2014 Superposition de gamme d\u0027instrument (guitare/basse/piano affichent Available Scale). \u00C9tiquettes de degr\u00E9 sur pads. Lecture li\u00E9e \u00E0 l\u0027octave',
    vh_27: '<b>V2.7</b> \u2014 Mode d\u0027ajout de tensions (synth\u00E8se d\u0027accords pad/guitare/basse/clavier \u2192 filtrage Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, superposition de gamme sur pads)',
    vh_19: '<b>V1.9</b> \u2014 9 langues',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 emplacements m\u00E9moire, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Mode Plain, export MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Version initiale (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6eR',
    root_5: '5eR',
    root_4: '4eR',
    root_3: '3eR',
    root_2: '2eR',
    open: 'Ouvert',
    all: 'Toutes',
    to_pad: 'Vers Pad',
  },
  tips: [
    'Appuyez sur C pour sauvegarder l\'accord actuel dans Memory',
    'Opt+1~V sauvegarde directement dans un slot (16 touches: 1234 QWER ASDF ZXCV)',
    'Shift+Clic sur un slot Memory pour le supprimer',
    'Opt+Glisser pour copier un slot',
    'Appuyez sur S pour alterner les Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D alterne Drop 2 / Drop 3',
    'Shift+G affiche le manche de guitare',
    'Shift+C affiche le Cycle des Quintes',
    'Tab alterne entre les modes Scale / Chord / Input',
    'Espace joue la gamme ou l\'accord actuel',
    'Exportez tous les slots Memory en fichier MIDI',
    'Connectez un contrôleur MIDI pour jouer les pads',
    'Flèches ↓↑ changent le renversement de l\'accord',
    'Appuyez sur R pour un voicing sans fondamentale',
    'Appuyez sur O pour omettre la 5te',
    'Shift+S affiche la partition',
    'L\'icône de sauvegarde conserve vos réglages entre sessions',
    '[ ] change les banques Memory — gérez plusieurs morceaux',
    'Mode Perform : Déclenchez des accords avec le clavier (1234 / QWER / ASDF / ZXCV) ou pads MIDI',
    'Appuyez sur / en mode Chord pour saisir des noms d\'accords (ex: Cm7, G7(b9,#11))',
  ],
  tips_off: 'Ne plus afficher',
  whats_new: 'Nouveautés',
  whats_new_32427: 'Voicing guitare \u2192 reflet sur pad (touche V). Basculement disposition style guitare / compact',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: 'Preset de son',
    sound_msg: 'Choisissez un preset et appuyez sur un pad pour l\u0027\u00E9couter.\nORGAN, E.PIANO, CLAV \u2014 chacun a plusieurs presets.',
    sound_done: '\u00C7a sonne bien ! Appuyez sur Suivant pour continuer.',
    midi_title: 'Contr\u00F4leur MIDI',
    midi_msg: 'Un contr\u00F4leur MIDI a \u00E9t\u00E9 d\u00E9tect\u00E9. S\u00E9lectionnez votre appareil dans le menu d\u00E9roulant.\nLa sensibilit\u00E9 de v\u00E9locit\u00E9 peut \u00EAtre ajust\u00E9e dans le panneau Sound.',
    midi_no_device: 'Aucun contr\u00F4leur MIDI d\u00E9tect\u00E9 \u2014 pas de souci.\nVous pouvez utiliser les clics sur les pads, l\u0027entr\u00E9e guitare/basse/piano ou la saisie texte d\u0027accords.',
    input_title: 'Trois modes',
    input_msg: 'Scale \u2014 voir les notes de gamme sur la grille de 64 pads\nChord \u2014 construire des accords avec voicings, renversements et tensions\nInput \u2014 cliquer librement sur les pads pour d\u00E9tecter les noms d\u0027accords\n\nChangez avec Tab ou les boutons de mode ci-dessus.',
    instruments_title: 'Entr\u00E9e instrumentale',
    instruments_msg: 'Guitare, Basse, Piano \u2014 activez chaque affichage et cliquez pour saisir des notes directement.\nClic sur le manche \u2192 d\u00E9tection d\u0027accord \u2192 \u00AB Vers Pad \u00BB (V) pour convertir en disposition de pads.\nSaisie texte : appuyez sur / en mode Chord pour saisir des noms d\u0027accords (ex. Cm7, G7(b9,#11)).',
    done_title: 'Pr\u00EAt !',
    done_msg: 'Tout est pr\u00EAt. Explorez librement \u2014 appuyez sur ? pour la liste compl\u00E8te des raccourcis.\nLe Guide contient des captures d\u0027\u00E9cran, des vid\u00E9os et des cas d\u0027utilisation.',
    next: 'Suivant',
    skip_step: 'Passer',
    skip_all: 'Passer le tutoriel',
    open_guide: 'Ouvrir le Guide',
    close: 'Commencer',
    reset: 'Red\u00E9marrer le tutoriel',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: 'Tutoriels',
    cat_getting_started: 'Pour commencer',
    cat_features: 'Fonctionnalit\u00E9s',
    cat_advanced: 'Avanc\u00E9',
    steps_label: '\u00E9tapes',
    reset_all: 'R\u00E9initialiser toute la progression',
    close_selector: 'Fermer',
    hint_available: 'Tutoriel disponible',
    hint_try: 'Essayer',
    // Button label
    btn_label: 'Tutoriels',
    // Shared action labels
    next: 'Suivant',
    skip_step: 'Passer',
    skip_all: 'Passer le tutoriel',
    open_guide: 'Ouvrir le Guide',
    close: 'Termin\u00E9',
    // Onboarding ask dialog
    onboarding_ask_title: 'Tutoriel',
    onboarding_ask_msg: 'Premi\u00E8re visite ? Voulez-vous un tour rapide de l\u0027appli ?',
    onboarding_yes: 'Oui, montrez-moi !',
    onboarding_no: 'Passer',
    // Onboarding
    onboarding_title: 'Premiers pas',
    onboarding_desc: 'Apprenez les bases de 64 Pad Explorer',
    onboarding: {
      sound_title: 'Preset de son',
      sound_msg: 'Choisissez un preset et appuyez sur un pad pour l\u0027\u00E9couter.\nORGAN, E.PIANO, CLAV \u2014 chacun a plusieurs presets.',
      sound_done: '\u00C7a sonne bien ! Appuyez sur Suivant pour continuer.',
      midi_title: 'Contr\u00F4leur MIDI',
      midi_msg: 'Un contr\u00F4leur MIDI a \u00E9t\u00E9 d\u00E9tect\u00E9. S\u00E9lectionnez votre appareil dans le menu d\u00E9roulant.\nLa sensibilit\u00E9 de v\u00E9locit\u00E9 peut \u00EAtre ajust\u00E9e dans le panneau Sound.',
      midi_no_device: 'Aucun contr\u00F4leur MIDI d\u00E9tect\u00E9 \u2014 pas de souci.\nVous pouvez utiliser les clics sur les pads, l\u0027entr\u00E9e guitare/basse/piano ou la saisie texte d\u0027accords.',
      input_title: 'Trois modes',
      input_msg: 'Scale \u2014 voir les notes de gamme sur la grille de 64 pads\nChord \u2014 construire des accords avec voicings, renversements et tensions\nInput \u2014 cliquer librement sur les pads pour d\u00E9tecter les noms d\u0027accords\n\nChangez avec Tab ou les boutons de mode ci-dessus.',
      instruments_title: 'Entr\u00E9e instrumentale',
      instruments_msg: 'Guitare, Basse, Piano \u2014 activez chaque affichage et cliquez pour saisir des notes directement.\nClic sur le manche \u2192 d\u00E9tection d\u0027accord \u2192 \u00AB Vers Pad \u00BB (V) pour convertir en disposition de pads.\nSaisie texte : appuyez sur / en mode Chord pour saisir des noms d\u0027accords (ex. Cm7, G7(b9,#11)).',
      done_title: 'Pr\u00EAt !',
      done_msg: 'Tout est pr\u00EAt. Explorez librement \u2014 appuyez sur ? pour la liste compl\u00E8te des raccourcis.\nLe Guide contient des captures d\u0027\u00E9cran, des vid\u00E9os et des cas d\u0027utilisation.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Mode Scale',
    scale_mode_desc: 'Explorez les gammes sur la grille de 64 pads',
    scale_mode: {
      step1_title: 'Passer en mode Scale',
      step1_msg: 'Le mode Scale illumine les notes de gamme sur la grille.\nAppuyez sur un pad allum\u00E9 pour entendre la note.',
      step2_title: 'Choisir une tonalit\u00E9',
      step2_msg: 'Choisissez une tonalit\u00E9. La grille se met \u00E0 jour instantan\u00E9ment.\nEssayez de passer entre C, G, F \u2014 \u00E9coutez comment le motif de couleurs change.',
      step3_title: 'Choisir une gamme',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 gammes disponibles. Les pads se mettent \u00E0 jour en temps r\u00E9el.',
      step4_title: 'Barre diatonique',
      step4_msg: 'Les accords diatoniques de votre gamme apparaissent ici.\nCliquez sur un accord pour passer en mode Chord avec ce voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Mode Chord',
    chord_mode_desc: 'Construisez des accords \u00E9tape par \u00E9tape',
    chord_mode: {
      step1_title: 'Passer en mode Chord',
      step1_msg: 'Le mode Chord vous permet de construire n\u0027importe quel accord.\n3 \u00E9tapes : Root \u2192 Quality \u2192 Tension.',
      step2_title: '\u00C9tape 1 : Root',
      step2_msg: 'Choisissez une note fondamentale. C, D, E... les 12 notes.\nL\u0027\u00E9cran affiche votre accord actuel.',
      step3_title: '\u00C9tape 2 : Quality',
      step3_msg: 'Choisissez le type d\u0027accord : Maj, min, 7, m7, dim, aug...\nLa grille illumine les notes de l\u0027accord.',
      step4_title: '\u00C9tape 3 : Tensions',
      step4_msg: 'Choisissez d\u0027abord une Quality \u2014 les boutons de tension apparaissent automatiquement.\n9, b9, #9, 11, #11, 13, b13. Plusieurs tensions peuvent \u00EAtre s\u00E9lectionn\u00E9es.',
      step5_title: 'Saisie texte',
      step5_msg: 'Saisissez les noms d\u0027accords directement avec la touche /.\nLes slash chords et les voicings complexes peuvent \u00EAtre entr\u00E9s rapidement.',
    },
    // Input Mode tutorial
    input_mode_title: 'Mode Input',
    input_mode_desc: 'Saisissez des accords via contrôleur MIDI, pads, manche ou clavier',
    input_mode: {
      step1_title: 'Passer en mode Input',
      step1_msg: 'Saisissez des accords via un contrôleur MIDI, en cliquant sur les pads, le manche ou le clavier.\nLa détection d\'accords fonctionne dans tous les modes.',
      step2_title: 'Cliquez sur quelques pads',
      step2_msg: 'Cliquez sur n\u0027importe quels pads de la grille.\nChaque clic active ou d\u00E9sactive une note.',
      step3_title: 'D\u00E9tection d\u0027accords',
      step3_msg: 'Le nom de l\u0027accord d\u00E9tect\u00E9 appara\u00EEt au-dessus de la grille.\nDes \u00E9tiquettes de degr\u00E9 (R, 3, 5, b7...) s\u0027affichent sur chaque pad.',
      step4_title: 'Sauvegarder avec Capture',
      step4_msg: 'La touche <strong>C</strong> sauvegarde l\u0027accord actuel dans le prochain emplacement m\u00E9moire.\nConstruisez des progressions d\u0027accords une par une.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Barre diatonique',
    diatonic_desc: 'Acc\u00E8s en un clic aux accords diatoniques',
    diatonic: {
      step1_title: 'La barre diatonique',
      step1_msg: 'Chaque gamme a son propre jeu d\u0027accords diatoniques.\nIls apparaissent ici \u2014 pr\u00EAts \u00E0 jouer.',
      step2_title: 'Triade / T\u00E9trade',
      step2_msg: 'Basculez entre triades \u00E0 3 notes et accords de septi\u00E8me \u00E0 4 notes.\nLa barre se met \u00E0 jour instantan\u00E9ment.',
      step3_title: 'Cliquez sur un accord',
      step3_msg: 'Cliquez sur un accord de la barre.\nVous pouvez le transformer avec des tensions et plus dans le Chord Builder.',
      step4_title: 'Raccourci clavier',
      step4_msg: 'Appuyez sur 1\u20137 pour s\u00E9lectionner les accords diatoniques instantan\u00E9ment.\nPas besoin de souris.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Sauvegardez des accords et jouez-les en direct',
    memory: {
      step1_title: 'Sauvegarder un accord',
      step1_msg: 'Sauvegardez vos accords favoris.\nEnregistrer les voicings que vous aimez aide pour le beat-making et la pratique.',
      step2_title: '16 emplacements m\u00E9moire',
      step2_msg: 'Fonctionne comme un layout Drumrack de 16 pads sur PUSH, Launchpad, MPC et Maschine \u2014 intuitif \u00E0 utiliser.',
      step3_title: 'Banques m\u00E9moire',
      step3_msg: 'Sur PUSH et Launchpad, le layout Drumrack le rend intuitif \u00E0 utiliser.',
      step4_title: 'Mode Perform',
      step4_msg: 'Les touches du clavier PC correspondent aussi aux 16 pads.',
      step5_title: 'Export MIDI',
      step5_msg: 'Exportez tous les accords en m\u00E9moire en fichier MIDI.\nGlissez dans votre DAW et commencez \u00E0 produire.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Fa\u00E7onnez vos voicings d\u0027accords',
    voicing: {
      step1_title: 'Commandes de voicing',
      step1_msg: 'En mode Chord Builder, diverses transformations sont possibles \u00E0 partir de la forme de base.\nOmit, Shell, Inversion, Drop \u2014 tout est ici.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> est pour le Shell voicing. Apprenez les voicings R37 et R73 de mani\u00E8re fluide sur le pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Les touches de raccourci suivent souvent des mn\u00E9motechniques.\n<strong>O</strong>mit = omettre la 5te. <strong>R</strong>ootless = voicing sans fondamentale.',
      step4_title: 'Renversements',
      step4_msg: 'Contrairement \u00E0 la plupart des logiciels, vous pouvez cr\u00E9er des renversements ultra-rapidement.\nAide aussi \u00E0 comprendre les slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'Pour quand vous voulez mettre en valeur la note du dessus \u2014\nles Drop voicings sont aussi pris en charge.',
      step6_title: 'Voicing Box',
      step6_msg: 'Les pads peuvent avoir plusieurs options de position. Le Voicing Box g\u00E8re cela.\nCliquez sur a, b, c, d etc. sur le pad, ou tapez la lettre, pour voir plusieurs possibilit\u00E9s de voicing.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, effets et volume',
    sound: {
      step1_title: 'Presets de son',
      step1_msg: 'ORGAN (4 types), E.PIANO (8 types), CLAV.\nCliquez sur un pad ou utilisez votre contr\u00F4leur MIDI.',
      step2_title: 'Panneau de d\u00E9tails',
      step2_msg: 'Cliquez sur \u25BC pour d\u00E9plier le panneau de d\u00E9tails.\nEffets, volume et contr\u00F4les de filtre sont ici.',
      step3_title: 'Effets',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nR\u00E9glez-les dans le panneau de d\u00E9tails.',
      step4_title: 'Son ON/OFF',
      step4_msg: 'Activez/d\u00E9sactivez le son avec l\u0027ic\u00F4ne du haut-parleur.\nLe d\u00E9sactiver peut \u00EAtre pratique lors de l\u0027utilisation d\u0027un DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings class\u00E9s par note sup\u00E9rieure. R\u00E9serv\u00E9 aux membres HPS',
    tasty: {
      step1_title: 'Activer TASTY',
      step1_msg: 'S\u00E9lectionnez des voicings raffin\u00E9s que la logique simple ne peut pas produire.\nPenser \u00E0 partir de la note sup\u00E9rieure est utile pour les arrangements de cordes et de cuivres.\n(R\u00E9serv\u00E9 aux membres HPS)',
      step2_title: 'Parcourir les recettes',
      step2_msg: 'Appuyez \u00E0 nouveau sur T pour parcourir les voicings.\nShift+T revient en arri\u00E8re. Le compteur indique votre position.',
      step3_title: 'Notation en degr\u00E9s',
      step3_msg: 'La zone d\u0027info affiche l\u0027empilement des degr\u00E9s \u2014 ex. m9 (b3-b7-9-5-1).\nC\u0027est la structure du voicing du bas vers le haut.',
      step4_title: 'Vers Pad',
      step4_msg: 'Optimisation de pads que les logiciels classiques ne peuvent pas faire.\nProfitez aussi de jouer des voicings \u00E9l\u00E9gants sur les pads.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Voicings idiomatiques classiques du piano. R\u00E9serv\u00E9 aux membres HPS',
    stock: {
      step1_title: 'Activer STOCK',
      step1_msg: 'Conna\u00EEtre les voicings sp\u00E9cifiques au piano vous aide \u00E0 sortir du jeu en forme de base uniquement.\n154 voicings piano en notation de degr\u00E9s.\n(R\u00E9serv\u00E9 aux membres HPS)',
      step2_title: 'Parcourir les voicings',
      step2_msg: 'Appuyez \u00E0 nouveau sur K pour avancer.\nShift+K revient en arri\u00E8re.',
      step3_title: 'Vue clavier',
      step3_msg: 'Activez l\u0027affichage Piano pour voir les positions r\u00E9elles.\nLe voicing prend vie sur le clavier.',
      step4_title: 'Vers Pad',
      step4_msg: 'Cliquez sur \u00AB Vers Pad \u00BB pour mapper le voicing sur les pads.\nSauvegardez en m\u00E9moire et exportez vers votre DAW.',
    },
    // Circle of Fifths tutorial
    circle_title: 'Cycle des quintes',
    circle_desc: 'Les relations entre tonalit\u00E9s en un coup d\u0027\u0153il',
    circle: {
      step1_title: 'Ouvrir le cycle',
      step1_msg: 'Appuyez sur Shift+C ou cliquez sur le bouton du cycle.\nLe cycle des quintes appara\u00EEt en dessous.',
      step2_title: 'Lien de tonalit\u00E9',
      step2_msg: 'V\u00E9rifiez rapidement les accords de substitution et les diatoniques importants pour l\u0027interpr\u00E9tation et la composition.',
      step3_title: 'Fonctions diatoniques',
      step3_msg: 'Contrairement au cycle des quintes classique, 64 Pad Explorer vous permet de choisir 3 types de mineur (Natural/Harmonic/Melodic) en tonalit\u00E9 mineure.\nFacilite la ma\u00EEtrise des tonalit\u00E9s mineures complexes.',
    },
    // Settings tutorial
    settings_title: 'Affichage & R\u00E9glages',
    settings_desc: 'Personnalisez votre espace de travail',
    settings: {
      step1_title: 'Panneaux d\u0027instruments',
      step1_msg: 'Guitar affiche les voicings courants lorsque vous s\u00E9lectionnez un accord dans le Chord Builder.\nEn mode Input, vous pouvez aussi saisir depuis guitare, basse et clavier.',
      step2_title: 'Noms / Degr\u00E9s',
      step2_msg: 'Basculez entre noms de notes (C, D, E) et degr\u00E9s (R, 2, 3).\nS\u0027applique aux pads et \u00E0 l\u0027affichage guitare.',
      step3_title: 'D\u00E9calage d\u0027octave',
      step3_msg: 'Utilisez \u25B2\u25BC pour d\u00E9caler la tessiture des pads d\u0027une octave.\nLes boutons octave de Push 3 se synchronisent automatiquement.',
      step4_title: 'Tout sauvegarder',
      step4_msg: 'Cliquez sur l\u0027ic\u00F4ne de sauvegarde pour conserver tous les r\u00E9glages.\nTonalit\u00E9, gamme, son, m\u00E9moire, voicing \u2014 tout est pr\u00E9serv\u00E9.',
    },
  },
});
