// 日本語
I18N.addLang('ja', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: '64パッド上のスケール・コード・ボイシングを探索するツール。',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 12キーから選択',
    scale_scale: '<strong>Scale</strong> \u2014 ダイアトニック、ハーモニックマイナー、メロディックマイナー、ペンタトニック、ビバップ等 31種',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 選択したスケールのダイアトニックコードを表示。クリックでChordモードへ',
    chord_mode: 'Chord Mode（3ステップ）',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 ピアノ鍵盤でルートを選択',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 コードタイプを選択（Maj, m, aug, dim, sus 等）',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 テンションを追加（9, b9, #9, 11, #11, 13, b13 等）。複数選択可',
    chord_onchord: '<strong>On Chord</strong> \u2014 「/」ボタンでスラッシュコード（分数コード）を指定',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 音を省略',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 シェルボイシング（+1, +2で音を追加）',
    voicing_inv: '<strong>Inversion</strong> \u2014 転回（Root, 1st, 2nd, 3rd）',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 ドロップボイシング',
    voicing_box: '<strong>ボイシングボックス</strong> \u2014 パッド上の配置候補をタップで切り替え（脈動バッジ = 代替配置あり）',
    display: '表示',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 ギターフレットボード、ピアノ鍵盤、五線譜を個別にON/OFF',
    display_label: '<strong>音名/度数</strong> \u2014 ギター・パッド上の表示を音名(C, D, E)と度数(R, 2, 3)で切り替え',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 パッドの音域をオクターブシフト',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4プリセット（Jazz, Perc, Full, Gospel）',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7プリセット（Rhodes, FM等）',
    sound_fx: '<strong>エフェクト</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'パッドをクリック、またはボイシングボックスをクリックで発音',
    midi: 'MIDI',
    midi_detect: 'WebMIDI対応デバイスを自動検出',
    midi_push: 'Ableton Push のシリアルMIDI出力に対応',
    midi_chord: '入力した音からコードを自動判定',
    color_title: '色の意味',
    color_root: '<strong>Root</strong> \u2014 ルート音',
    color_scale: '<strong>Scale / Chord</strong> \u2014 スケール音・コードトーン',
    color_char: '<strong>特性音</strong> \u2014 そのスケール/コードを特徴づける音',
    color_3rd: '<strong>3rd</strong> \u2014 ガイドトーン（3度）',
    color_7th: '<strong>7th</strong> \u2014 ガイドトーン（7度）',
    color_tension: '<strong>Tension</strong> \u2014 テンション音',
    color_avoid: '<strong>Avoid</strong> \u2014 コードトーンの半音上のスケール音（Chordモード時）',
    color_palette: '配色: Okabe-Ito（色覚多様性対応）',
    input_title: 'ギター・ピアノ入力',
    input_desc1: 'ギターフレットボード / ピアノ鍵盤をクリックして音を入力',
    input_desc2: '入力した音からコードを自動判定してパッドに反映',
    input_desc3: '<strong>Clear</strong> \u2014 入力をクリア、<strong>Play \u25B6</strong> \u2014 入力した音を再生',
    plain_title: 'Plain Mode',
    plain_desc1: 'パッドをクリックして自由に音を選択 \u2192 コード名をリアルタイム判定',
    plain_desc2: '理論フィルタなし。探索 \u2192 発見 \u2192 理論を後から知る',
    plain_memory: '<strong>Memory</strong> \u2014 16スロットにコードを保存・呼び出し',
    plain_export: '<strong>MIDI Export</strong> \u2014 メモリーのコードをMIDIファイルとして書き出し',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> ボタンまたは <kbd>p</kbd> キーで切替',
    perform_desc1: 'メモリースロットのコードを16パッド配置でリアルタイム演奏',
    perform_desc2: 'キーボード（4\u00D74グリッド）またはMIDIパッドで発音',
    perform_desc3: 'スロットのドラッグ&ドロップで並び替え可能',
    shortcut_title: 'キーボードショートカット',
    shortcut_scale_chord: 'Scale / Chord モード',
    sc_diatonic: '<kbd>1</kbd>〜<kbd>7</kbd> \u2014 ダイアトニックコード選択（7音スケール時）',
    sc_voicing: '<kbd>a</kbd>〜<kbd>i</kbd> \u2014 ボイシングボックス選択（代替配置の循環も可）',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 転回形の切り替え（Chordモード時）',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 ルートを半音移動（同型コードのトランスポーズ）',
    sc_omit: '<kbd>o</kbd> \u2014 Omit 5 切り替え',
    sc_rootless: '<kbd>r</kbd> \u2014 Rootless 切り替え',
    sc_shell: '<kbd>s</kbd> \u2014 Shell循環（off \u2192 1-3-7 \u2192 1-7-3 \u2192 off）',
    sc_drop: '<kbd>d</kbd> \u2014 Drop循環（off \u2192 Drop 2 \u2192 Drop 3 \u2192 off）',
    sc_clear: '<kbd>x</kbd> \u2014 コードクリア（Chordモード）',
    shortcut_plain: 'Plain モード',
    sp_capture: '<kbd>c</kbd> \u2014 Capture 開始/次のスロットへ保存',
    sp_end: '<kbd>e</kbd> \u2014 Capture 終了',
    sp_recall: '<kbd>1</kbd>〜<kbd>9</kbd>, <kbd>0</kbd> \u2014 メモリースロット呼び出し（Edit）',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移動（全ノート\u00B11）',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 転回形（最低音\u21911oct / 最高音\u21931oct）',
    sp_clear: '<kbd>x</kbd> \u2014 全クリア',
    sp_transfer: '<b>Chord切替</b> \u2014 検出コードをChordモードに引き継ぎ',
    shortcut_perform: 'Perform モード',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74グリッドでスロット1〜16を発音',
    pf_midi: 'MIDIパッド（ノート36〜54）でも発音可能',
    shortcut_common: '共通（全モード）',
    sc_perform: '<kbd>p</kbd> \u2014 Perform表示の切り替え',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 メモリースロットのUndo（最大30回）',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>〜<kbd>0</kbd> \u2014 Plainメモリースロットに保存（どのモードからでも）',
    sc_esc: '<kbd>Esc</kbd> \u2014 ボイシングボックス選択解除 / ヘルプを閉じる',
    sc_help: '<kbd>?</kbd> \u2014 ヘルプ表示切替',
    footer: '64 Pad Explorer V1.9 \u2014 HPS（Hardcore Pad Style）',
  },
  legend: {
    characteristic: '特性音',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: '閉じる',
    slot_hint: 'クリックで選択 \u2192 Save(c) / Shift+クリックで消去',
  },
  label: {
    note_name: '音名',
    degree: '度数',
  },
  header: {
    portal: 'HPSポータル',
    blog: '無理ない暮らし',
  },
  plain: {
    status_idle: 'Press Capture to start building chords',
    status_capturing: 'Capturing: Slot {slot}/16 \u2014 Click pads, then Capture to save',
    status_editing: 'Editing: Slot {slot} \u2014 Click pads to modify',
    notes_label: 'Notes: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selected',
    slot_cleared: 'Slot {slot} cleared',
    undo: 'Undo',
    no_chords: 'メモリースロットにコードがありません',
  },
  info: {
    note_count: '{n}音',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Select root',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Slot {slot}: Empty',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
});
