// 한국어
I18N.addLang('ko', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: '64패드 그리드에서 스케일, 코드, 보이싱을 탐색하는 도구입니다.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 12개의 키 중 선택',
    scale_scale: '<strong>Scale</strong> \u2014 다이아토닉, 하모닉 마이너, 멜로딕 마이너, 펜타토닉, 비밥 등 31종',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 선택한 스케일의 다이아토닉 코드를 표시. 클릭하면 Chord 모드로 전환',
    chord_mode: 'Chord Mode (3단계)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 피아노 건반에서 근음을 선택',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 코드 유형 선택 (Maj, m, aug, dim, sus 등)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 텐션 추가 (9, b9, #9, 11, #11, 13, b13 등). 복수 선택 가능',
    chord_onchord: '<strong>On Chord</strong> \u2014 "/" 버튼으로 슬래시 코드 (코드/베이스 음)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 음 생략',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2로 음 추가)',
    voicing_inv: '<strong>Inversion</strong> \u2014 전위 (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 탭하여 패드 배치 옵션 전환 (깜빡이는 뱃지 = 대체 배치 있음)',
    display: '표시',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 기타 지판, 피아노 건반, 오선보를 개별적으로 켜기/끄기',
    display_label: '<strong>음이름 / 도수</strong> \u2014 기타와 패드에서 음이름(C, D, E)과 도수(R, 2, 3) 간 전환',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 패드 음역을 옥타브 단위로 이동',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 프리셋 (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 프리셋 (Rhodes, FM 등)',
    sound_fx: '<strong>이펙트</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: '패드 또는 보이싱 박스를 클릭하면 소리가 납니다',
    midi: 'MIDI',
    midi_detect: 'WebMIDI 호환 기기를 자동 감지',
    midi_push: 'Ableton Push 시리얼 MIDI 출력 지원',
    midi_chord: '입력된 음으로부터 코드를 자동 판별',
    color_title: '색상 범례',
    color_root: '<strong>Root</strong> \u2014 근음',
    color_scale: '<strong>Scale / Chord</strong> \u2014 스케일 음 / 코드 톤',
    color_char: '<strong>특성음</strong> \u2014 스케일/코드를 정의하는 음',
    color_3rd: '<strong>3rd</strong> \u2014 가이드 톤 (3도)',
    color_7th: '<strong>7th</strong> \u2014 가이드 톤 (7도)',
    color_tension: '<strong>Tension</strong> \u2014 텐션 음',
    color_avoid: '<strong>Avoid</strong> \u2014 코드 톤 반음 위의 스케일 음 (Chord 모드 시)',
    color_palette: '색상 팔레트: Okabe-Ito (색각 다양성 대응)',
    input_title: 'Guitar / Piano 입력',
    input_desc1: '기타 지판 또는 피아노 건반을 클릭하여 음을 입력',
    input_desc2: '입력한 음으로부터 코드를 자동 판별하여 패드에 반영',
    input_desc3: '<strong>Clear</strong> \u2014 입력 초기화, <strong>Play \u25B6</strong> \u2014 입력한 음 재생',
    plain_title: 'Plain Mode',
    plain_desc1: '패드를 자유롭게 클릭하여 음을 선택 \u2192 실시간 코드 판별',
    plain_desc2: '이론 필터 없음. 탐색 \u2192 발견 \u2192 나중에 이론 학습',
    plain_memory: '<strong>Memory</strong> \u2014 16개 Slot에 코드를 저장 및 불러오기',
    plain_export: '<strong>MIDI Export</strong> \u2014 메모리의 코드를 MIDI 파일로 내보내기',
    perform_title: 'Perform Mode',
    perform_desc1: '16패드 레이아웃으로 Memory Slot 코드를 실시간 연주',
    perform_desc2: '키보드(4\u00D74 그리드) 또는 MIDI 패드로 트리거',
    perform_desc3: 'Slot을 드래그 앤 드롭하여 순서 변경',
    shortcut_title: '키보드 단축키',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 다이아토닉 코드 선택 (7음 스케일)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 보이싱 박스 선택 (대체 배치 순환)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 전위 전환 (Chord 모드)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 근음 반음 이동',
    sc_omit: '<kbd>o</kbd> \u2014 Omit 5 전환',
    sc_rootless: '<kbd>r</kbd> \u2014 Rootless 전환',
    sc_shell: '<kbd>s</kbd> \u2014 Shell 순환 (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Drop 순환 (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 코드 초기화 (Chord 모드)',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Capture 시작 / 다음 슬롯에 저장',
    sp_end: '<kbd>e</kbd> \u2014 Capture 종료',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 메모리 슬롯 불러오기 (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 반음 이동 (전체 음 \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 전위 (최저음 \u21911옥타브 / 최고음 \u21931옥타브)',
    sp_clear: '<kbd>x</kbd> \u2014 전체 초기화',
    sp_transfer: '<b>Chord switch</b> \u2014 감지된 코드를 Chord 모드로 전송',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74 그리드로 Slot 1\u201316 트리거',
    pf_midi: 'MIDI 패드(노트 36\u201354)로도 Slot 트리거 가능',
    shortcut_common: '공통 (모든 모드)',
    sc_perform: '<kbd>p</kbd> \u2014 Perform 뷰 전환',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Memory Slot Undo (최대 30회)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Plain 메모리 슬롯에 저장 (어떤 모드에서든)',
    sc_esc: '<kbd>Esc</kbd> \u2014 보이싱 박스 선택 해제 / 도움말 닫기',
    sc_help: '<kbd>?</kbd> \u2014 도움말 표시/숨기기',
    footer: '64 Pad Explorer V1.9 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: '특성음',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: '닫기',
    slot_hint: '클릭하여 선택 \u2192 Save(c) / Shift+클릭으로 삭제',
  },
  label: {
    note_name: '음이름',
    degree: '도수',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
  },
  plain: {
    status_idle: 'Capture를 눌러 코드 만들기를 시작하세요',
    status_capturing: '캡처 중: Slot {slot}/16 \u2014 패드를 클릭한 후 Capture로 저장',
    status_editing: '편집 중: Slot {slot} \u2014 패드를 클릭하여 수정',
    notes_label: '음: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} 선택됨',
    slot_cleared: 'Slot {slot} 삭제됨',
    undo: '실행 취소',
    no_chords: '메모리 슬롯에 코드가 없습니다',
  },
  info: {
    note_count: '{n}음',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: '근음 선택',
  },
  midi: {
    all_devices: '모든 기기',
  },
  memory: {
    slot_empty: 'Slot {slot}: 비어 있음',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
});
