// Italiano
I18N.addLang('it', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: 'Uno strumento per esplorare scale, accordi e voicings su una griglia di 64 pad.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Scegliere tra 12 tonalità',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonica, minore armonica, minore melodica, pentatonica, Bebop e altro \u2014 31 tipi',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Mostra gli accordi diatonici della scala selezionata. Clicca per entrare in modalità Chord',
    chord_mode: 'Chord Mode (3 passaggi)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selezionare la fondamentale sulla tastiera del pianoforte',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Scegliere il tipo di accordo (Maj, m, aug, dim, sus, ecc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Aggiungere tensioni (9, b9, #9, 11, #11, 13, b13, ecc.). Selezione multipla consentita',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usare il pulsante "/" per accordi con basso diverso (accordo / nota di basso)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettere note',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 per aggiungere note)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Rivolti (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tocca per scorrere le disposizioni sui pad (badge pulsante = disposizioni alternative disponibili)',
    display: 'Visualizzazione',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Attivare/disattivare tastiera di chitarra, pianoforte e pentagramma indipendentemente',
    display_label: '<strong>Nome / Grado</strong> \u2014 Alternare tra nomi delle note (C, D, E) e gradi (R, 2, 3) su chitarra e pad',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Spostare l\'estensione dei pad di un\'ottava',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 preset (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 preset (Rhodes, FM, ecc.)',
    sound_fx: '<strong>Effetti</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Clicca su un pad o una voicing box per riprodurre il suono',
    midi: 'MIDI',
    midi_detect: 'Rilevamento automatico dei dispositivi compatibili WebMIDI',
    midi_push: 'Supporto per l\'uscita MIDI seriale di Ableton Push',
    midi_chord: 'Identificazione automatica degli accordi dalle note suonate',
    color_title: 'Legenda colori',
    color_root: '<strong>Root</strong> \u2014 Nota fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Note della scala / Note dell\'accordo',
    color_char: '<strong>Caratteristica</strong> \u2014 Note che definiscono la scala/l\'accordo',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (terza)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (settima)',
    color_tension: '<strong>Tension</strong> \u2014 Note di tensione',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota della scala un semitono sopra una nota dell\'accordo (in modalità Chord)',
    color_palette: 'Palette colori: Okabe-Ito (accessibile per daltonici)',
    input_title: 'Ingresso Guitar / Piano',
    input_desc1: 'Clicca sulla tastiera della chitarra o del pianoforte per inserire le note',
    input_desc2: 'Gli accordi vengono identificati automaticamente dall\'input e riflessi sul pad',
    input_desc3: '<strong>Clear</strong> \u2014 Cancella input, <strong>Play \u25B6</strong> \u2014 Riproduci le note inserite',
    plain_title: 'Plain Mode',
    plain_desc1: 'Clicca liberamente sui pad per selezionare le note \u2192 Identificazione accordi in tempo reale',
    plain_desc2: 'Senza filtro teorico. Esplora \u2192 scopri \u2192 impara la teoria dopo',
    plain_memory: '<strong>Memory</strong> \u2014 Salva e richiama accordi in 16 slot',
    plain_export: '<strong>MIDI Export</strong> \u2014 Esporta gli accordi in memoria come file MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> pulsante o tasto <kbd>p</kbd> per cambiare',
    perform_desc1: 'Suona gli accordi dei Memory Slot in tempo reale con un layout a 16 pad',
    perform_desc2: 'Attiva tramite tastiera (griglia 4\u00D74) o pad MIDI',
    perform_desc3: 'Trascina e rilascia gli Slot per riordinare',
    shortcut_title: 'Scorciatoie da tastiera',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Selezionare accordo diatonico (scale a 7 note)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Selezionare voicing box (scorrere le alternative)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Scorrere i rivolti (modalità Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Trasposizione cromatica della fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Attivare/disattivare Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Attivare/disattivare Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclare Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclare Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Cancella accordo (modalità Chord)',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Avviare Capture / salvare nello slot successivo',
    sp_end: '<kbd>e</kbd> \u2014 Terminare Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Richiamare slot di memoria (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Trasposizione cromatica (tutte le note \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Rivolto (più bassa \u21911ott / più alta \u21931ott)',
    sp_clear: '<kbd>x</kbd> \u2014 Cancella tutto',
    sp_transfer: '<b>Chord switch</b> \u2014 Trasferire l\'accordo rilevato in modalità Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Griglia 4\u00D74 attiva Slot 1\u201316',
    pf_midi: 'I pad MIDI (note 36\u201354) attivano anche gli Slot',
    shortcut_common: 'Comune (tutte le modalit\u00E0)',
    sc_perform: '<kbd>p</kbd> \u2014 Attivare/disattivare la vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annulla Memory Slot (fino a 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Salvare nello slot di memoria Plain (da qualsiasi modalità)',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselezionare voicing box / chiudere la guida',
    sc_help: '<kbd>?</kbd> \u2014 Mostrare/nascondere la guida',
    footer: '64 Pad Explorer V1.9 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caratteristica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Chiudi',
    slot_hint: 'Clicca per selezionare \u2192 Save(c) / Shift+clic per cancellare',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grado',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
  },
  plain: {
    status_idle: 'Premi Capture per iniziare a costruire accordi',
    status_capturing: 'Cattura: Slot {slot}/16 \u2014 Clicca sui pad, poi Capture per salvare',
    status_editing: 'Modifica: Slot {slot} \u2014 Clicca sui pad per modificare',
    notes_label: 'Note: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selezionato',
    slot_cleared: 'Slot {slot} cancellato',
    undo: 'Annulla',
    no_chords: 'Nessun accordo negli slot di memoria',
  },
  info: {
    note_count: '{n} note',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Seleziona la fondamentale',
  },
  midi: {
    all_devices: 'Tutti i dispositivi',
  },
  memory: {
    slot_empty: 'Slot {slot}: Vuoto',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  parent: {
    toggle: 'Parent Scale',
    header: 'Parent Scales ({n})',
    expand: 'Mostra tutto',
  },
});
