// Português
I18N.addLang('pt', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: 'Uma ferramenta para explorar escalas, acordes e voicings numa grelha de 64 pads.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Escolher entre 12 tonalidades',
    scale_scale: '<strong>Scale</strong> \u2014 Diatónica, menor harmónica, menor melódica, pentatónica, Bebop e mais \u2014 31 tipos',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Mostra os acordes diatónicos da escala selecionada. Clique para entrar no modo Chord',
    chord_mode: 'Chord Mode (3 passos)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selecionar a fundamental no teclado de piano',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Escolher o tipo de acorde (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Adicionar tensões (9, b9, #9, 11, #11, 13, b13, etc.). Seleção múltipla permitida',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usar o botão "/" para acordes invertidos (acorde sobre nota de baixo)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omitir notas',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 para adicionar notas)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversões (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Toque para percorrer as opções de disposição no pad (badge pulsante = disposições alternativas disponíveis)',
    display: 'Visualização',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Ativar/desativar braço da guitarra, teclado e pauta musical independentemente',
    display_label: '<strong>Nome / Grau</strong> \u2014 Alternar entre nomes de notas (C, D, E) e graus (R, 2, 3) na guitarra e nos pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Deslocar a extensão dos pads por oitava',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 presets (Rhodes, FM, etc.)',
    sound_fx: '<strong>Efeitos</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Clique num pad ou voicing box para reproduzir o som',
    midi: 'MIDI',
    midi_detect: 'Deteção automática de dispositivos compatíveis com WebMIDI',
    midi_push: 'Suporte para saída MIDI série do Ableton Push',
    midi_chord: 'Identificação automática de acordes a partir das notas tocadas',
    color_title: 'Legenda de cores',
    color_root: '<strong>Root</strong> \u2014 Nota fundamental',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notas da escala / Notas do acorde',
    color_char: '<strong>Característica</strong> \u2014 Notas que definem a escala/acorde',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (terça)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (sétima)',
    color_tension: '<strong>Tension</strong> \u2014 Notas de tensão',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota da escala um semitom acima de uma nota do acorde (no modo Chord)',
    color_palette: 'Paleta de cores: Okabe-Ito (acessível para daltónicos)',
    input_title: 'Entrada Guitar / Piano',
    input_desc1: 'Clique no braço da guitarra ou no teclado do piano para inserir notas',
    input_desc2: 'Os acordes são identificados automaticamente a partir da entrada e refletidos no pad',
    input_desc3: '<strong>Clear</strong> \u2014 Limpar entrada, <strong>Play \u25B6</strong> \u2014 Reproduzir notas inseridas',
    plain_title: 'Plain Mode',
    plain_desc1: 'Clique livremente nos pads para selecionar notas \u2192 Identificação de acordes em tempo real',
    plain_desc2: 'Sem filtro teórico. Explorar \u2192 descobrir \u2192 aprender teoria depois',
    plain_memory: '<strong>Memory</strong> \u2014 Guardar e recuperar acordes em 16 slots',
    plain_export: '<strong>MIDI Export</strong> \u2014 Exportar acordes da mem\u00F3ria como ficheiro MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> bot\u00E3o ou tecla <kbd>p</kbd> para alternar',
    perform_desc1: 'Toque os acordes dos Memory Slots em tempo real com um layout de 16 pads',
    perform_desc2: 'Acione via teclado (grelha 4\u00D74) ou pads MIDI',
    perform_desc3: 'Arraste e solte Slots para reordenar',
    shortcut_title: 'Atalhos de teclado',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Selecionar acorde diatónico (escalas de 7 notas)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Selecionar voicing box (percorrer alternativas)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Percorrer inversões (modo Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposição cromática da fundamental',
    sc_omit: '<kbd>o</kbd> \u2014 Ativar/desativar Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Ativar/desativar Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclar Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclar Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Limpar acorde (modo Chord)',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Iniciar Capture / guardar no slot seguinte',
    sp_end: '<kbd>e</kbd> \u2014 Terminar Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recuperar slot de memória (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposição cromática (todas as notas \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversão (mais grave \u21911oit / mais aguda \u21931oit)',
    sp_clear: '<kbd>x</kbd> \u2014 Limpar tudo',
    sp_transfer: '<b>Chord switch</b> \u2014 Transferir acorde detetado para o modo Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Grelha 4\u00D74 aciona Slots 1\u201316',
    pf_midi: 'Pads MIDI (notas 36\u201354) tamb\u00E9m acionam Slots',
    shortcut_common: 'Comum (todos os modos)',
    sc_perform: '<kbd>p</kbd> \u2014 Alternar vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Desfazer Memory Slots (at\u00E9 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Guardar no slot de memória Plain (a partir de qualquer modo)',
    sc_esc: '<kbd>Esc</kbd> \u2014 Desselecionar voicing box / fechar ajuda',
    sc_help: '<kbd>?</kbd> \u2014 Mostrar/ocultar ajuda',
    footer: '64 Pad Explorer V1.9 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Característica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Fechar',
    slot_hint: 'Clique para selecionar \u2192 Save(c) / Shift+clique para limpar',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grau',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
    guide: 'Guia',
  },
  plain: {
    status_idle: 'Prima Capture para começar a construir acordes',
    status_capturing: 'A capturar: Slot {slot}/16 \u2014 Clique nos pads, depois Capture para guardar',
    status_editing: 'A editar: Slot {slot} \u2014 Clique nos pads para modificar',
    notes_label: 'Notas: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selecionado',
    slot_cleared: 'Slot {slot} limpo',
    undo: 'Desfazer',
    no_chords: 'Sem acordes nos slots de memória',
  },
  info: {
    note_count: '{n} notas',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Selecionar fundamental',
  },
  midi: {
    all_devices: 'Todos os dispositivos',
  },
  memory: {
    slot_empty: 'Slot {slot}: Vazio',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostrar tudo',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guia',
    tagline: 'Uma ferramenta de navegador para explorar escalas, acordes e voicings numa grelha de 64 pads.<br>Sem necessidade de fonte sonora \u2014 apenas Chrome.',
    cta: 'Abrir App',
    features: 'Funcionalidades',
    feat_sound: '<strong>Sem necessidade de fonte sonora</strong> \u2014 O som toca diretamente no Chrome. 4 presets de \u00F3rg\u00E3o + 7 presets de piano el\u00E9trico integrados. Efeitos (reverb, phaser, flanger, tremolo, filtro) inclu\u00EDdos',
    feat_input: '<strong>Sem habilidade de pad necess\u00E1ria</strong> \u2014 Construa acordes em 3 passos. Tens\u00F5es exibidas. Clique nos pads para inserir diretamente',
    feat_detect: '<strong>Dete\u00E7\u00E3o de acordes</strong> \u2014 Dete\u00E7\u00E3o em tempo real do nome do acorde a partir das notas clicadas. Suporta omit, acordes invertidos e m\u00FAltiplos candidatos',
    feat_instruments: '<strong>Exibi\u00E7\u00E3o Guitar / Bass / Keyboard</strong> \u2014 Mostra notas do acorde no bra\u00E7o da guitarra, baixo e piano. A entrada pelo bra\u00E7o da guitarra reflete-se automaticamente nos pads',
    feat_scales: '<strong>Exibi\u00E7\u00E3o de escalas</strong> \u2014 31 escalas \u00D7 12 tonalidades. Diat\u00F3nica, menor harm\u00F3nica, menor mel\u00F3dica, pentat\u00F3nica, Bebop e mais',
    feat_diatonic: '<strong>Exibi\u00E7\u00E3o de acordes diat\u00F3nicos</strong> \u2014 Os acordes diat\u00F3nicos s\u00E3o mostrados numa barra para a escala selecionada. Clique ou use atalhos para tocar instantaneamente',
    feat_voicing: '<strong>Opera\u00E7\u00F5es de voicing</strong> \u2014 Invers\u00F5es, Drop 2/3, Shell Voicing, Omit, Rootless. Setas para invers\u00F5es, bot\u00F5es para m\u00FAltiplas digita\u00E7\u00F5es',
    feat_memory: '<strong>Mem\u00F3ria de acordes</strong> \u2014 Guarde os seus acordes favoritos em 16 slots. Exporte como ficheiros MIDI para o seu DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Toque os acordes em mem\u00F3ria em tempo real com 16 pads ou o seu teclado de PC',
    feat_parent: '<strong>Pesquisa inversa Available Scale</strong> \u2014 Encontre escalas que cont\u00EAm o seu acorde. Veja as Available Tensions de relance. Altern\u00E2ncia Practical/Diatonic',
    feat_pivot: '<strong>Pensamento de acorde pivot</strong> \u2014 Insira um acorde manualmente e a barra diat\u00F3nica desaparece, mostrando todas as tonalidades \u00E0s quais o seu acorde poderia pertencer. Ideal para an\u00E1lise de modula\u00E7\u00E3o',
    feat_dimming: '<strong>Exibi\u00E7\u00E3o pr\u00E1tica de Tensions</strong> \u2014 Para acordes de 7\u00AA n\u00E3o dominante, as tens\u00F5es pouco comuns (b9, #9, b13, etc.) s\u00E3o atenuadas. Ainda selecion\u00E1veis',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 l\u00EDnguas (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Capturas de ecr\u00E3',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Selecione uma tonalidade e uma escala para ver as notas da escala coloridas na grelha de 64 pads. Escolha acordes na barra diat\u00F3nica.',
    ss_scale_alt: 'Scale Mode \u2014 Exibi\u00E7\u00E3o da escala de C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (laranja), notas da escala (azul), notas caracter\u00EDsticas (amarelo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construa acordes em 3 passos: Root \u2192 Quality \u2192 Tension. Ajuste voicings com invers\u00F5es, Drop, Shell e Omit. Use o painel Parent Scale para pesquisa inversa.',
    ss_chord_alt: 'Chord Mode \u2014 Exibi\u00E7\u00E3o do acorde Dm7 com grelha de tens\u00F5es',
    ss_chord_caption: 'Dm7 \u2014 Notas do acorde, 3rd (rosa), 7th (verde). Verifique as disposi\u00E7\u00F5es nas voicing boxes',
    ss_plain: '<span class="mode-badge plain">Plain</span> Plain Mode',
    ss_plain_desc: 'Clique livremente nos pads para dete\u00E7\u00E3o de acordes em tempo real. Sem filtro te\u00F3rico \u2014 explore, descubra e depois aprenda a teoria.',
    ss_plain_alt: 'Plain Mode \u2014 Dete\u00E7\u00E3o em tempo real de C7',
    ss_plain_caption: 'C7 \u2014 Clique nos pads para detetar automaticamente nomes de acordes. M\u00FAltiplos candidatos mostrados',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Coloque os acordes guardados em 16 pads para performance em tempo real via teclado ou pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 slots com acordes',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 guardados nos slots. Toque usando a grelha de teclado 4\u00D74',
    ss_parent: 'Available Scale + Acorde Pivot',
    ss_parent_desc: 'Pesquisa inversa de escalas que cont\u00EAm o seu acorde. Alterne entre ordena\u00E7\u00E3o Practical (por usabilidade) e Diatonic (por teoria). A entrada manual de acordes oculta a barra diat\u00F3nica para an\u00E1lise de acordes pivot.',
    ss_parent_alt: 'Painel Parent Scale e exibi\u00E7\u00E3o do bra\u00E7o da guitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions exibidas',
    usecases: 'Casos de uso',
    uc1_q: '\u00AB Quero encontrar como voicer este acorde nos pads \u00BB',
    uc1_a: '\u2192 Selecione Root, Quality e Tension no modo <span class="mode-badge chord">Chord</span> \u2192 Verifique as disposi\u00E7\u00F5es nas voicing boxes',
    uc2_q: '\u00AB Quero ver uma escala da minha aula nos pads \u00BB',
    uc2_a: '\u2192 Selecione tonalidade e escala no modo <span class="mode-badge scale">Scale</span>. 31 escalas dispon\u00EDveis',
    uc3_q: '\u00AB Quero criar uma progress\u00E3o de acordes para o meu DAW \u00BB',
    uc3_a: '\u2192 Guarde os acordes nos slots de mem\u00F3ria \u2192 MIDI Export para importar no seu DAW',
    uc4_q: '\u00AB A que tonalidade pertence este acorde? \u00BB',
    uc4_a: '\u2192 Pesquisa inversa no painel Available Scale. Alterne entre ordena\u00E7\u00E3o Practical/Diatonic',
    uc7_q: '\u00AB Quero encontrar acordes pivot para modula\u00E7\u00E3o \u00BB',
    uc7_a: '\u2192 Insira um acorde manualmente no modo <span class="mode-badge chord">Chord</span>. A barra diat\u00F3nica desaparece e Available Scale mostra todas as tonalidades poss\u00EDveis',
    uc5_q: '\u00AB Quero praticar improvisa\u00E7\u00E3o nos pads \u00BB',
    uc5_a: '\u2192 Disponha os acordes em mem\u00F3ria em 16 pads no Perform mode. Toque via teclado ou pads MIDI',
    uc6_q: '\u00AB Quero transferir um acorde de guitarra para os pads \u00BB',
    uc6_a: '\u2192 Clique no bra\u00E7o da guitarra para inserir \u2192 Exibi\u00E7\u00E3o autom\u00E1tica nos pads \u2192 Nome do acorde detetado',
    quickstart: 'In\u00EDcio r\u00E1pido',
    qs_modes: '3 modos',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Mostrar escalas e acordes diat\u00F3nicos<br><span class="mode-badge chord">Chord</span> Construir acordes em 3 passos. Opera\u00E7\u00F5es de voicing dispon\u00EDveis<br><span class="mode-badge plain">Plain</span> Clicar livremente nos pads \u2192 Dete\u00E7\u00E3o autom\u00E1tica dos nomes de acordes',
    qs_first: 'Para come\u00E7ar',
    qs_step1: 'Escolha uma tonalidade (ex: C)',
    qs_step2: 'Escolha uma escala (ex: Major) \u2192 As notas da escala aparecem nos pads',
    qs_step3: 'Clique num acorde na barra diat\u00F3nica (ex: Dm7) \u2192 Notas do acorde exibidas',
    qs_step4: 'Clique nos pads para tocar sons. Mude as disposi\u00E7\u00F5es nas voicing boxes',
    qs_step5: 'Guarde os seus acordes favoritos com <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Atalhos de teclado',
    qs_shortcuts_desc: 'Prima <kbd>?</kbd> para a lista completa de atalhos.<br><kbd>1</kbd>\u2013<kbd>7</kbd> para acordes diat\u00F3nicos, <kbd>\u2191</kbd><kbd>\u2193</kbd> para invers\u00F5es, <kbd>\u2190</kbd><kbd>\u2192</kbd> para movimento crom\u00E1tico.<br>No Perform mode, use <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> como grelha 4\u00D74.',
    footer_open: 'Abrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer V2.5 \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Saiba mais no blog \u2192',
  },
});
