// English (fallback)
I18N.addLang('en', {
  help: {
    title: '64 Pad Explorer',
    description: 'A tool for exploring scales, chords, and voicings on a 64-pad grid.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choose from 12 keys',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Shows diatonic chords for the selected scale. Click to enter Chord mode',
    chord_mode: 'Chord Mode (3 Steps)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Select root on the piano keyboard',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choose chord type (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Add tensions (9, b9, #9, 11, #11, 13, b13, etc.). Multiple selections OK',
    chord_text: '<strong>Text Input</strong> \u2014 Press "/" to focus. Type Cm7, G7(b9,#11), Am7/G etc. directly. Autocomplete suggestions appear',
    chord_onchord: '<strong>On Chord</strong> \u2014 Use the "/" button for slash chords (chord over bass note)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omit notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 to add notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversions (Root, 1st, 2nd, 3rd)',
    inv_1: '1st Inversion',
    inv_2: '2nd Inversion',
    inv_3: '3rd Inversion',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tap to cycle through pad layout options (pulsing badge = alternative layouts available)',
    display: 'Display',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Toggle guitar fretboard, bass, piano keyboard, and staff notation independently',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Displays the circle of fifths. Linked to key selection, showing diatonic chords and functions (T/SD/D). Minor mode switching supported',
    display_label: '<strong>Note Name / Degree</strong> \u2014 Switch between note names (C, D, E) and degrees (R, 2, 3) on guitar and pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Shift pad range by octave',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Toggle sound on/off with the speaker icon',
    sound_select: '<strong>ORGAN / E.PIANO</strong> \u2014 Select a sound engine. Press \u25BC to open the detail panel for presets and effects',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 presets (Rhodes 1-3, FM EP 1-2, Clavinet 1-2, jRhodes3c Sampler)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Envelope filter (Auto-Wah). 3 types: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Analog saturation. Adds warm overdrive to the sound',
    sound_fx: '<strong>Effects</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Click a pad or voicing box to play sound',
    midi: 'MIDI',
    midi_detect: 'Auto-detects WebMIDI-compatible devices',
    midi_push: 'Supports Ableton Push serial MIDI output',
    midi_chord: 'Auto-identifies chords from input notes',
    color_title: 'Color Legend',
    color_root: '<strong>Root</strong> \u2014 Root note',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Scale notes / Chord tones',
    color_char: '<strong>Characteristic</strong> \u2014 Notes that define the scale/chord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (3rd)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (7th)',
    color_tension: '<strong>Tension</strong> \u2014 Tension notes',
    color_avoid: '<strong>Avoid</strong> \u2014 Scale note a half step above a chord tone (in Chord mode)',
    color_palette: 'Color palette: Okabe-Ito (color vision accessible)',
    input_title: 'Guitar / Piano Input',
    input_desc1: 'Click the guitar fretboard or piano keyboard to input notes',
    input_desc2: 'Chords are auto-identified from input and reflected on the pad',
    input_desc3: '<strong>Clear</strong> \u2014 Clear input, <strong>Play \u25B6</strong> \u2014 Play input notes',
    input_title: 'Input Mode',
    input_desc1: 'Click pads freely to select notes \u2192 Real-time chord identification',
    input_desc2: 'No theory filter. Explore \u2192 discover \u2192 learn theory afterward',
    input_desc3: 'When a chord is detected, degree labels (R, 3, 5, b7, etc.) appear on pads. Guitar, bass, piano, and staff update automatically',
    input_memory: '<strong>Memory</strong> \u2014 Save and recall chords in 16 slots',
    input_banks: '<strong>Banks</strong> \u2014 16 slots \u00D7 up to 16 banks. Switch with <kbd>[</kbd> <kbd>]</kbd>. Duplicate and rename supported',
    input_export: '<strong>MIDI Export</strong> \u2014 Export memory chords as a MIDI file',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> button or <kbd>p</kbd> key to switch',
    perform_desc1: 'Play memory slot chords in real-time with a 16-pad layout',
    perform_desc2: 'Trigger via keyboard (4\u00D74 grid) or MIDI pads',
    perform_desc3: 'Drag & drop slots to reorder',
    shortcut_title: 'Keyboard Shortcuts',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Select diatonic chord (7-note scales)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Select voicing box (cycles alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Cycle inversions (Chord mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic root transpose',
    sc_omit: '<kbd>o</kbd> \u2014 Toggle Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Toggle Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycle Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycle Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: '<kbd>v</kbd> \u2014 Reflect to pad / cycle layout (guitar-like \u2194 compact)',
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Cycle guitar position (prev / next)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Cycle bass position (prev / next)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON / next voicing, <kbd>Shift</kbd>+<kbd>t</kbd> \u2014 previous',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON / next voicing, <kbd>Shift</kbd>+<kbd>k</kbd> \u2014 previous',
    sc_clear: '<kbd>x</kbd> \u2014 Clear chord (Chord mode)',
    sc_pad_explore: '<b>Pad (Chord mode)</b> \u2014 Click pad to toggle note \u2014 builder updates automatically',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Start Capture / save to next slot',
    sp_end: '<kbd>e</kbd> \u2014 End Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recall memory slot (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic transpose (all notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversion (lowest \u21911oct / highest \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Clear all',
    sp_transfer: '<b>Chord switch</b> \u2014 Transfer detected chord to Chord mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74 grid triggers slots 1\u201316',
    pf_midi: 'MIDI pads (notes 36\u201354) also trigger slots',
    shortcut_common: 'Common (All Modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Toggle Perform view',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Undo memory slots (up to 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Save to Input memory slot (from any mode)',
    sc_space: '<kbd>Space</kbd> \u2014 Play current chord',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselect voicing box / close Help',
    sc_help: '<kbd>?</kbd> \u2014 Toggle Help',
    tips_toggle: 'Show startup tips',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Characteristic',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Close',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> save(all 16)</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Save Settings',
    sound_hint: 'Select a sound preset to enable audio',
    tap_to_start: 'Tap to enable sound',
    tap_pads: 'Tap any pad to play!',
    input_keys_disabled: 'Key selection is not used in Input mode',
    load_vst: 'Load VST/AU Plugin...',
    affiliate_label: '',
    staff: 'Staff',
    circle: 'Circle',
    help: 'Help',
    oct_down: 'Shift octave down',
    oct_up: 'Shift octave up',
    toggle_guitar: 'Show/hide guitar fretboard (Shift+G)',
    toggle_bass: 'Show/hide bass fretboard (Shift+B)',
    toggle_piano: 'Show/hide piano keyboard (Shift+P)',
    mode_scale: 'Scale mode \u2014 view scale notes on the pad (Tab to cycle)',
    mode_chord: 'Chord mode \u2014 build chords with voicings (Tab to cycle)',
    mode_input: 'Input mode \u2014 tap pads freely to detect chords (Tab to cycle)',
    play_chord: 'Play current chord (Space)',
    toggle_staff: 'Show/hide staff notation (Shift+S)',
    toggle_circle: 'Show/hide circle of fifths (Shift+C)',
    toggle_sound: 'Show/hide sound controls',
    sound_mute: 'Sound ON/OFF',
    sound_expand: 'Show/hide detailed sound settings',
  },
  label: {
    note_name: 'Note',
    degree: 'Degree',
    chord_input: 'Enter a chord',
    chord_hint: 'Tensions in ( ): C7(b9,#11) | dim, h=m7♭5 supported',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'My Blog',
    guide: 'Guide',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Press Capture to start building chords',
    status_capturing: 'Capturing: Slot {slot}/16 \u2014 Click pads, then Capture to save',
    status_editing: 'Editing: Slot {slot} \u2014 Click pads to modify',
    notes_label: 'Notes: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} selected',
    slot_cleared: 'Slot {slot} cleared',
    undo: 'Undo',
    settings_saved: 'Settings saved',
    no_chords: 'No chords in memory slots',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Select root',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Slot {slot}: Empty',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Click to rename bank',
    rename: 'Rename',
    duplicate: 'Duplicate',
    delete: 'Delete',
    rename_prompt: 'Enter bank name:',
    confirm_delete: 'Delete "{name}"?',
    limit_reached: 'Maximum 16 banks',
    cannot_delete_last: 'Cannot delete the last bank',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Show all',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guide',
    tagline: 'A browser tool for exploring scales, chords, and voicings on a 64-pad grid.<br>No sound source needed \u2014 just Chrome.',
    cta: 'Open App',
    features: 'Features',
    feat_sound: '<strong>No sound source needed</strong> \u2014 Sound plays right in Chrome. 4 organ + 8 electric piano presets built in. Effects (drive, reverb, phaser, flanger, tremolo, lo cut, hi cut, auto filter) included',
    feat_input: '<strong>No pad skills required</strong> \u2014 Build chords in 3 steps. Tensions displayed. Click pads to input directly',
    feat_text_input: '<strong>Text Chord Input</strong> \u2014 Press "/" to type Cm7, G7(b9,#11), Am7/G etc. directly. Autocomplete suggestions. Abbreviations like dim, h(=m7\u266D5) supported',
    feat_detect: '<strong>Chord detection</strong> \u2014 Real-time chord name detection from clicked notes. Supports omit, slash chords, and multiple candidates',
    feat_instruments: '<strong>Guitar / Bass / Keyboard display</strong> \u2014 Shows chord tones on guitar fretboard, bass, and piano. Guitar fingering input auto-reflects on pads. In Chord mode, positions are grouped by root string',
    feat_scales: '<strong>Scale display</strong> \u2014 31 scales \u00D7 12 keys. Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more',
    feat_diatonic: '<strong>Diatonic chord display</strong> \u2014 Diatonic chords shown on a bar for the selected scale. Click or use shortcuts to play instantly. Triad/tetrad toggle supported',
    feat_voicing: '<strong>Voicing operations</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Arrow keys for inversions, buttons for multiple fingerings',
    feat_memory: '<strong>Chord memory</strong> \u2014 Save favorite chords to 16 slots. Export as MIDI files for your DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Play memory chords in real-time using 16 pads or your PC keyboard',
    feat_parent: '<strong>Available Scale reverse lookup</strong> \u2014 Find scales that contain your chord. See available tensions at a glance. Practical/Diatonic sort toggle',
    feat_pivot: '<strong>Pivot chord thinking</strong> \u2014 Manually input a chord and the diatonic bar disappears, showing all keys your chord could belong to. Perfect for modulation analysis',
    feat_dimming: '<strong>Tension practical display</strong> \u2014 For non-dominant 7th chords, uncommon tensions (b9, #9, b13, etc.) are dimmed. Still selectable',
    feat_circle: '<strong>Circle of Fifths</strong> \u2014 Displays the circle of fifths. Linked to key selection, showing diatonic chords and functions (T/SD/D). Minor mode switching supported',
    feat_banks: '<strong>Memory banks</strong> \u2014 16 slots \u00D7 up to 16 banks. Switch, duplicate, and rename banks. <kbd>[</kbd> <kbd>]</kbd> keys to switch',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Envelope filter (Auto-Wah). 3 types: Cry Baby / Mu-Tron / Moog. Adjust frequency, resonance, sensitivity, and decay',
    feat_drive: '<strong>Drive</strong> \u2014 Analog saturation. Adds warm overdrive to the sound',
    feat_clav: '<strong>Clavinet presets</strong> \u2014 2 clavinet presets added to E.PIANO (Clav Muted, Clav Bright). Perfect for funk',
    feat_midi_sens: '<strong>MIDI velocity sensitivity</strong> \u2014 Push 3-style 4-parameter (Threshold, Drive, Compand, Range) velocity curve adjustment. Real-time curve visualization. Works with all MIDI controllers',
    feat_push_oct: '<strong>Push 3 octave sync</strong> \u2014 Push 3 octave \u25B2\u25BC buttons auto-sync with the app\u2019s octave shift',
    feat_i18n: '<strong>Multilingual</strong> \u2014 9 languages (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshots',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Select a key and scale to see scale notes color-coded on the 64-pad grid. Choose chords from the diatonic bar.',
    ss_scale_alt: 'Scale Mode \u2014 C Major (Ionian) scale display',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (orange), scale notes (blue), characteristic notes (yellow)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Build chords in 3 steps: Root \u2192 Quality \u2192 Tension. Adjust voicings with inversions, Drop, Shell, and Omit. Use the Parent Scale panel to reverse-lookup scales.',
    ss_chord_alt: 'Chord Mode \u2014 Dm7 chord display with tension grid',
    ss_chord_caption: 'Dm7 \u2014 Chord tones, 3rd (pink), 7th (green). Check layout options in voicing boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Click pads freely for real-time chord detection. Understand chords even without knowing theory.',
    ss_input_alt: 'Input Mode \u2014 C7 real-time chord detection',
    ss_input_caption: 'C7 \u2014 Click pads to auto-detect chord names. Multiple candidates shown',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Place saved chords on 16 pads for real-time performance using keyboard or MIDI pads.',
    ss_perform_alt: 'Perform Mode \u2014 16 slots with chords',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 saved to slots. Play using 4\u00D74 keyboard grid',
    ss_parent: 'Available Scale + Pivot Chord',
    ss_parent_desc: 'Reverse-lookup scales that contain your chord. Toggle between Practical (by usability) and Diatonic (by theory) sorting. Manual chord input hides the diatonic bar for pivot chord analysis.',
    ss_parent_alt: 'Parent Scale panel and guitar fretboard display',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions displayed',
    ss_parent_note: '\u203B Pentatonic/Blues scales are modal (horizontal approach) and belong to a different system from chord-scale theory (vertical mapping), so they are not included in Available Scale. In practice, pentatonic is often the first choice.',
    ss_velocity: 'MIDI Velocity Sensitivity',
    ss_velocity_desc: 'Adjust MIDI controller velocity sensitivity with Push 3-style 4 parameters. Configure in the VELOCITY SENSITIVITY section within the Sound panel. Real-time curve visualization.',
    ss_push_oct: 'Push 3 Octave Button Sync',
    ss_push_oct_desc: 'Push 3 octave \u25B2\u25BC buttons (CC#55/CC#54) automatically sync with the app\u2019s octave shift. Press the octave buttons on Push 3 and the display octave updates automatically.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'HPS-Exclusive Voicing Features',
    ss_hps_voicing_intro: 'HPS members get 3 voicing tools. Each provides voicings from a different instrument and classification, and all can be reflected to the 64-pad layout with "To Pad".',
    ss_tasty: 'TASTY Voicing \u2014 Classified by Top Note',
    ss_tasty_desc: '129 sophisticated voicings displayed as degree arrays. Select a chord, press <kbd>T</kbd> to activate, and press again to cycle through voicings. Auto-selects the optimal pad position.',
    ss_tasty_target: 'Target: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'The info area shows degree stacking order (e.g., <code>m9 (b3-b7-9-5-1)</code>). This is the voicing structure \u2014 which notes are stacked from bottom to top.',
    ss_tasty_labels_title: 'Label meanings',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Root (1st degree) omitted. Common in jazz/R&B/neo-soul where the bassist covers the root.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5th omitted. The 5th has little tonal character, so it\'s replaced with a tension for richer sound.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3rd omitted. Approaches a sus or quartal sound.',
    ss_tasty_ops_title: 'Controls',
    ss_stock: 'STOCK Voicing \u2014 Piano Voicing Collection',
    ss_stock_desc: '154 piano voicings from educational materials, displayed in degree notation. Covers Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. View actual positions on the keyboard display, then use "To Pad" to map to pad layout.',
    ss_stock_ops_title: 'Controls',
    ss_guitar_pos: 'Guitar Position \u2014 Guitar Voicings',
    ss_guitar_pos_desc: 'Auto-calculates chord positions on the guitar fretboard. Click fretboard for manual input. Use <kbd>V</kbd> "To Pad" to convert guitar voicings to pad layout. Choose between guitar-like (1 note per row) and compact layouts.',
    usecases: 'Use Cases',
    uc1_q: '"I want to find how to voice this chord on pads"',
    uc1_a: '\u2192 Select Root, Quality, and Tension in <span class="mode-badge chord">Chord</span> mode \u2192 Check layouts in voicing boxes',
    uc2_q: '"I want to see a scale from my lesson on the pads"',
    uc2_a: '\u2192 Select key and scale in <span class="mode-badge scale">Scale</span> mode. 31 scales available',
    uc3_q: '"I want to create a chord progression for my DAW"',
    uc3_a: '\u2192 Save chords to memory slots \u2192 MIDI Export to import into your DAW',
    uc4_q: '"Which key does this chord belong to?"',
    uc4_a: '\u2192 Reverse-lookup in the Available Scale panel. Switch between Practical/Diatonic sort for usability ordering',
    uc7_q: '"I want to find pivot chords for modulation"',
    uc7_a: '\u2192 Manually input a chord in <span class="mode-badge chord">Chord</span> mode. The diatonic bar disappears and Available Scale shows all keys your chord could belong to',
    uc5_q: '"I want to check chord progressions by playing them"',
    uc5_a: '\u2192 Save chords to memory slots, then play them with a MIDI controller or PC keyboard',
    uc6_q: '"I want to check guitar chords on the pads"',
    uc6_a: '\u2192 Click guitar fretboard to input \u2192 Auto-displayed on pads \u2192 Chord name detected',
    uc8_q: '"I want to learn professional voicings"',
    uc8_a: '\u2192 Build a chord in <span class="mode-badge chord">Chord</span> mode, then press <kbd>T</kbd> for TASTY (top-note classification) or <kbd>K</kbd> for STOCK (piano voicings). View with degree notation, use "To Pad" to map to pad layout, save to memory and export to DAW',
    quickstart: 'Quick Start',
    qs_modes: '3 Modes',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Display scales and diatonic chords<br><span class="mode-badge chord">Chord</span> Build chords in 3 steps. Voicing operations available<br><span class="mode-badge input">Input</span> Click pads freely \u2192 Auto-detect chord names',
    qs_first: 'Getting Started',
    qs_step1: 'Choose a key (e.g., C)',
    qs_step2: 'Choose a scale (e.g., Major) \u2192 Scale notes appear on pads',
    qs_step3: 'Click a chord on the diatonic bar (e.g., Dm7) \u2192 Chord tones displayed',
    qs_step4: 'Click pads to play sounds. Change layouts in voicing boxes',
    qs_step5: 'Save favorite chords with <kbd>Option</kbd>+<kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> (16 slots)',
    qs_shortcuts: 'Keyboard Shortcuts',
    qs_shortcuts_desc: 'Press <kbd>?</kbd> for the full shortcut list.<br><kbd>Space</kbd> to play chord. <kbd>1</kbd>\u2013<kbd>7</kbd> for diatonic chords, <kbd>\u2191</kbd><kbd>\u2193</kbd> for inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> for chromatic movement.<br>In Perform mode, use <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> as a 4\u00D74 grid.',
    footer_open: 'Open 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Learn more on the blog \u2192',
    // Header Icons
    header_icons: 'Header Icons',
    header_icons_desc: 'Three icon buttons in the top-right corner.',
    icon_save: '<strong>\uD83D\uDCBE Save</strong> \u2014 Save current settings (sound, effects, display options, etc.) to the browser. Auto-restored on next visit',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 Browse 11 interactive tutorials. Learn each feature step by step',
    icon_help: '<strong>? Help</strong> \u2014 View shortcut keys, version history, and mode descriptions. Also opens with <kbd>?</kbd> key',
    // Sound Panel
    sound_panel: 'Sound Panel',
    sound_panel_desc: 'Select sound presets and adjust effects. Click the \u25B6 button to expand the panel.',
    sound_presets: 'Sound Presets',
    sound_presets_desc: 'Choose from ORGAN (4 types) and E.PIANO (8 types: Rhodes, FM EP, Clavinet, Sampler).',
    sound_effects: 'Effects',
    sound_effects_desc: 'Drag each knob to adjust values.',
    fx_drive: 'Analog saturation. Adds warm overdrive',
    fx_locut: 'Low-cut filter. Removes muddy bass',
    fx_hicut: 'High-cut filter. Tames harsh highs',
    fx_reverb: 'Reverb. Adds spatial depth',
    fx_phaser: 'Phaser. Sweeping modulation',
    fx_flanger: 'Flanger. Jet-like modulation',
    fx_tremolo: 'Tremolo. Periodic volume modulation',
    sound_autofilter: 'Auto-Filter (Auto-Wah)',
    sound_autofilter_desc: 'Envelope filter. Adjust FREQ, RESO, SENS, and DECAY.',
    version_history: 'Version History',
    vh_340: '<b>V3.40</b> \u2014 TASTY/Stock compact positioning: automatic optimal voicing layout on 64-pad grid. "To Pad" button removed. Voicing boxes hidden during TASTY/Stock mode',
    vh_336: '<b>V3.36</b> \u2014 Guitar voicing engine v2: genre presets (Jazz/Bossa/Funk), reference table (120 types \u00D7 12 keys), auto finger assignment with barre detection',
    vh_335: '<b>V3.35</b> \u2014 Tutorial UX improvements (beginner review). All tooltips translated to 9 languages. Guide: sound panel & header icon sections added',
    vh_333: '<b>V3.33</b> \u2014 Interactive tutorials. 11 topics \u00D7 9 languages. Context hints on first feature interaction',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 piano voicings with MIDI-specific keyboard display + "To Pad" reflect. Guide updated with HPS voicing features section',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 sophisticated voicings sorted by top note. Degree array display + auto octave optimization. HPS members only',
    vh_325: '<b>V3.25.0</b> \u2014 Guitar voicing \u2192 Pad reflect (<kbd>V</kbd> key). Guitar-like (1 note per row) / Compact layout switch. Guitar position "All" filter first',
    vh_324: '<b>V3.24</b> \u2014 Clavinet presets added (2 in E.PIANO). Auto Filter (envelope filter / auto-wah) effect added',
    vh_323: '<b>V3.23</b> \u2014 Text chord input with autocomplete. Press "/" to focus, supports abbreviations (dim, h=m7\u266D5), tension-count sorting',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Diatonic triad/tetrad toggle. Guitar/bass positions grouped by root string',
    vh_37: '<b>V3.7</b> \u2014 Voicing position preservation (auto-maintain fingering shape on chromatic movement). Pad grid, staff, and chord detection during playback. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 MIDI file playback \u2192 pad lighting (timeline playback, chord name display, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 E.PIANO sampler (Rhodes Mark I). 7 EP presets. Sound ON/OFF toggle. iPad support',
    vh_31: '<b>V3.1</b> \u2014 Velocity sensitivity (4 parameters + curve visualization). Push 3 octave button support. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 Multiple memory banks (16 slots \u00D7 up to 16 banks, switch/duplicate/rename)',
    vh_218: '<b>V2.18</b> \u2014 Auto save/restore all settings (key/scale/sound/MIDI/memory)',
    vh_213: '<b>V2.13</b> \u2014 Instrument scale overlay (guitar/bass/piano show Available Scale). Pad degree labels. Octave-linked playback',
    vh_27: '<b>V2.7</b> \u2014 Tension addition mode (pad/guitar/bass/keyboard chord synthesis \u2192 Available Scale filtering)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, scale overlay on pads)',
    vh_19: '<b>V1.9</b> \u2014 9 languages',
    vh_18: '<b>V1.8</b> \u2014 Perform mode, 16 memory slots, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Plain mode, MIDI/CHS export',
    vh_10: '<b>V1.0</b> \u2014 Initial release (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6th R',
    root_5: '5th R',
    root_4: '4th R',
    root_3: '3rd R',
    root_2: '2nd R',
    open: 'Open',
    all: 'All',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'To Pad',
    genre_default: 'Standard',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk',
  },
  tips: [
    'Press C to save the current chord to Memory',
    'Opt+1~V saves directly to a Memory slot (16 keys: 1234 QWER ASDF ZXCV)',
    'Shift+Click on a Memory slot to delete it',
    'Opt+Drag to copy a Memory slot to another',
    'Press S to cycle Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D cycles Drop 2 / Drop 3 voicings',
    'Shift+G shows Guitar fretboard view',
    'Shift+C shows Circle of Fifths',
    'Tab cycles Scale / Chord / Input modes',
    'Space plays the current scale or chord',
    'Export all Memory slots as a MIDI file from the Memory panel',
    'Connect a MIDI controller to play pads directly',
    'Arrow keys change chord inversion (Root / 1st / 2nd / 3rd)',
    'Press R for rootless voicing',
    'Press O to omit the 5th',
    'Shift+S shows staff notation',
    'The save icon preserves all your settings across sessions',
    '[ ] keys switch Memory banks — manage multiple songs',
    'Perform mode: Trigger saved chords with PC keyboard (1234 / QWER / ASDF / ZXCV) or MIDI pads',
    'Press / in Chord mode to type chord names directly (e.g. Cm7, G7(b9,#11))',
  ],
  tips_off: "Don't show tips",
  whats_new: "What's New",
  whats_new_32427: 'Guitar voicing \u2192 Pad reflect (V key). Guitar-like / Compact layout switch.',
  whats_new_33000: 'Tutorial system! Click the book icon in the header to learn Scale mode, Chord mode, and more.',

  // Legacy tutorial keys (backward compat for old lang files)
  tutorial: {
    sound_title: 'Sound Preset',
    sound_msg: 'Change the preset and tap a pad to hear it.\nORGAN and E.PIANO — each has multiple presets.',
    sound_done: 'Sounds good! Press Next to continue.',
    midi_title: 'MIDI Controller',
    midi_msg: 'A MIDI controller has been detected. Select your device from the dropdown.\nVelocity sensitivity can be adjusted in the Sound panel.',
    midi_no_device: 'No MIDI controller detected — that\'s OK.\nYou can use pad clicks, guitar/bass/piano input, or text chord input.',
    input_title: 'Three Modes',
    input_msg: 'Scale — view scale notes on the 64-pad grid\nChord — build chords with voicings, inversions, and tensions\nInput — tap pads freely to detect chord names\n\nSwitch with Tab or the mode buttons above.',
    instruments_title: 'Instrument Input',
    instruments_msg: 'Guitar, Bass, Piano — toggle each display and click to input notes directly.\nGuitar fretboard click \u2192 chord detection \u2192 "Pad reflect" (V) to convert to pad layout.\nText input: press / in Chord mode to type chord names (e.g. Cm7, G7(b9,#11)).',
    done_title: 'Ready!',
    done_msg: 'You\'re all set. Explore freely — press ? for the full shortcut list.\nThe Guide has screenshots, videos, and use cases.',
    next: 'Next',
    skip_step: 'Next',
    skip_all: 'Skip tutorial',
    open_guide: 'Open Guide',
    close: 'Start',
    reset: 'Restart tutorial',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: 'Tutorials',
    cat_getting_started: 'Getting Started',
    cat_features: 'Features',
    cat_advanced: 'Advanced',
    steps_label: 'steps',
    reset_all: 'Reset all progress',
    close_selector: 'Close',
    hint_available: 'Tutorial available',
    hint_try: 'Try it',
    // Button label
    btn_label: 'Tutorials',
    // Shared action labels
    next: 'Next',
    skip_step: 'Next',
    skip_all: 'Skip tutorial',
    open_guide: 'Open Guide',
    close: 'Done',
    // Onboarding ask dialog
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: 'First time here? Want a quick tour of the app?',
    onboarding_yes: 'Yes, show me!',
    onboarding_no: 'Skip',
    // Onboarding
    onboarding_title: 'First Steps',
    onboarding_desc: 'Learn the basics of 64 Pad Explorer',
    onboarding: {
      sound_title: 'Sound Preset',
      sound_msg: 'Change the preset and tap a pad to hear it.\nORGAN and E.PIANO — each has multiple presets.',
      sound_done: 'Sounds good! Press Next to continue.',
      midi_title: 'MIDI Controller',
      midi_msg: 'A MIDI controller has been detected. Select your device from the dropdown.\nVelocity sensitivity can be adjusted in the Sound panel.',
      midi_no_device: 'No MIDI controller detected — that\'s OK.\nYou can use pad clicks, guitar/bass/piano input, or text chord input.',
      input_title: 'Three Modes',
      input_msg: 'Scale — view scale notes on the 64-pad grid\nChord — build chords with voicings, inversions, and tensions\nInput — tap pads freely to detect chord names\n\nSwitch with Tab or the mode buttons above.',
      instruments_title: 'Instrument Input',
      instruments_msg: 'Guitar, Bass, Piano — toggle each display and click to input notes directly.\nGuitar fretboard click \u2192 chord detection \u2192 "Pad reflect" (V) to convert to pad layout.\nText input: press / in Chord mode to type chord names (e.g. Cm7, G7(b9,#11)).',
      done_title: 'Ready!',
      done_msg: 'You\'re all set. Explore freely — press ? for the full shortcut list.\nThe Guide has screenshots, videos, and use cases.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Scale Mode',
    scale_mode_desc: 'Explore scales on the 64-pad grid',
    scale_mode: {
      step1_title: 'Switch to Scale Mode',
      step1_msg: 'Scale mode shows scale notes lit up across the pad grid.\nTap any lit pad to hear the note.',
      step2_title: 'Choose a Key',
      step2_msg: 'Pick a key from Major and Minor rows (Cycle of 4ths order).\nYou can also set the key from the Circle of Fifths. Outer ring = major keys, inner ring = minor keys. Minor keys support 3 types of minor scales.\nTry switching between C, G, F.',
      step3_title: 'Choose a Scale',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 scales available. The pads update in real time.',
      step4_title: 'Diatonic Bar',
      step4_msg: 'The diatonic chords for your chosen scale appear here.\nPress 3 for triads, 4 for tetrads (7th chords).\nClick any chord to jump into Chord mode with that voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Chord Mode',
    chord_mode_desc: 'Build chords step by step',
    chord_mode: {
      step1_title: 'Switch to Chord Mode',
      step1_msg: 'Chord mode lets you build any chord from scratch.\nKey → Root → Quality → Tension.',
      step_key_title: 'Key Selection',
      step_key_msg: 'Set the scale key. When a Key is set, the diatonic bar shows chords and tension availability is filtered.\nYou can also build chords freely from Root without using Key.',
      step_diatonic_title: 'Diatonic Bar',
      step_diatonic_msg: 'Diatonic chords for the selected Key.\nClick to instantly set a chord with scale-aware tension filtering.',
      step2_title: 'Root',
      step2_msg: 'Pick the chord root note. All 12 notes.\nIndependent from Key — build non-diatonic chords freely.',
      step3_title: 'Chord Quality',
      step3_msg: 'Choose the chord type: Maj, min, 7, m7, dim, aug...\nThe pad grid lights up the chord tones.',
      step4_title: 'Tensions',
      step4_msg: 'Choose Quality first — tension buttons appear automatically.\nWhen using the diatonic bar, available tensions are highlighted based on the scale.',
      step5_title: 'Text Input',
      step5_msg: 'Type chord names directly with / key.\nSlash chords and complex voicings can be entered quickly.',
    },
    // Input Mode tutorial
    input_mode_title: 'Input Mode',
    input_mode_desc: 'Input chords via MIDI controller, pads, fretboard, or keyboard',
    input_mode: {
      step1_title: 'Switch to Input Mode',
      step1_msg: 'Input chords via MIDI controller, clicking pads, fretboard, or keyboard.\nChord detection works in all modes.',
      step2_title: 'Tap Some Pads',
      step2_msg: 'Click any pads on the grid.\nEach tap toggles a note on or off.',
      step3_title: 'Chord Detection',
      step3_msg: 'The detected chord name appears above the grid.\nDegree labels (R, 3, 5, b7...) show on each pad.',
      step4_title: 'Save with Capture',
      step4_msg: '<strong>C</strong> key saves the current chord to the next memory slot.\nBuild chord progressions one by one.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Diatonic Bar',
    diatonic_desc: 'One-click access to diatonic chords',
    diatonic: {
      step1_title: 'The Diatonic Bar',
      step1_msg: 'Every scale has its own set of diatonic chords.\nThey appear here — ready to play.',
      step2_title: 'Triad / Tetrad',
      step2_msg: 'Toggle between 3-note triads and 4-note seventh chords.\nThe bar updates instantly.',
      step3_title: 'Click a Chord',
      step3_msg: 'Click a chord on the bar.\nYou can transform it with tensions and more in the Chord Builder.',
      step4_title: 'Keyboard Shortcut',
      step4_msg: 'Press 1–7 to select diatonic chords instantly.\nNo mouse needed.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Save chords and play them live',
    memory: {
      step1_title: 'Save a Chord',
      step1_msg: 'Save your favorite chords.\nSaving voicings you like helps with beat-making and practice.',
      step2_title: '16 Memory Slots',
      step2_msg: 'Works like a 16-pad Drumrack layout on PUSH, Launchpad, MPC, and Maschine — intuitive to use.',
      step3_title: 'Memory Banks',
      step3_msg: 'On PUSH and Launchpad, the Drumrack layout makes it intuitive to use.',
      step4_title: 'Perform Mode',
      step4_msg: 'PC keyboard keys also correspond to the 16 pads.',
      step5_title: 'MIDI Export',
      step5_msg: 'Export all memory chords as a MIDI file.\nDrag into your DAW and start producing.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Shape your chord voicings',
    voicing: {
      step1_title: 'Voicing Controls',
      step1_msg: 'In Chord Builder mode, various transformations are possible from the basic form.\nOmit, Shell, Inversion, Drop — all here.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> is for Shell voicing. Learn R37 and R73 voicings\nsmoothly on the pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Shortcut keys are often set to mnemonics.\n<strong>O</strong>mit = omit 5th. <strong>R</strong>ootless = rootless voicing.',
      step4_title: 'Inversions',
      step4_msg: 'Unlike most software, you can create inversions ultra-fast.\nAlso helps understand slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'For when you want to feature the top note —\nDrop voicings are also supported.',
      step6_title: 'Voicing Box',
      step6_msg: 'Pads can have multiple position options. The Voicing Box handles this.\nClick a, b, c, d etc. on the pad, or type the letter, to see multiple voicing possibilities.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, effects, and volume',
    sound: {
      step1_title: 'Sound Presets',
      step1_msg: 'ORGAN (4 types) and E.PIANO (8 types).\nClick a pad or use your MIDI controller.',
      step2_title: 'Detail Panel',
      step2_msg: 'Click ▼ to expand the sound detail panel.\nEffects, volume, and filter controls live here.',
      step3_title: 'Effects',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nTweak them in the detail panel.',
      step4_title: 'Sound ON/OFF',
      step4_msg: 'Toggle sound ON/OFF with the speaker icon.\nTurning it off can be convenient when using a DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings classified by top note. HPS members only',
    tasty: {
      step1_title: 'Activate TASTY',
      step1_msg: 'Select hip voicings that simple logic alone can\'t produce.\nThinking from the top note is useful for string and horn arrangements.\n(HPS members only)',
      step2_title: 'Cycle Recipes',
      step2_msg: 'Press T again to cycle through voicings.\nShift+T goes backward. The counter shows your position.',
      step3_title: 'Degree Notation',
      step3_msg: 'The info area shows the degree stack — e.g. m9 (b3-b7-9-5-1).\nThis is the voicing structure from bottom to top.',
      step4_title: 'To Pad',
      step4_msg: 'Pad optimization that typical software can\'t do.\nEnjoy playing stylish voicings on pads too.',
      fb_step1_title: 'What is TASTY Voicing?',
      fb_step1_msg: '129 sophisticated voicings sorted by top note.\nSupports Maj7 / Dom7 / Min7. Displayed in degree notation.\nHPS members only.',
      fb_step2_title: 'How to Access TASTY',
      fb_step2_msg: 'Available when you join HPS (Hardcore Pad Style).\nPress T in Chord mode to activate. Press again to switch to another voicing.\nSee the Guide for details.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Classic piano voicing idioms. HPS members only',
    stock: {
      step1_title: 'Activate STOCK',
      step1_msg: 'Knowing piano-specific voicings helps you break free from basic-form-only playing.\n154 piano voicings in degree notation.\n(HPS members only)',
      step2_title: 'Cycle Voicings',
      step2_msg: 'Press K again to step through voicings.\nShift+K goes backward.',
      step3_title: 'Keyboard View',
      step3_msg: 'Turn on Piano display to see the actual key positions.\nThe voicing comes alive on the keyboard.',
      step4_title: 'To Pad',
      step4_msg: 'Click "To Pad" to map the voicing to pad layout.\nSave to memory and export to your DAW.',
      fb_step1_title: 'What is STOCK Voicing?',
      fb_step1_msg: 'Presents commonly used piano voicings.\nDegree notation shows you the structure.\nHPS members only.',
      fb_step2_title: 'How to Access STOCK',
      fb_step2_msg: 'Available when you join HPS (Hardcore Pad Style).\nPress K in Chord mode to activate.\nSee the Guide for details.',
    },
    // Circle of Fifths tutorial
    circle_title: 'Circle of Fifths',
    circle_desc: 'Key relationships at a glance',
    circle: {
      step1_title: 'Open the Circle',
      step1_msg: 'Press Shift+C or click the Circle button.\nThe circle of fifths appears below.',
      step2_title: 'Key Linking',
      step2_msg: 'Quickly check proxy chords and diatonics that are important for performance and composition.',
      step3_title: 'Diatonic Functions',
      step3_msg: 'Unlike typical circle of fifths displays, 64 Pad Explorer lets you select 3 types of minor (Natural/Harmonic/Melodic) when you choose a minor key.\nMakes mastering tricky minor keys easier.',
      step4_title: 'Select a Minor Key',
      step4_msg: 'The inner ring of the circle shows minor keys.\nClick a key on the inner ring to select a minor key.\nThe diatonic chord display will change.',
      step5_title: '3 Minor Scale Types',
      step5_msg: 'When a minor key is selected, Nat / Harm / Mel buttons appear in the center.\nNat = Natural Minor (standard form)\nHarm = Harmonic Minor (V7 appears)\nMel = Melodic Minor (VI, VII degrees change)\nClick each to see how the diatonic chords change.',
    },
    // Guitar tutorial
    guitar_title: 'Guitar Diagram',
    guitar_desc: 'Input chords from guitar & reflect to pads',
    guitar: {
      step1_title: 'Show Guitar Fretboard',
      step1_msg: 'Press Shift+G or click the Guitar button.\nChord tones appear on the fretboard.',
      step2_title: 'View Chord Positions',
      step2_msg: 'Select a chord in Chord mode and the fretboard automatically shows matching positions.\nUse comma (,) and period (.) keys to cycle through positions.',
      step3_title: 'Input from Guitar',
      step3_msg: 'In Input mode, click frets on the fretboard to input notes.\nChord names are detected in real-time from your input.',
      step4_title: 'Reflect to Pad',
      step4_msg: 'Press V for "Reflect to Pad".\nChoose between guitar-like (one note per row) and compact layouts.\nPlay guitar voicings directly on pads.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Keyboard Shortcuts',
    shortcuts_desc: 'Essential keys for efficient operation',
    shortcuts: {
      step1_title: 'Mode Switching',
      step1_msg: 'Tab — Switch modes (Scale → Chord → Input)\nShift+Tab — Reverse direction\n\nQuickly move between modes.',
      step2_title: 'Diatonic & Navigation',
      step2_msg: '1–7 — Select diatonic chord\n↑↓ — Cycle inversions\n←→ — Transpose root by semitone (keeps chord shape)\n\nOperate chords without a mouse.',
      step3_title: 'Voicing Operations',
      step3_msg: 'S — Shell cycle (off → 1-3-7 → 1-7-3)\nO — Omit 5 toggle\nR — Rootless toggle\nShift+D — Drop cycle (off → Drop2 → Drop3)\nV — Reflect to pad / layout toggle\n/ — Text chord input',
      step4_title: 'Memory & Banks',
      step4_msg: 'Option+1234/qwer/asdf/zxcv — Save to slot\n[ ] — Switch banks\nM — Memory view toggle\nP — Perform mode toggle\nSpace — Play\nShift+Space — Play All (sequential)',
      step5_title: 'More',
      step5_msg: '? — Help (full shortcut list)\nShift+G/B/P — Guitar/Bass/Piano toggle\nShift+C — Circle of Fifths toggle\nCmd/Ctrl+Z — Undo (up to 30 times)\nEsc — Deselect / Close modals',
    },
    // Settings tutorial
    settings_title: 'Display & Settings',
    settings_desc: 'Customize your workspace',
    settings: {
      step1_title: 'Instrument Panels',
      step1_msg: 'Guitar displays commonly used voicings when you select a chord in the Chord Builder.\nIn Input mode, you can also input from guitar, bass, and keyboard.',
      step2_title: 'Note Names / Degrees',
      step2_msg: 'Switch between note names (C, D, E) and degrees (R, 2, 3).\nApplies to pads and guitar display.',
      step3_title: 'Octave Shift',
      step3_msg: 'Use ▲▼ to shift the pad range up or down an octave.\nPush 3 octave buttons sync automatically.',
      step4_title: 'Save Everything',
      step4_msg: 'Click the save icon to preserve all settings.\nKey, scale, sound, memory, voicing — everything persists.',
    },
  },
});
