// Español
I18N.addLang('es', {
  help: {
    title: '64 Pad Explorer',
    description: 'Herramienta para explorar escalas, acordes y voicings en una cuadrícula de 64 pads.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Elige entre 12 tonalidades',
    scale_scale: '<strong>Scale</strong> \u2014 Diatónica, Menor Armónica, Menor Melódica, Pentatónica, Bebop y más \u2014 31 tipos',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Muestra los acordes diatónicos de la escala seleccionada. Haz clic para entrar en Chord Mode',
    chord_mode: 'Chord Mode (3 pasos)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selecciona la nota raíz en el teclado de piano',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Elige el tipo de acorde (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Añade tensiones (9, b9, #9, 11, #11, 13, b13, etc.). Selección múltiple OK',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usa el botón "/" para acordes con bajo alterno (acorde sobre nota de bajo)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omitir notas',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 para añadir notas)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversiones (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Toca para recorrer las opciones de disposición en el pad (badge pulsante = disposiciones alternativas disponibles)',
    display: 'Visualización',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Activa/desactiva el diapasón de guitarra, el teclado de piano y la partitura de forma independiente',
    display_label: '<strong>Nombre de nota / Grado</strong> \u2014 Alterna entre nombres de notas (C, D, E) y grados (R, 2, 3) en la guitarra y los pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Desplaza el rango de los pads por octava',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 presets (Rhodes, FM, etc.)',
    sound_fx: '<strong>Efectos</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Haz clic en un pad o en el Voicing Box para reproducir sonido',
    midi: 'MIDI',
    midi_detect: 'Detecta automáticamente dispositivos compatibles con WebMIDI',
    midi_push: 'Compatible con la salida MIDI serial de Ableton Push',
    midi_chord: 'Identifica acordes automáticamente a partir de las notas de entrada',
    color_title: 'Leyenda de colores',
    color_root: '<strong>Root</strong> \u2014 Nota raíz',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notas de la escala / Notas del acorde',
    color_char: '<strong>Nota característica</strong> \u2014 Notas que definen la escala/el acorde',
    color_3rd: '<strong>3rd</strong> \u2014 Nota guía (3.ª)',
    color_7th: '<strong>7th</strong> \u2014 Nota guía (7.ª)',
    color_tension: '<strong>Tension</strong> \u2014 Notas de tensión',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota de la escala a un semitono por encima de una nota del acorde (en Chord Mode)',
    color_palette: 'Paleta de colores: Okabe-Ito (accesible para distintas visiones del color)',
    input_title: 'Entrada por Guitar / Piano',
    input_desc1: 'Haz clic en el diapasón de guitarra o en el teclado de piano para ingresar notas',
    input_desc2: 'Los acordes se identifican automáticamente a partir de la entrada y se reflejan en el pad',
    input_desc3: '<strong>Clear</strong> \u2014 Borrar entrada, <strong>Play \u25B6</strong> \u2014 Reproducir las notas ingresadas',
    input_title: 'Input Mode',
    input_desc1: 'Haz clic en los pads libremente para seleccionar notas \u2192 Identificación de acordes en tiempo real',
    input_desc2: 'Sin filtro de teor\u00EDa. Explora \u2192 descubre \u2192 aprende la teor\u00EDa despu\u00E9s',
    input_desc3: 'Al detectar un acorde, se muestran etiquetas de grado (R, 3, 5, b7, etc.) en los pads. Guitarra, bajo, piano y pentagrama se actualizan autom\u00E1ticamente',
    input_memory: '<strong>Memory</strong> \u2014 Guarda y recupera acordes en 16 ranuras',
    input_export: '<strong>MIDI Export</strong> \u2014 Exporta los acordes de memoria como archivo MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> botón o tecla <kbd>p</kbd> para cambiar',
    perform_desc1: 'Toca los acordes de los Memory Slots en tiempo real con un layout de 16 pads',
    perform_desc2: 'Activa mediante teclado (cuadr\u00EDcula 4\u00D74) o pads MIDI',
    perform_desc3: 'Arrastra y suelta Slots para reordenar',
    shortcut_title: 'Atajos de teclado',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Seleccionar acorde diatónico (escalas de 7 notas)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Seleccionar Voicing Box (recorre las alternativas)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Recorrer inversiones (Chord Mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transporte cromático de la raíz',
    sc_omit: '<kbd>o</kbd> \u2014 Alternar Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Alternar Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclar Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclar Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Borrar acorde (Chord Mode)',
    sc_pad_explore: '<b>Pad (modo Chord)</b> \u2014 Clic para activar/desactivar nota \u2014 constructor actualizado automáticamente',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Iniciar Capture / guardar en la siguiente ranura',
    sp_end: '<kbd>e</kbd> \u2014 Finalizar Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recuperar ranura de memoria (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transporte cromático (todas las notas \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversión (nota más grave \u21911oct / nota más aguda \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Borrar todo',
    sp_transfer: '<b>Cambiar a Chord</b> \u2014 Transferir el acorde detectado a Chord Mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Cuadr\u00EDcula 4\u00D74 activa Slots 1\u201316',
    pf_midi: 'Los pads MIDI (notas 36\u201354) tambi\u00E9n activan Slots',
    shortcut_common: 'Com\u00FAn (Todos los modos)',
    sc_perform: '<kbd>p</kbd> \u2014 Alternar vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Deshacer Memory Slots (hasta 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Guardar en ranura de memoria Input (desde cualquier modo)',
    sc_space: '<kbd>Space</kbd> \u2014 Reproducir acorde actual',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deseleccionar Voicing Box / cerrar Ayuda',
    sc_help: '<kbd>?</kbd> \u2014 Mostrar/ocultar Ayuda',
    footer: '64 Pad Explorer V2.10 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Nota característica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Cerrar',
    slot_hint: 'Clic para seleccionar \u2192 Save(c) / Shift+clic para borrar',
    save_settings: 'Guardar configuración',
    sound_hint: 'Selecciona ORGAN o E.PIANO para activar el sonido',
    load_vst: 'Cargar plugin VST/AU...',
    affiliate_label: '',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grado',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mi Blog',
    guide: 'Gu\u00EDa',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Pulsa Capture para empezar a construir acordes',
    status_capturing: 'Capturando: Ranura {slot}/16 \u2014 Haz clic en los pads y luego Capture para guardar',
    status_editing: 'Editando: Ranura {slot} \u2014 Haz clic en los pads para modificar',
    notes_label: 'Notas: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Ranura {slot} seleccionada',
    slot_cleared: 'Ranura {slot} borrada',
    undo: 'Deshacer',
    settings_saved: 'Configuración guardada',
    no_chords: 'No hay acordes en las ranuras de memoria',
  },
  info: {
    note_count: '{n} notas',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Selecciona la raíz',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Ranura {slot}: Vacía',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Clic para renombrar',
    rename: 'Renombrar',
    duplicate: 'Duplicar',
    delete: 'Eliminar',
    rename_prompt: 'Nombre del banco:',
    confirm_delete: '\u00BFEliminar "{name}"?',
    limit_reached: 'M\u00E1ximo 16 bancos',
    cannot_delete_last: 'No se puede eliminar el \u00FAltimo banco',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostrar todo',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Gu\u00EDa',
    tagline: 'Una herramienta de navegador para explorar escalas, acordes y voicings en una cuadr\u00EDcula de 64 pads.<br>No necesitas fuente de sonido \u2014 solo Chrome.',
    cta: 'Abrir App',
    features: 'Caracter\u00EDsticas',
    feat_sound: '<strong>Sin fuente de sonido necesaria</strong> \u2014 El sonido se reproduce directamente en Chrome. 4 presets de \u00F3rgano + 7 de piano el\u00E9ctrico integrados. Efectos incluidos (reverb, phaser, flanger, tr\u00E9molo, filtro)',
    feat_input: '<strong>Sin habilidades de pad necesarias</strong> \u2014 Construye acordes en 3 pasos. Tensiones mostradas. Haz clic en los pads para ingresar directamente',
    feat_detect: '<strong>Detecci\u00F3n de acordes</strong> \u2014 Detecci\u00F3n en tiempo real del nombre del acorde a partir de las notas clicadas. Soporta omit, acordes con bajo alterno y m\u00FAltiples candidatos',
    feat_instruments: '<strong>Visualizaci\u00F3n de Guitar / Bass / Keyboard</strong> \u2014 Muestra las notas del acorde en el diapas\u00F3n de guitarra, bajo y piano. La entrada de digitaci\u00F3n de guitarra se refleja autom\u00E1ticamente en los pads',
    feat_scales: '<strong>Visualizaci\u00F3n de escalas</strong> \u2014 31 escalas \u00D7 12 tonalidades. Diat\u00F3nica, Menor Arm\u00F3nica, Menor Mel\u00F3dica, Pentat\u00F3nica, Bebop y m\u00E1s',
    feat_diatonic: '<strong>Visualizaci\u00F3n de acordes diat\u00F3nicos</strong> \u2014 Los acordes diat\u00F3nicos se muestran en una barra para la escala seleccionada. Haz clic o usa atajos para reproducir al instante',
    feat_voicing: '<strong>Operaciones de voicing</strong> \u2014 Inversiones, Drop 2/3, Shell Voicing, Omit, Rootless. Teclas de flechas para inversiones, botones para m\u00FAltiples digitaciones',
    feat_memory: '<strong>Memoria de acordes</strong> \u2014 Guarda tus acordes favoritos en 16 ranuras. Exporta como archivos MIDI para tu DAW',
    feat_perform: '<strong>Modo Perform</strong> \u2014 Toca los acordes de memoria en tiempo real usando 16 pads o tu teclado de PC',
    feat_parent: '<strong>B\u00FAsqueda inversa de Available Scale</strong> \u2014 Encuentra escalas que contengan tu acorde. Ve los Available Tensions de un vistazo. Alternancia Practical/Diatonic',
    feat_pivot: '<strong>Pensamiento de acorde pivote</strong> \u2014 Ingresa un acorde manualmente y la barra diat\u00F3nica desaparece, mostrando todas las tonalidades a las que tu acorde podr\u00EDa pertenecer. Ideal para an\u00E1lisis de modulaci\u00F3n',
    feat_dimming: '<strong>Visualizaci\u00F3n pr\u00E1ctica de Tensions</strong> \u2014 Para acordes de 7\u00AA no dominante, las tensiones poco comunes (b9, #9, b13, etc.) se muestran atenuadas. A\u00FAn seleccionables',
    feat_i18n: '<strong>Multiling\u00FCe</strong> \u2014 9 idiomas (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Capturas de pantalla',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Selecciona una tonalidad y escala para ver las notas de la escala codificadas por color en la cuadr\u00EDcula de 64 pads. Elige acordes de la barra diat\u00F3nica.',
    ss_scale_alt: 'Scale Mode \u2014 Visualizaci\u00F3n de la escala C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Ra\u00EDz (naranja), notas de escala (azul), notas caracter\u00EDsticas (amarillo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construye acordes en 3 pasos: Root \u2192 Quality \u2192 Tension. Ajusta voicings con inversiones, Drop, Shell y Omit. Usa el panel Parent Scale para b\u00FAsqueda inversa de escalas.',
    ss_chord_alt: 'Chord Mode \u2014 Visualizaci\u00F3n del acorde Dm7 con cuadr\u00EDcula de tensiones',
    ss_chord_caption: 'Dm7 \u2014 Notas del acorde, 3rd (rosa), 7th (verde). Consulta las opciones de disposici\u00F3n en los Voicing Boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Haz clic en los pads libremente para detecci\u00F3n de acordes en tiempo real. Entiende los acordes incluso sin conocer la teor\u00EDa.',
    ss_input_alt: 'Input Mode \u2014 Detecci\u00F3n en tiempo real de C7',
    ss_input_caption: 'C7 \u2014 Haz clic en los pads para detectar autom\u00E1ticamente nombres de acordes. Se muestran m\u00FAltiples candidatos',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Coloca los acordes guardados en 16 pads para interpretaci\u00F3n en tiempo real usando teclado o pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 ranuras con acordes',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 guardados en ranuras. Toca usando la cuadr\u00EDcula 4\u00D74 del teclado',
    ss_parent: 'Available Scale + Acorde Pivote',
    ss_parent_desc: 'B\u00FAsqueda inversa de escalas que contengan tu acorde. Alterna entre ordenamiento Practical (por usabilidad) y Diatonic (por teor\u00EDa). La entrada manual de acordes oculta la barra diat\u00F3nica para an\u00E1lisis de acordes pivote.',
    ss_parent_alt: 'Panel Parent Scale y visualizaci\u00F3n del diapas\u00F3n de guitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Se muestran los Available Tensions',
    ss_parent_note: '\u203B Las escalas pentat\u00F3nicas/blues son modales (enfoque horizontal) y pertenecen a un sistema diferente de la teor\u00EDa de escalas por acorde (mapeo vertical), por lo que no se incluyen en Available Scale. En la pr\u00E1ctica, la pentat\u00F3nica suele ser la primera opci\u00F3n.',
    usecases: 'Casos de uso',
    uc1_q: '"Quiero encontrar c\u00F3mo hacer el voicing de este acorde en los pads"',
    uc1_a: '\u2192 Selecciona Root, Quality y Tension en el modo <span class="mode-badge chord">Chord</span> \u2192 Consulta las disposiciones en los Voicing Boxes',
    uc2_q: '"Quiero ver una escala de mi lecci\u00F3n en los pads"',
    uc2_a: '\u2192 Selecciona tonalidad y escala en el modo <span class="mode-badge scale">Scale</span>. 31 escalas disponibles',
    uc3_q: '"Quiero crear una progresi\u00F3n de acordes para mi DAW"',
    uc3_a: '\u2192 Guarda acordes en las ranuras de memoria \u2192 MIDI Export para importar en tu DAW',
    uc4_q: '"\u00BFA qu\u00E9 tonalidad pertenece este acorde?"',
    uc4_a: '\u2192 B\u00FAsqueda inversa en el panel Available Scale. Alterna entre ordenamiento Practical/Diatonic',
    uc7_q: '"Quiero encontrar acordes pivote para modulaci\u00F3n"',
    uc7_a: '\u2192 Ingresa un acorde manualmente en el modo <span class="mode-badge chord">Chord</span>. La barra diat\u00F3nica desaparece y Available Scale muestra todas las tonalidades posibles',
    uc5_q: '"Quiero comprobar progresiones de acordes toc\u00E1ndolos"',
    uc5_a: '\u2192 Guarda los acordes en los slots de memoria y t\u00F3calos con un controlador MIDI o el teclado del PC',
    uc6_q: '"Quiero verificar acordes de guitarra en los pads"',
    uc6_a: '\u2192 Haz clic en el diapas\u00F3n de guitarra para ingresar \u2192 Se muestra autom\u00E1ticamente en los pads \u2192 Se detecta el nombre del acorde',
    quickstart: 'Inicio r\u00E1pido',
    qs_modes: '3 modos',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Muestra escalas y acordes diat\u00F3nicos<br><span class="mode-badge chord">Chord</span> Construye acordes en 3 pasos. Operaciones de voicing disponibles<br><span class="mode-badge input">Input</span> Haz clic en los pads libremente \u2192 Detecci\u00F3n autom\u00E1tica de nombres de acordes',
    qs_first: 'Primeros pasos',
    qs_step1: 'Elige una tonalidad (ej. C)',
    qs_step2: 'Elige una escala (ej. Major) \u2192 Las notas de la escala aparecen en los pads',
    qs_step3: 'Haz clic en un acorde de la barra diat\u00F3nica (ej. Dm7) \u2192 Se muestran las notas del acorde',
    qs_step4: 'Haz clic en los pads para reproducir sonidos. Cambia disposiciones en los Voicing Boxes',
    qs_step5: 'Guarda tus acordes favoritos con <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Atajos de teclado',
    qs_shortcuts_desc: 'Pulsa <kbd>?</kbd> para ver la lista completa de atajos.<br><kbd>Space</kbd> para reproducir acorde. <kbd>1</kbd>\u2013<kbd>7</kbd> para acordes diat\u00F3nicos, <kbd>\u2191</kbd><kbd>\u2193</kbd> para inversiones, <kbd>\u2190</kbd><kbd>\u2192</kbd> para movimiento crom\u00E1tico.<br>En el modo Perform, usa <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> como cuadr\u00EDcula 4\u00D74.',
    footer_open: 'Abrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'M\u00E1s informaci\u00F3n en el blog \u2192',
    version_history: 'Historial de versiones',
    vh_37: '<b>V3.7</b> \u2014 Conservaci\u00F3n de posici\u00F3n de voicing (mantener autom\u00E1ticamente la forma de la digitaci\u00F3n en movimiento crom\u00E1tico). Cuadr\u00EDcula de pads, pentagrama y detecci\u00F3n de acordes durante la reproducci\u00F3n. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 Reproducci\u00F3n de archivo MIDI \u2192 iluminaci\u00F3n de pads (reproducci\u00F3n por l\u00EDnea de tiempo, visualizaci\u00F3n del nombre del acorde, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Rhodes Mark I). 7 presets de EP. Interruptor de sonido ON/OFF. Soporte para iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilidad de velocidad (4 par\u00E1metros + visualizaci\u00F3n de curva). Soporte para el bot\u00F3n de octava de Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 M\u00FAltiples bancos de memoria (16 slots \u00D7 hasta 16 bancos, cambiar/duplicar/renombrar)',
    vh_218: '<b>V2.18</b> \u2014 Guardado/restauraci\u00F3n autom\u00E1tica de todos los ajustes (tonalidad/escala/sonido/MIDI/memoria)',
    vh_213: '<b>V2.13</b> \u2014 Superposici\u00F3n de escala de instrumento (guitarra/bajo/piano muestran Available Scale). Etiquetas de grado en pads. Reproducci\u00F3n vinculada a octava',
    vh_27: '<b>V2.7</b> \u2014 Modo de adici\u00F3n de tensiones (s\u00EDntesis de acordes en pad/guitarra/bajo/teclado \u2192 filtrado por Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, superposici\u00F3n de escala en pads)',
    vh_19: '<b>V1.9</b> \u2014 9 idiomas',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 ranuras de memoria, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Modo Plain, exportaci\u00F3n MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Lanzamiento inicial (Scale/Chord/Voicing/Sound/MIDI)',
  },
});
