// Deutsch
I18N.addLang('de', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: 'Ein Werkzeug zum Erkunden von Skalen, Akkorden und Voicings auf einem 64-Pad-Raster.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Aus 12 Tonarten wählen',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonisch, harmonisch Moll, melodisch Moll, Pentatonik, Bebop und mehr \u2014 31 Typen',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Zeigt die diatonischen Akkorde der gewählten Skala. Klicken, um in den Chord-Modus zu wechseln',
    chord_mode: 'Chord Mode (3 Schritte)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Grundton auf der Klaviertastatur auswählen',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Akkordtyp wählen (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Tensions hinzufügen (9, b9, #9, 11, #11, 13, b13, etc.). Mehrfachauswahl möglich',
    chord_onchord: '<strong>On Chord</strong> \u2014 Die "/"-Taste für Slash-Akkorde verwenden (Akkord über Basston)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Töne weglassen',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell Voicing (+1, +2 um Töne hinzuzufügen)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Umkehrungen (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop Voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Antippen, um Pad-Anordnungen durchzuschalten (pulsierendes Badge = alternative Anordnungen verfügbar)',
    display: 'Anzeige',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Gitarrengriffbrett, Klaviertastatur und Notenzeile unabhängig ein-/ausschalten',
    display_label: '<strong>Notenname / Stufe</strong> \u2014 Zwischen Notennamen (C, D, E) und Stufen (R, 2, 3) auf Gitarre und Pads umschalten',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Pad-Tonumfang um eine Oktave verschieben',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 Presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 Presets (Rhodes, FM, etc.)',
    sound_fx: '<strong>Effekte</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Pad oder Voicing Box anklicken, um den Klang abzuspielen',
    midi: 'MIDI',
    midi_detect: 'Automatische Erkennung WebMIDI-kompatibler Geräte',
    midi_push: 'Unterstützung für serielle MIDI-Ausgabe von Ableton Push',
    midi_chord: 'Automatische Akkorderkennung aus eingegebenen Noten',
    color_title: 'Farblegende',
    color_root: '<strong>Root</strong> \u2014 Grundton',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Skalentöne / Akkordtöne',
    color_char: '<strong>Charakteristisch</strong> \u2014 Töne, die die Skala/den Akkord definieren',
    color_3rd: '<strong>3rd</strong> \u2014 Guide Tone (Terz)',
    color_7th: '<strong>7th</strong> \u2014 Guide Tone (Septime)',
    color_tension: '<strong>Tension</strong> \u2014 Spannungstöne',
    color_avoid: '<strong>Avoid</strong> \u2014 Skalenton einen Halbton über einem Akkordton (im Chord-Modus)',
    color_palette: 'Farbpalette: Okabe-Ito (farbfehlsichtigkeitsfreundlich)',
    input_title: 'Guitar / Piano Eingabe',
    input_desc1: 'Gitarrengriffbrett oder Klaviertastatur anklicken, um Noten einzugeben',
    input_desc2: 'Akkorde werden automatisch aus der Eingabe erkannt und auf dem Pad dargestellt',
    input_desc3: '<strong>Clear</strong> \u2014 Eingabe löschen, <strong>Play \u25B6</strong> \u2014 Eingegebene Noten abspielen',
    plain_title: 'Plain Mode',
    plain_desc1: 'Pads frei anklicken, um Noten auszuwählen \u2192 Echtzeit-Akkorderkennung',
    plain_desc2: 'Ohne Theoriefilter. Erkunden \u2192 entdecken \u2192 Theorie danach lernen',
    plain_memory: '<strong>Memory</strong> \u2014 Akkorde in 16 Slots speichern und abrufen',
    plain_export: '<strong>MIDI Export</strong> \u2014 Gespeicherte Akkorde als MIDI-Datei exportieren',
    perform_title: 'Perform Mode',
    perform_desc1: 'Memory Slot-Akkorde in Echtzeit mit einem 16-Pad-Layout spielen',
    perform_desc2: '\u00DCber Tastatur (4\u00D74-Raster) oder MIDI-Pads ausl\u00F6sen',
    perform_desc3: 'Slots per Drag & Drop neu anordnen',
    shortcut_title: 'Tastenkürzel',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Diatonischen Akkord auswählen (7-Ton-Skalen)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Voicing Box auswählen (Alternativen durchschalten)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Umkehrungen durchschalten (Chord-Modus)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatische Transposition des Grundtons',
    sc_omit: '<kbd>o</kbd> \u2014 Omit 5 umschalten',
    sc_rootless: '<kbd>r</kbd> \u2014 Rootless umschalten',
    sc_shell: '<kbd>s</kbd> \u2014 Shell durchschalten (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Drop durchschalten (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Akkord löschen (Chord-Modus)',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Capture starten / im nächsten Slot speichern',
    sp_end: '<kbd>e</kbd> \u2014 Capture beenden',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Speicherslot abrufen (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatische Transposition (alle Noten \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Umkehrung (tiefste \u21911 Okt. / höchste \u21931 Okt.)',
    sp_clear: '<kbd>x</kbd> \u2014 Alles löschen',
    sp_transfer: '<b>Chord switch</b> \u2014 Erkannten Akkord in den Chord-Modus übertragen',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74-Raster l\u00F6st Slots 1\u201316 aus',
    pf_midi: 'MIDI-Pads (Noten 36\u201354) l\u00F6sen ebenfalls Slots aus',
    shortcut_common: 'Allgemein (alle Modi)',
    sc_perform: '<kbd>p</kbd> \u2014 Perform-Ansicht umschalten',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Memory Slots r\u00FCckg\u00E4ngig machen (bis zu 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 In Plain-Speicherslot speichern (aus jedem Modus)',
    sc_esc: '<kbd>Esc</kbd> \u2014 Voicing Box abwählen / Hilfe schließen',
    sc_help: '<kbd>?</kbd> \u2014 Hilfe ein-/ausblenden',
    footer: '64 Pad Explorer V1.9 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Charakteristisch',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Schließen',
    slot_hint: 'Klicken zum Auswählen \u2192 Save(c) / Shift+Klick zum Löschen',
  },
  label: {
    note_name: 'Note',
    degree: 'Stufe',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
  },
  plain: {
    status_idle: 'Capture drücken, um Akkorde zu erstellen',
    status_capturing: 'Aufnahme: Slot {slot}/16 \u2014 Pads anklicken, dann Capture zum Speichern',
    status_editing: 'Bearbeitung: Slot {slot} \u2014 Pads anklicken zum Ändern',
    notes_label: 'Noten: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} ausgewählt',
    slot_cleared: 'Slot {slot} gelöscht',
    undo: 'Rückgängig',
    no_chords: 'Keine Akkorde in den Speicherslots',
  },
  info: {
    note_count: '{n} Töne',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Grundton auswählen',
  },
  midi: {
    all_devices: 'Alle Geräte',
  },
  memory: {
    slot_empty: 'Slot {slot}: Leer',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
});
