// 中文
I18N.addLang('zh', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: '在64键打击垫上探索音阶、和弦与声位的工具。',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 从12个调中选择',
    scale_scale: '<strong>Scale</strong> \u2014 自然音阶、和声小调、旋律小调、五声音阶、Bebop等 \u2014 共31种',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 显示所选音阶的自然和弦。点击进入Chord模式',
    chord_mode: 'Chord Mode（3步）',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 在钢琴键盘上选择根音',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 选择和弦类型（Maj, m, aug, dim, sus 等）',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 添加延伸音（9, b9, #9, 11, #11, 13, b13 等）。可多选',
    chord_onchord: '<strong>On Chord</strong> \u2014 使用"/"按钮指定分割和弦（和弦/低音）',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 省略音',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing（+1、+2 添加音）',
    voicing_inv: '<strong>Inversion</strong> \u2014 转位（Root, 1st, 2nd, 3rd）',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicing',
    voicing_box: '<strong>Voicing Box</strong> \u2014 点击切换打击垫排列方案（闪烁标记 = 有替代排列）',
    display: '显示',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 分别开关吉他指板、钢琴键盘和五线谱',
    display_label: '<strong>音名/音级</strong> \u2014 在吉他和打击垫上切换音名（C, D, E）与音级（R, 2, 3）',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 按八度移动打击垫音域',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4种预设（Jazz, Perc, Full, Gospel）',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7种预设（Rhodes, FM 等）',
    sound_fx: '<strong>效果器</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: '点击打击垫或Voicing Box即可发声',
    midi: 'MIDI',
    midi_detect: '自动检测WebMIDI兼容设备',
    midi_push: '支持Ableton Push串行MIDI输出',
    midi_chord: '根据输入音符自动识别和弦',
    color_title: '颜色说明',
    color_root: '<strong>Root</strong> \u2014 根音',
    color_scale: '<strong>Scale / Chord</strong> \u2014 音阶音·和弦音',
    color_char: '<strong>特征音</strong> \u2014 定义该音阶/和弦特征的音',
    color_3rd: '<strong>3rd</strong> \u2014 引导音（3度）',
    color_7th: '<strong>7th</strong> \u2014 引导音（7度）',
    color_tension: '<strong>Tension</strong> \u2014 延伸音',
    color_avoid: '<strong>Avoid</strong> \u2014 在和弦音上方半音的音阶音（Chord模式下）',
    color_palette: '配色方案：Okabe-Ito（色觉无障碍）',
    input_title: '吉他/钢琴输入',
    input_desc1: '点击吉他指板或钢琴键盘输入音符',
    input_desc2: '自动识别输入音符的和弦并反映到打击垫上',
    input_desc3: '<strong>Clear</strong> \u2014 清除输入，<strong>Play \u25B6</strong> \u2014 播放输入的音符',
    plain_title: 'Plain Mode',
    plain_desc1: '自由点击打击垫选择音符 \u2192 实时和弦识别',
    plain_desc2: '无理论过滤。探索 \u2192 发现 \u2192 之后再学习理论',
    plain_memory: '<strong>Memory</strong> \u2014 在16个插槽中保存和调用和弦',
    plain_export: '<strong>MIDI Export</strong> \u2014 将记忆中的和弦导出为MIDI文件',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> 按钮或 <kbd>p</kbd> 键切换',
    perform_desc1: '使用16键打击垫布局实时演奏Memory Slot和弦',
    perform_desc2: '通过键盘（4\u00D74网格）或MIDI打击垫触发',
    perform_desc3: '拖放Slot以重新排序',
    shortcut_title: '键盘快捷键',
    shortcut_scale_chord: 'Scale / Chord 模式',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 选择自然和弦（7音音阶时）',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 选择Voicing Box（循环切换替代排列）',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 切换转位（Chord模式下）',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移调根音',
    sc_omit: '<kbd>o</kbd> \u2014 切换Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 切换Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 循环Shell（off \u2192 1-3-7 \u2192 1-7-3 \u2192 off）',
    sc_drop: '<kbd>d</kbd> \u2014 循环Drop（off \u2192 Drop 2 \u2192 Drop 3 \u2192 off）',
    sc_clear: '<kbd>x</kbd> \u2014 清除和弦（Chord模式）',
    shortcut_plain: 'Plain 模式',
    sp_capture: '<kbd>c</kbd> \u2014 开始Capture / 保存到下一个插槽',
    sp_end: '<kbd>e</kbd> \u2014 结束Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 调用记忆插槽（Edit）',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移调（所有音符\u00B11）',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 转位（最低音\u21911个八度 / 最高音\u21931个八度）',
    sp_clear: '<kbd>x</kbd> \u2014 全部清除',
    sp_transfer: '<b>Chord切换</b> \u2014 将识别的和弦转移到Chord模式',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74网格触发Slot 1\u201316',
    pf_midi: 'MIDI打击垫（音符36\u201354）也可触发Slot',
    shortcut_common: '通用（所有模式）',
    sc_perform: '<kbd>p</kbd> \u2014 切换Perform视图',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 撤销Memory Slot操作（最多30步）',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 保存到Plain记忆插槽（任何模式均可）',
    sc_esc: '<kbd>Esc</kbd> \u2014 取消Voicing Box选择 / 关闭帮助',
    sc_help: '<kbd>?</kbd> \u2014 切换帮助显示',
    footer: '64 Pad Explorer V1.9 \u2014 HPS（Hardcore Pad Style）',
  },
  legend: {
    characteristic: '特征音',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: '关闭',
    slot_hint: '点击选择 \u2192 Save(c) / Shift+点击清除',
  },
  label: {
    note_name: '音名',
    degree: '音级',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
    guide: '指南',
  },
  plain: {
    status_idle: '按Capture开始构建和弦',
    status_capturing: '录入中：插槽 {slot}/16 \u2014 点击打击垫，然后按Capture保存',
    status_editing: '编辑中：插槽 {slot} \u2014 点击打击垫进行修改',
    notes_label: '音符：',
  },
  notify: {
    slot_saved: '插槽 {slot} \u2190 {chord}',
    slot_selected: '已选择插槽 {slot}',
    slot_cleared: '已清除插槽 {slot}',
    undo: '撤销',
    no_chords: '记忆插槽中没有和弦',
  },
  info: {
    note_count: '{n}个音',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: '选择根音',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: '插槽 {slot}：空',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: '\u663E\u793A\u5168\u90E8',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 指南',
    tagline: '一款在64键打击垫网格上探索音阶、和弦和声位的浏览器工具。<br>无需音源 \u2014 只需Chrome。',
    cta: '打开应用',
    features: '功能特点',
    feat_sound: '<strong>无需音源</strong> \u2014 声音直接在Chrome中播放。内置4种管风琴 + 7种电钢琴预设。包含效果器（混响、移相器、镶边、颤音、滤波器）',
    feat_input: '<strong>无需打击垫技巧</strong> \u2014 3步构建和弦。显示延伸音。直接点击打击垫输入',
    feat_detect: '<strong>和弦识别</strong> \u2014 根据点击的音符实时检测和弦名称。支持省略音、分割和弦和多个候选',
    feat_instruments: '<strong>吉他/贝斯/键盘显示</strong> \u2014 在吉他指板、贝斯和钢琴上显示和弦音。吉他指法输入自动反映到打击垫',
    feat_scales: '<strong>音阶显示</strong> \u2014 31种音阶 \u00D7 12个调。自然音阶、和声小调、旋律小调、五声音阶、Bebop等',
    feat_diatonic: '<strong>自然和弦显示</strong> \u2014 在条形图上显示所选音阶的自然和弦。点击或使用快捷键即时播放',
    feat_voicing: '<strong>声位操作</strong> \u2014 转位、Drop 2/3、Shell Voicing、Omit、Rootless。方向键控制转位，按钮切换多种指法',
    feat_memory: '<strong>和弦记忆</strong> \u2014 将喜欢的和弦保存到16个插槽。导出为MIDI文件用于DAW',
    feat_perform: '<strong>Perform模式</strong> \u2014 使用16个打击垫或电脑键盘实时演奏记忆和弦',
    feat_parent: '<strong>Available Scale反向查找</strong> \u2014 查找包含你的和弦的音阶。一目了然地查看Available Tensions。支持Practical/Diatonic排序切换',
    feat_pivot: '<strong>枢纽和弦思维</strong> \u2014 手动输入和弦后自然和弦条消失，显示该和弦可能属于的所有调。非常适合转调分析',
    feat_dimming: '<strong>Tension实用性显示</strong> \u2014 非属七和弦中，不常用的Tension（b9, #9, b13等）会以低透明度显示。仍可选择',
    feat_i18n: '<strong>多语言</strong> \u2014 9种语言（EN / JA / ZH / ES / FR / PT / DE / KO / IT）',
    screenshots: '截图',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: '选择调和音阶，在64键打击垫网格上以颜色编码显示音阶音。从自然和弦条中选择和弦。',
    ss_scale_alt: 'Scale Mode \u2014 C Major (Ionian) 音阶显示',
    ss_scale_caption: 'C Major (Ionian) \u2014 根音（橙色）、音阶音（蓝色）、特征音（黄色）',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: '3步构建和弦：Root \u2192 Quality \u2192 Tension。使用转位、Drop、Shell和Omit调整声位。使用Parent Scale面板反向查找音阶。',
    ss_chord_alt: 'Chord Mode \u2014 Dm7和弦显示及延伸音网格',
    ss_chord_caption: 'Dm7 \u2014 和弦音、3rd（粉色）、7th（绿色）。在Voicing Box中查看布局选项',
    ss_plain: '<span class="mode-badge plain">Plain</span> Plain Mode',
    ss_plain_desc: '自由点击打击垫进行实时和弦检测。无理论过滤 \u2014 探索、发现，然后学习理论。',
    ss_plain_alt: 'Plain Mode \u2014 C7实时和弦检测',
    ss_plain_caption: 'C7 \u2014 点击打击垫自动检测和弦名称。显示多个候选',
    ss_perform: 'Perform Mode',
    ss_perform_desc: '将保存的和弦放置在16个打击垫上，使用键盘或MIDI打击垫进行实时演奏。',
    ss_perform_alt: 'Perform Mode \u2014 16个插槽含和弦',
    ss_perform_caption: 'Perform Mode \u2014 C7、Fm7、G7、Am7已保存到插槽。使用4\u00D74键盘网格演奏',
    ss_parent: 'Available Scale + 枢纽和弦',
    ss_parent_desc: '反向查找包含你的和弦的音阶。可在Practical（实用性排序）和Diatonic（理论排序）之间切换。手动输入和弦时自然和弦条消失，可作为枢纽和弦进行分析。',
    ss_parent_alt: 'Parent Scale面板和吉他指板显示',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian)、C Mel.Min (Dorian b2)、F Major (Aeolian)等。显示Available Tensions',
    ss_parent_note: '\u203B 五声音阶/布鲁斯音阶属于调式（横向方法），与和弦-音阶理论（纵向对应）是不同的体系，因此不在Available Scale中涉及。在实际演奏中，五声音阶往往是首选。',
    usecases: '使用场景',
    uc1_q: '"我想找到这个和弦在打击垫上的声位"',
    uc1_a: '\u2192 在<span class="mode-badge chord">Chord</span>模式中选择Root、Quality和Tension \u2192 在Voicing Box中查看布局',
    uc2_q: '"我想在打击垫上查看课程中的音阶"',
    uc2_a: '\u2192 在<span class="mode-badge scale">Scale</span>模式中选择调和音阶。提供31种音阶',
    uc3_q: '"我想为DAW创建和弦进行"',
    uc3_a: '\u2192 将和弦保存到记忆插槽 \u2192 MIDI Export导入DAW',
    uc4_q: '"这个和弦属于哪个调？"',
    uc4_a: '\u2192 在Available Scale面板中反向查找。可切换Practical/Diatonic排序按实用性排列',
    uc7_q: '"我想找到转调的枢纽和弦"',
    uc7_a: '\u2192 在<span class="mode-badge chord">Chord</span>模式中手动输入和弦。自然和弦条消失，Available Scale显示该和弦可能属于的所有调',
    uc5_q: '"我想通过弹奏来确认和弦进行"',
    uc5_a: '\u2192 将和弦保存到记忆槽，然后用MIDI控制器或PC键盘弹奏试试',
    uc6_q: '"我想在打击垫上确认吉他和弦"',
    uc6_a: '\u2192 点击吉他指板输入 \u2192 自动显示在打击垫上 \u2192 检测和弦名称',
    quickstart: '快速入门',
    qs_modes: '3种模式',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> 显示音阶和自然和弦<br><span class="mode-badge chord">Chord</span> 3步构建和弦。可进行声位操作<br><span class="mode-badge plain">Plain</span> 自由点击打击垫 \u2192 自动检测和弦名称',
    qs_first: '开始使用',
    qs_step1: '选择一个调（例如C）',
    qs_step2: '选择一个音阶（例如Major）\u2192 音阶音出现在打击垫上',
    qs_step3: '点击自然和弦条上的和弦（例如Dm7）\u2192 显示和弦音',
    qs_step4: '点击打击垫播放声音。在Voicing Box中更改布局',
    qs_step5: '使用<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>保存喜欢的和弦',
    qs_shortcuts: '键盘快捷键',
    qs_shortcuts_desc: '按<kbd>?</kbd>查看完整快捷键列表。<br><kbd>1</kbd>\u2013<kbd>7</kbd>选择自然和弦，<kbd>\u2191</kbd><kbd>\u2193</kbd>切换转位，<kbd>\u2190</kbd><kbd>\u2192</kbd>半音移动。<br>在Perform模式中，使用<kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd>作为4\u00D74网格。',
    footer_open: '打开64 Pad Explorer',
    footer_version: '64 Pad Explorer V2.6 \u2014 HPS (Hardcore Pad Style)',
    blog_more: '在博客上了解更多 \u2192',
  },
});
