// 中文
I18N.addLang('zh', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: '在64键打击垫上探索音阶、和弦与声位的工具。',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 从12个调中选择',
    scale_scale: '<strong>Scale</strong> \u2014 自然音阶、和声小调、旋律小调、五声音阶、Bebop等 \u2014 共31种',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 显示所选音阶的自然和弦。点击进入Chord模式',
    chord_mode: 'Chord Mode（3步）',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 在钢琴键盘上选择根音',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 选择和弦类型（Maj, m, aug, dim, sus 等）',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 添加延伸音（9, b9, #9, 11, #11, 13, b13 等）。可多选',
    chord_onchord: '<strong>On Chord</strong> \u2014 使用"/"按钮指定分割和弦（和弦/低音）',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 省略音',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing（+1、+2 添加音）',
    voicing_inv: '<strong>Inversion</strong> \u2014 转位（Root, 1st, 2nd, 3rd）',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicing',
    voicing_box: '<strong>Voicing Box</strong> \u2014 点击切换打击垫排列方案（闪烁标记 = 有替代排列）',
    display: '显示',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 分别开关吉他指板、钢琴键盘和五线谱',
    display_label: '<strong>音名/音级</strong> \u2014 在吉他和打击垫上切换音名（C, D, E）与音级（R, 2, 3）',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 按八度移动打击垫音域',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4种预设（Jazz, Perc, Full, Gospel）',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7种预设（Rhodes, FM 等）',
    sound_fx: '<strong>效果器</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: '点击打击垫或Voicing Box即可发声',
    midi: 'MIDI',
    midi_detect: '自动检测WebMIDI兼容设备',
    midi_push: '支持Ableton Push串行MIDI输出',
    midi_chord: '根据输入音符自动识别和弦',
    color_title: '颜色说明',
    color_root: '<strong>Root</strong> \u2014 根音',
    color_scale: '<strong>Scale / Chord</strong> \u2014 音阶音·和弦音',
    color_char: '<strong>特征音</strong> \u2014 定义该音阶/和弦特征的音',
    color_3rd: '<strong>3rd</strong> \u2014 引导音（3度）',
    color_7th: '<strong>7th</strong> \u2014 引导音（7度）',
    color_tension: '<strong>Tension</strong> \u2014 延伸音',
    color_avoid: '<strong>Avoid</strong> \u2014 在和弦音上方半音的音阶音（Chord模式下）',
    color_palette: '配色方案：Okabe-Ito（色觉无障碍）',
    input_title: '吉他/钢琴输入',
    input_desc1: '点击吉他指板或钢琴键盘输入音符',
    input_desc2: '自动识别输入音符的和弦并反映到打击垫上',
    input_desc3: '<strong>Clear</strong> \u2014 清除输入，<strong>Play \u25B6</strong> \u2014 播放输入的音符',
    plain_title: 'Plain Mode',
    plain_desc1: '自由点击打击垫选择音符 \u2192 实时和弦识别',
    plain_desc2: '无理论过滤。探索 \u2192 发现 \u2192 之后再学习理论',
    plain_memory: '<strong>Memory</strong> \u2014 在16个插槽中保存和调用和弦',
    plain_export: '<strong>MIDI Export</strong> \u2014 将记忆中的和弦导出为MIDI文件',
    perform_title: 'Perform Mode',
    perform_desc1: '使用16键打击垫布局实时演奏Memory Slot和弦',
    perform_desc2: '通过键盘（4\u00D74网格）或MIDI打击垫触发',
    perform_desc3: '拖放Slot以重新排序',
    shortcut_title: '键盘快捷键',
    shortcut_scale_chord: 'Scale / Chord 模式',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 选择自然和弦（7音音阶时）',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 选择Voicing Box（循环切换替代排列）',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 切换转位（Chord模式下）',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移调根音',
    sc_omit: '<kbd>o</kbd> \u2014 切换Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 切换Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 循环Shell（off \u2192 1-3-7 \u2192 1-7-3 \u2192 off）',
    sc_drop: '<kbd>d</kbd> \u2014 循环Drop（off \u2192 Drop 2 \u2192 Drop 3 \u2192 off）',
    sc_clear: '<kbd>x</kbd> \u2014 清除和弦（Chord模式）',
    shortcut_plain: 'Plain 模式',
    sp_capture: '<kbd>c</kbd> \u2014 开始Capture / 保存到下一个插槽',
    sp_end: '<kbd>e</kbd> \u2014 结束Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 调用记忆插槽（Edit）',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移调（所有音符\u00B11）',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 转位（最低音\u21911个八度 / 最高音\u21931个八度）',
    sp_clear: '<kbd>x</kbd> \u2014 全部清除',
    sp_transfer: '<b>Chord切换</b> \u2014 将识别的和弦转移到Chord模式',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74网格触发Slot 1\u201316',
    pf_midi: 'MIDI打击垫（音符36\u201354）也可触发Slot',
    shortcut_common: '通用（所有模式）',
    sc_perform: '<kbd>p</kbd> \u2014 切换Perform视图',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 撤销Memory Slot操作（最多30步）',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 保存到Plain记忆插槽（任何模式均可）',
    sc_esc: '<kbd>Esc</kbd> \u2014 取消Voicing Box选择 / 关闭帮助',
    sc_help: '<kbd>?</kbd> \u2014 切换帮助显示',
    footer: '64 Pad Explorer V1.9 \u2014 HPS（Hardcore Pad Style）',
  },
  legend: {
    characteristic: '特征音',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: '关闭',
    slot_hint: '点击选择 \u2192 Save(c) / Shift+点击清除',
  },
  label: {
    note_name: '音名',
    degree: '音级',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
  },
  plain: {
    status_idle: '按Capture开始构建和弦',
    status_capturing: '录入中：插槽 {slot}/16 \u2014 点击打击垫，然后按Capture保存',
    status_editing: '编辑中：插槽 {slot} \u2014 点击打击垫进行修改',
    notes_label: '音符：',
  },
  notify: {
    slot_saved: '插槽 {slot} \u2190 {chord}',
    slot_selected: '已选择插槽 {slot}',
    slot_cleared: '已清除插槽 {slot}',
    undo: '撤销',
    no_chords: '记忆插槽中没有和弦',
  },
  info: {
    note_count: '{n}个音',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: '选择根音',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: '插槽 {slot}：空',
    midi_selected: 'MIDI: {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
});
