// Français
I18N.addLang('fr', {
  help: {
    title: '64 Pad Explorer V1.9',
    description: 'Un outil pour explorer les gammes, accords et voicings sur une grille de 64 pads.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choisir parmi 12 tonalités',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonique, mineur harmonique, mineur mélodique, pentatonique, Bebop et plus \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Affiche les accords diatoniques de la gamme sélectionnée. Cliquer pour passer en mode Chord',
    chord_mode: 'Chord Mode (3 étapes)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Sélectionner la fondamentale sur le clavier',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choisir le type d\'accord (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Ajouter des tensions (9, b9, #9, 11, #11, 13, b13, etc.). Sélection multiple possible',
    chord_onchord: '<strong>On Chord</strong> \u2014 Utiliser le bouton "/" pour les accords sur basse (accord / note de basse)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettre des notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 pour ajouter des notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Renversements (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Appuyer pour parcourir les dispositions sur le pad (badge pulsant = dispositions alternatives disponibles)',
    display: 'Affichage',
    display_inst: '<strong>Guitar / Piano / Staff</strong> \u2014 Activer/désactiver le manche de guitare, le clavier et la portée indépendamment',
    display_label: '<strong>Nom / Degré</strong> \u2014 Basculer entre noms de notes (C, D, E) et degrés (R, 2, 3) sur la guitare et les pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Décaler la tessiture des pads par octave',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 7 presets (Rhodes, FM, etc.)',
    sound_fx: '<strong>Effets</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Cliquer sur un pad ou une voicing box pour jouer le son',
    midi: 'MIDI',
    midi_detect: 'Détection automatique des appareils compatibles WebMIDI',
    midi_push: 'Support de la sortie MIDI série Ableton Push',
    midi_chord: 'Identification automatique des accords à partir des notes jouées',
    color_title: 'Légende des couleurs',
    color_root: '<strong>Root</strong> \u2014 Fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notes de la gamme / Notes de l\'accord',
    color_char: '<strong>Caractéristique</strong> \u2014 Notes qui définissent la gamme/l\'accord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (tierce)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (septième)',
    color_tension: '<strong>Tension</strong> \u2014 Notes de tension',
    color_avoid: '<strong>Avoid</strong> \u2014 Note de la gamme un demi-ton au-dessus d\'une note d\'accord (en mode Chord)',
    color_palette: 'Palette de couleurs : Okabe-Ito (accessible aux daltoniens)',
    input_title: 'Entrée Guitar / Piano',
    input_desc1: 'Cliquer sur le manche de guitare ou le clavier pour saisir des notes',
    input_desc2: 'Les accords sont identifiés automatiquement et reflétés sur le pad',
    input_desc3: '<strong>Clear</strong> \u2014 Effacer la saisie, <strong>Play \u25B6</strong> \u2014 Jouer les notes saisies',
    plain_title: 'Plain Mode',
    plain_desc1: 'Cliquer librement sur les pads pour sélectionner des notes \u2192 Identification d\'accord en temps réel',
    plain_desc2: 'Sans filtre théorique. Explorer \u2192 découvrir \u2192 apprendre la théorie ensuite',
    plain_memory: '<strong>Memory</strong> \u2014 Sauvegarder et rappeler des accords dans 16 emplacements',
    plain_export: '<strong>MIDI Export</strong> \u2014 Exporter les accords en m\u00E9moire en fichier MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> bouton ou touche <kbd>p</kbd> pour basculer',
    perform_desc1: 'Jouez les accords des Memory Slots en temps r\u00E9el avec un layout de 16 pads',
    perform_desc2: 'D\u00E9clenchez via le clavier (grille 4\u00D74) ou des pads MIDI',
    perform_desc3: 'Glissez-d\u00E9posez les Slots pour r\u00E9ordonner',
    shortcut_title: 'Raccourcis clavier',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Sélectionner un accord diatonique (gammes à 7 notes)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Sélectionner une voicing box (parcourir les alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Parcourir les renversements (mode Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposer chromatiquement la fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Activer/désactiver Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Activer/désactiver Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycler Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycler Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Effacer l\'accord (mode Chord)',
    shortcut_plain: 'Plain Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Démarrer Capture / sauvegarder dans l\'emplacement suivant',
    sp_end: '<kbd>e</kbd> \u2014 Terminer Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Rappeler un emplacement mémoire (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposition chromatique (toutes les notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Renversement (la plus basse \u21911oct / la plus haute \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Tout effacer',
    sp_transfer: '<b>Chord switch</b> \u2014 Transférer l\'accord détecté en mode Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Grille 4\u00D74 d\u00E9clenche les Slots 1\u201316',
    pf_midi: 'Les pads MIDI (notes 36\u201354) d\u00E9clenchent aussi les Slots',
    shortcut_common: 'Commun (tous les modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Basculer la vue Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annuler les Memory Slots (jusqu\u0027\u00E0 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Sauvegarder dans un emplacement Plain (depuis n\'importe quel mode)',
    sc_esc: '<kbd>Esc</kbd> \u2014 Désélectionner la voicing box / fermer l\'aide',
    sc_help: '<kbd>?</kbd> \u2014 Afficher/masquer l\'aide',
    footer: '64 Pad Explorer V1.9 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caractéristique',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Fermer',
    slot_hint: 'Cliquer pour sélectionner \u2192 Save(c) / Shift+clic pour effacer',
  },
  label: {
    note_name: 'Note',
    degree: 'Degré',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'murinaikurashi',
  },
  plain: {
    status_idle: 'Appuyer sur Capture pour commencer à construire des accords',
    status_capturing: 'Capture : Slot {slot}/16 \u2014 Cliquer sur les pads, puis Capture pour sauvegarder',
    status_editing: 'Édition : Slot {slot} \u2014 Cliquer sur les pads pour modifier',
    notes_label: 'Notes : ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} sélectionné',
    slot_cleared: 'Slot {slot} effacé',
    undo: 'Annuler',
    no_chords: 'Aucun accord dans les emplacements mémoire',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Sélectionner la fondamentale',
  },
  midi: {
    all_devices: 'Tous les appareils',
  },
  memory: {
    slot_empty: 'Slot {slot} : Vide',
    midi_selected: 'MIDI : {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS : {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play : {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  parent: {
    toggle: 'Parent Scale',
    header: 'Parent Scales ({n})',
    expand: 'Tout afficher',
  },
});
