// Deutsch
I18N.addLang('de', {
  help: {
    title: '64 Pad Explorer',
    description: 'Ein Werkzeug zum Erkunden von Skalen, Akkorden und Voicings auf einem 64-Pad-Raster.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Aus 12 Tonarten wählen',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonisch, harmonisch Moll, melodisch Moll, Pentatonik, Bebop und mehr \u2014 31 Typen',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Zeigt die diatonischen Akkorde der gewählten Skala. Klicken, um in den Chord-Modus zu wechseln',
    chord_mode: 'Chord Mode (3 Schritte)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Grundton auf der Klaviertastatur auswählen',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Akkordtyp wählen (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Tensions hinzufügen (9, b9, #9, 11, #11, 13, b13, etc.). Mehrfachauswahl möglich',
    chord_text: '<strong>Texteingabe</strong> \u2014 "/" drücken zum Fokussieren. Cm7, G7(b9,#11), Am7/G etc. direkt eingeben. Vorschläge erscheinen automatisch',
    chord_onchord: '<strong>On Chord</strong> \u2014 Die "/"-Taste für Slash-Akkorde verwenden (Akkord über Basston)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Töne weglassen',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell Voicing (+1, +2 um Töne hinzuzufügen)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Umkehrungen (Root, 1st, 2nd, 3rd)',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop Voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Antippen, um Pad-Anordnungen durchzuschalten (pulsierendes Badge = alternative Anordnungen verfügbar)',
    display: 'Anzeige',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Gitarrengriffbrett, Bass, Klaviertastatur und Notenzeile unabhängig ein-/ausschalten. Hinweis: Gitarren-/Basspositionen zeigen spielbare Griffmuster des Instruments, sie entsprechen nicht der Pad-Anordnung',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Zeigt den Quintenzirkel an. Mit der Tonartwahl verknüpft, zeigt diatonische Akkorde und Funktionen (T/SD/D). Moll-Modus-Umschaltung unterstützt',
    display_label: '<strong>Notenname / Stufe</strong> \u2014 Zwischen Notennamen (C, D, E) und Stufen (R, 2, 3) auf Gitarre und Pads umschalten',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Pad-Tonumfang um eine Oktave verschieben',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 Presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 Presets (Rhodes, FM, Clavinet, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Hüllkurvenfilter (Auto-Wah). 3 Typen: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Analoge Sättigung. Fügt dem Sound eine warme Verzerrung hinzu',
    sound_fx: '<strong>Effekte</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Pad oder Voicing Box anklicken, um den Klang abzuspielen',
    midi: 'MIDI',
    midi_detect: 'Automatische Erkennung WebMIDI-kompatibler Geräte',
    midi_push: 'Unterstützung für serielle MIDI-Ausgabe von Ableton Push',
    midi_chord: 'Automatische Akkorderkennung aus eingegebenen Noten',
    color_title: 'Farblegende',
    color_root: '<strong>Root</strong> \u2014 Grundton',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Skalentöne / Akkordtöne',
    color_char: '<strong>Charakteristisch</strong> \u2014 Töne, die die Skala/den Akkord definieren',
    color_3rd: '<strong>3rd</strong> \u2014 Guide Tone (Terz)',
    color_7th: '<strong>7th</strong> \u2014 Guide Tone (Septime)',
    color_tension: '<strong>Tension</strong> \u2014 Spannungstöne',
    color_avoid: '<strong>Avoid</strong> \u2014 Skalenton einen Halbton über einem Akkordton (im Chord-Modus)',
    color_palette: 'Farbpalette: Okabe-Ito (farbfehlsichtigkeitsfreundlich)',
    input_title: 'Guitar / Piano Eingabe',
    input_desc1: 'Gitarrengriffbrett oder Klaviertastatur anklicken, um Noten einzugeben',
    input_desc2: 'Akkorde werden automatisch aus der Eingabe erkannt und auf dem Pad dargestellt',
    input_desc3: '<strong>Clear</strong> \u2014 Eingabe löschen, <strong>Play \u25B6</strong> \u2014 Eingegebene Noten abspielen',
    input_title: 'Input Mode',
    input_desc1: 'Pads frei anklicken, um Noten auszuwählen \u2192 Echtzeit-Akkorderkennung',
    input_desc2: 'Ohne Theoriefilter. Erkunden \u2192 entdecken \u2192 Theorie danach lernen',
    input_desc3: 'Bei Akkorderkennung werden Stufenlabels (R, 3, 5, b7 usw.) auf den Pads angezeigt. Gitarre, Bass, Klavier und Notensystem aktualisieren sich automatisch',
    input_memory: '<strong>Memory</strong> \u2014 Akkorde in 16 Slots speichern und abrufen',
    input_banks: '<strong>Banks</strong> \u2014 16 Slots \u00D7 bis zu 16 Bänke. Mit <kbd>[</kbd> <kbd>]</kbd> wechseln. Duplizieren und Umbenennen unterstützt',
    input_export: '<strong>MIDI Export</strong> \u2014 Gespeicherte Akkorde als MIDI-Datei exportieren',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> Button oder <kbd>p</kbd> Taste zum Umschalten',
    perform_desc1: 'Memory Slot-Akkorde in Echtzeit mit einem 16-Pad-Layout spielen',
    perform_desc2: '\u00DCber Tastatur (4\u00D74-Raster) oder MIDI-Pads ausl\u00F6sen',
    perform_desc3: 'Slots per Drag & Drop neu anordnen',
    shortcut_title: 'Tastenkürzel',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Diatonischen Akkord auswählen (7-Ton-Skalen)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Voicing Box auswählen (Alternativen durchschalten)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Umkehrungen durchschalten (Chord-Modus)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatische Transposition des Grundtons',
    sc_omit: '<kbd>o</kbd> \u2014 Omit 5 umschalten',
    sc_rootless: '<kbd>r</kbd> \u2014 Rootless umschalten',
    sc_shell: '<kbd>s</kbd> \u2014 Shell durchschalten (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Drop durchschalten (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_clear: '<kbd>x</kbd> \u2014 Akkord löschen (Chord-Modus)',
    sc_pad_explore: '<b>Pad (Chord-Modus)</b> \u2014 Klicken zum Ein-/Ausschalten \u2014 Builder wird automatisch aktualisiert',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Capture starten / im nächsten Slot speichern',
    sp_end: '<kbd>e</kbd> \u2014 Capture beenden',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Speicherslot abrufen (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatische Transposition (alle Noten \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Umkehrung (tiefste \u21911 Okt. / höchste \u21931 Okt.)',
    sp_clear: '<kbd>x</kbd> \u2014 Alles löschen',
    sp_transfer: '<b>Chord switch</b> \u2014 Erkannten Akkord in den Chord-Modus übertragen',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74-Raster l\u00F6st Slots 1\u201316 aus',
    pf_midi: 'MIDI-Pads (Noten 36\u201354) l\u00F6sen ebenfalls Slots aus',
    shortcut_common: 'Allgemein (alle Modi)',
    sc_perform: '<kbd>p</kbd> \u2014 Perform-Ansicht umschalten',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Memory Slots r\u00FCckg\u00E4ngig machen (bis zu 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 In Input-Speicherslot speichern (aus jedem Modus)',
    sc_space: '<kbd>Space</kbd> \u2014 Aktuellen Akkord abspielen',
    sc_esc: '<kbd>Esc</kbd> \u2014 Voicing Box abwählen / Hilfe schließen',
    sc_help: '<kbd>?</kbd> \u2014 Hilfe ein-/ausblenden',
    tips_toggle: 'Tipps beim Start anzeigen',
    footer: '64 Pad Explorer V2.10 \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Charakteristisch',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Schließen',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Shift+#</b> save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Einstellungen speichern',
    sound_hint: 'Wähle ORGAN oder E.PIANO, um den Sound zu aktivieren',
    tap_to_start: 'Tippen zum Aktivieren',
    tap_pads: 'Tippe auf ein Pad zum Spielen!',
    load_vst: 'VST/AU-Plugin laden...',
    affiliate_label: '',
    circle: 'Quintenzirkel',
  },
  label: {
    note_name: 'Note',
    degree: 'Stufe',
    chord_input: 'Akkord eingeben',
    chord_hint: 'Tensions in ( ): C7(b9,#11) | dim, h=m7♭5 unterstützt',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mein Blog',
    guide: 'Anleitung',
    wishlist: 'Wunschliste',
  },
  input: {
    status_idle: 'Capture drücken, um Akkorde zu erstellen',
    status_capturing: 'Aufnahme: Slot {slot}/16 \u2014 Pads anklicken, dann Capture zum Speichern',
    status_editing: 'Bearbeitung: Slot {slot} \u2014 Pads anklicken zum Ändern',
    notes_label: 'Noten: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} ausgewählt',
    slot_cleared: 'Slot {slot} gelöscht',
    undo: 'Rückgängig',
    settings_saved: 'Einstellungen gespeichert',
    no_chords: 'Keine Akkorde in den Speicherslots',
  },
  info: {
    note_count: '{n} Töne',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Grundton auswählen',
  },
  midi: {
    all_devices: 'Alle Geräte',
  },
  memory: {
    slot_empty: 'Slot {slot}: Leer',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Klicken zum Umbenennen',
    rename: 'Umbenennen',
    duplicate: 'Duplizieren',
    delete: 'L\u00F6schen',
    rename_prompt: 'Bank-Name eingeben:',
    confirm_delete: '"{name}" l\u00F6schen?',
    limit_reached: 'Maximal 16 B\u00E4nke',
    cannot_delete_last: 'Letzte Bank kann nicht gel\u00F6scht werden',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Alle anzeigen',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Anleitung',
    tagline: 'Ein Browser-Tool zum Erkunden von Skalen, Akkorden und Voicings auf einem 64-Pad-Raster.<br>Keine Klangquelle n\u00F6tig \u2014 nur Chrome.',
    cta: 'App \u00F6ffnen',
    features: 'Funktionen',
    feat_sound: '<strong>Keine Klangquelle n\u00F6tig</strong> \u2014 Sound wird direkt in Chrome abgespielt. 4 Orgel- + 8 E-Piano-Presets integriert. Effekte (Reverb, Phaser, Flanger, Tremolo, Auto Filter) inklusive',
    feat_input: '<strong>Keine Pad-Kenntnisse erforderlich</strong> \u2014 Akkorde in 3 Schritten aufbauen. Tensions werden angezeigt. Pads direkt anklicken zur Eingabe',
    feat_text_input: '<strong>Text-Akkordeingabe</strong> \u2014 "/" drücken um Cm7, G7(b9,#11), Am7/G etc. direkt einzugeben. Autovervollständigung. Abkürzungen wie dim, h(=m7\u266D5)',
    feat_detect: '<strong>Akkorderkennung</strong> \u2014 Echtzeit-Akkorderkennung aus angeklickten T\u00F6nen. Unterst\u00FCtzt Omit, Slash-Akkorde und mehrere Vorschl\u00E4ge',
    feat_instruments: '<strong>Guitar / Bass / Keyboard-Anzeige</strong> \u2014 Zeigt Akkordt\u00F6ne auf Gitarrengriffbrett, Bass und Klavier. Eingabe \u00FCber Gitarrengriffbrett wird automatisch auf Pads \u00FCbertragen. Im Chord-Modus werden Positionen nach Grundton-Saite gruppiert',
    feat_scales: '<strong>Scale-Anzeige</strong> \u2014 31 Skalen \u00D7 12 Tonarten. Diatonisch, harmonisch Moll, melodisch Moll, Pentatonik, Bebop und mehr',
    feat_diatonic: '<strong>Diatonische Akkorde</strong> \u2014 Diatonische Akkorde werden als Leiste f\u00FCr die gew\u00E4hlte Skala angezeigt. Per Klick oder Tastenk\u00FCrzel sofort abspielen. Dreiklang/Vierklang-Umschaltung',
    feat_voicing: '<strong>Voicing-Operationen</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Pfeiltasten f\u00FCr Inversions, Buttons f\u00FCr verschiedene Fingerings',
    feat_memory: '<strong>Chord Memory</strong> \u2014 Lieblingsakkorde in 16 Slots speichern. Als MIDI-Dateien f\u00FCr die DAW exportieren',
    feat_perform: '<strong>Perform Mode</strong> \u2014 Memory-Akkorde in Echtzeit mit 16 Pads oder PC-Tastatur spielen',
    feat_parent: '<strong>Available Scale R\u00FCckw\u00E4rtssuche</strong> \u2014 Skalen finden, die den Akkord enthalten. Available Tensions auf einen Blick sehen. Practical/Diatonic-Sortierung umschaltbar',
    feat_pivot: '<strong>Pivot-Akkord-Denken</strong> \u2014 Akkord manuell eingeben und die diatonische Leiste verschwindet. Alle Tonarten, zu denen der Akkord geh\u00F6ren k\u00F6nnte, werden angezeigt. Ideal f\u00FCr Modulationsanalyse',
    feat_dimming: '<strong>Praktische Tension-Anzeige</strong> \u2014 Bei nicht-dominanten Septakkorden werden ungew\u00F6hnliche Tensions (b9, #9, b13 usw.) abgedimmt. Weiterhin ausw\u00E4hlbar',
    feat_i18n: '<strong>Mehrsprachig</strong> \u2014 9 Sprachen (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshots',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Tonart und Skala w\u00E4hlen, um Skalent\u00F6ne farbcodiert auf dem 64-Pad-Raster zu sehen. Akkorde aus der diatonischen Leiste w\u00E4hlen.',
    ss_scale_alt: 'Scale Mode \u2014 C-Dur (Ionisch) Skala-Anzeige',
    ss_scale_caption: 'C-Dur (Ionisch) \u2014 Root (orange), Skalent\u00F6ne (blau), charakteristische T\u00F6ne (gelb)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Akkorde in 3 Schritten aufbauen: Root \u2192 Quality \u2192 Tension. Voicings mit Inversions, Drop, Shell und Omit anpassen. Im Parent Scale-Panel Skalen r\u00FCckw\u00E4rts suchen.',
    ss_chord_alt: 'Chord Mode \u2014 Dm7-Akkord mit Tension-Raster',
    ss_chord_caption: 'Dm7 \u2014 Akkordt\u00F6ne, 3rd (rosa), 7th (gr\u00FCn). Layout-Optionen in den Voicing Boxes pr\u00FCfen',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Pads frei anklicken f\u00FCr Echtzeit-Akkorderkennung. Verstehe Akkorde auch ohne Theoriekenntnisse.',
    ss_input_alt: 'Input Mode \u2014 C7 Echtzeit-Akkorderkennung',
    ss_input_caption: 'C7 \u2014 Pads anklicken f\u00FCr automatische Akkorderkennung. Mehrere Vorschl\u00E4ge werden angezeigt',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Gespeicherte Akkorde auf 16 Pads f\u00FCr Echtzeit-Performance per Tastatur oder MIDI-Pads platzieren.',
    ss_perform_alt: 'Perform Mode \u2014 16 Slots mit Akkorden',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 in Slots gespeichert. Abspielen \u00FCber 4\u00D74-Tastatur-Raster',
    ss_parent: 'Available Scale + Pivot-Akkord',
    ss_parent_desc: 'Skalen r\u00FCckw\u00E4rts suchen, die den Akkord enthalten. Zwischen Practical (nach Nutzbarkeit) und Diatonic (nach Theorie) Sortierung umschalten. Bei manueller Akkordeingabe verschwindet die diatonische Leiste f\u00FCr Pivot-Akkord-Analyse.',
    ss_parent_alt: 'Parent Scale-Panel und Gitarrengriffbrett-Anzeige',
    ss_parent_caption: 'Dm7 \u2192 C-Dur (Dorisch), C Mel.Min (Dorisch b2), F-Dur (\u00C4olisch) usw. Available Tensions angezeigt',
    ss_parent_note: '\u203B Pentatonische/Blues-Skalen sind modal (horizontaler Ansatz) und geh\u00F6ren zu einem anderen System als die Akkord-Skalen-Theorie (vertikale Zuordnung), daher sind sie nicht in Available Scale enthalten. In der Praxis ist die Pentatonik oft die erste Wahl.',
    usecases: 'Anwendungsf\u00E4lle',
    uc1_q: '\u201EIch m\u00F6chte herausfinden, wie ich diesen Akkord auf den Pads greifen kann\u201C',
    uc1_a: '\u2192 Root, Quality und Tension im <span class="mode-badge chord">Chord</span>-Modus w\u00E4hlen \u2192 Layouts in den Voicing Boxes pr\u00FCfen',
    uc2_q: '\u201EIch m\u00F6chte eine Skala aus meinem Unterricht auf den Pads sehen\u201C',
    uc2_a: '\u2192 Tonart und Skala im <span class="mode-badge scale">Scale</span>-Modus w\u00E4hlen. 31 Skalen verf\u00FCgbar',
    uc3_q: '\u201EIch m\u00F6chte eine Akkordfolge f\u00FCr meine DAW erstellen\u201C',
    uc3_a: '\u2192 Akkorde in Memory Slots speichern \u2192 MIDI Export zum Import in die DAW',
    uc4_q: '\u201EZu welcher Tonart geh\u00F6rt dieser Akkord?\u201C',
    uc4_a: '\u2192 R\u00FCckw\u00E4rtssuche im Available Scale-Panel. Zwischen Practical/Diatonic-Sortierung umschalten',
    uc7_q: '\u201EIch m\u00F6chte Pivot-Akkorde f\u00FCr die Modulation finden\u201C',
    uc7_a: '\u2192 Akkord manuell im <span class="mode-badge chord">Chord</span>-Modus eingeben. Die diatonische Leiste verschwindet und Available Scale zeigt alle m\u00F6glichen Tonarten',
    uc5_q: '\u201EIch m\u00F6chte Akkordfolgen durch Spielen \u00FCberpr\u00FCfen\u201C',
    uc5_a: '\u2192 Akkorde in Memory-Slots speichern, dann mit MIDI-Controller oder PC-Tastatur spielen',
    uc6_q: '\u201EIch m\u00F6chte Gitarrenakkorde auf den Pads \u00FCberpr\u00FCfen\u201C',
    uc6_a: '\u2192 Gitarrengriffbrett anklicken zur Eingabe \u2192 Automatisch auf Pads dargestellt \u2192 Akkordname erkannt',
    quickstart: 'Schnellstart',
    qs_modes: '3 Modi',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Skalen und diatonische Akkorde anzeigen<br><span class="mode-badge chord">Chord</span> Akkorde in 3 Schritten aufbauen. Voicing-Operationen verf\u00FCgbar<br><span class="mode-badge input">Input</span> Pads frei anklicken \u2192 Akkordnamen automatisch erkennen',
    qs_first: 'Erste Schritte',
    qs_step1: 'Tonart w\u00E4hlen (z.B. C)',
    qs_step2: 'Skala w\u00E4hlen (z.B. Major) \u2192 Skalent\u00F6ne erscheinen auf den Pads',
    qs_step3: 'Einen Akkord auf der diatonischen Leiste anklicken (z.B. Dm7) \u2192 Akkordt\u00F6ne werden angezeigt',
    qs_step4: 'Pads anklicken, um T\u00F6ne zu h\u00F6ren. Layouts in den Voicing Boxes \u00E4ndern',
    qs_step5: 'Lieblingsakkorde mit <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> speichern',
    qs_shortcuts: 'Tastenk\u00FCrzel',
    qs_shortcuts_desc: '<kbd>?</kbd> dr\u00FCcken f\u00FCr die vollst\u00E4ndige Tastenk\u00FCrzel-Liste.<br><kbd>Space</kbd> zum Akkord abspielen. <kbd>1</kbd>\u2013<kbd>7</kbd> f\u00FCr diatonische Akkorde, <kbd>\u2191</kbd><kbd>\u2193</kbd> f\u00FCr Inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> f\u00FCr chromatische Bewegung.<br>Im Perform Mode <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> als 4\u00D74-Raster verwenden.',
    footer_open: '64 Pad Explorer \u00F6ffnen',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Mehr erfahren im Blog \u2192',
    version_history: 'Versionshistorie',
    vh_324: '<b>V3.24</b> \u2014 Clavinet-Presets hinzugef\u00FCgt (2 in E.PIANO). Auto Filter (H\u00FCllkurvenfilter / Auto-Wah) Effekt hinzugef\u00FCgt',
    vh_323: '<b>V3.23</b> \u2014 Text-Akkordeingabe mit Autovervollst\u00E4ndigung. "/" zum Fokussieren, Abk\u00FCrzungen (dim, h=m7\u266D5), Sortierung nach Tensions',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Diatonischer Dreiklang/Vierklang-Umschalter. Gitarren-/Bass-Positionen nach Grundton-Saite gruppiert',
    vh_37: '<b>V3.7</b> \u2014 Voicing-Position beibehalten (Fingersatz-Form bei chromatischer Bewegung automatisch beibehalten). Pad-Raster, Notenzeile und Akkorderkennung w\u00E4hrend der Wiedergabe. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 MIDI-Datei-Wiedergabe \u2192 Pad-Beleuchtung (Timeline-Wiedergabe, Akkordname-Anzeige, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 E.PIANO-Sampler (Rhodes Mark I). 7 EP-Presets. Sound AN/AUS-Schalter. iPad-Unterst\u00FCtzung',
    vh_31: '<b>V3.1</b> \u2014 Anschlagdynamik (4 Parameter + Kurvenvisualisierung). Push 3 Oktavtasten-Unterst\u00FCtzung. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 Mehrere Speicherb\u00E4nke (16 Slots \u00D7 bis zu 16 B\u00E4nke, Wechseln/Duplizieren/Umbenennen)',
    vh_218: '<b>V2.18</b> \u2014 Alle Einstellungen automatisch speichern/wiederherstellen (Tonart/Skala/Sound/MIDI/Speicher)',
    vh_213: '<b>V2.13</b> \u2014 Instrument-Skalen\u00FCberlagerung (Gitarre/Bass/Piano zeigen Available Scale). Pad-Stufenbezeichnungen. Oktavgekoppelte Wiedergabe',
    vh_27: '<b>V2.7</b> \u2014 Tension-Erg\u00E4nzungsmodus (Pad/Gitarre/Bass/Keyboard-Akkordaufbau \u2192 Available Scale-Filterung)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, Skalen-Overlay auf Pads)',
    vh_19: '<b>V1.9</b> \u2014 9 Sprachen',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 Speicherslots, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Plain Mode, MIDI/CHS-Export',
    vh_10: '<b>V1.0</b> \u2014 Erstver\u00F6ffentlichung (Skala/Akkord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6.S R',
    root_5: '5.S R',
    root_4: '4.S R',
    root_3: '3.S R',
    root_2: '2.S R',
    open: 'Offen',
    all: 'Alle',
  },
  tips: [
    'Drücke C um den aktuellen Akkord im Memory zu speichern',
    'Opt+1~V speichert direkt in einen Slot (16 Tasten: 1234 QWER ASDF ZXCV)',
    'Shift+Klick auf einen Memory-Slot zum Löschen',
    'Opt+Ziehen zum Kopieren eines Slots',
    'Drücke S für Shell Voicings (1-3-7 / 1-7-3)',
    'Shift+D wechselt Drop 2 / Drop 3',
    'Shift+G zeigt das Gitarrengriffbrett',
    'Shift+C zeigt den Quintenzirkel',
    'Tab wechselt zwischen Scale / Chord / Input',
    'Leertaste spielt die aktuelle Tonleiter oder den Akkord',
    'Exportiere alle Memory-Slots als MIDI-Datei',
    'Verbinde einen MIDI-Controller zum Spielen',
    'Pfeiltasten ↓↑ ändern die Akkordumkehrung',
    'Drücke R für Rootless Voicing',
    'Drücke O um die Quinte wegzulassen',
    'Shift+S zeigt die Notenzeile',
    'Das Speicher-Symbol bewahrt alle Einstellungen',
    '[ ] wechselt Memory-Bänke — verwalte mehrere Songs',
    'Perform-Modus: Akkorde mit Tastatur (1234 / QWER / ASDF / ZXCV) oder MIDI-Pads auslösen',
    'Drücke / im Chord-Modus um Akkordnamen einzugeben (z.B. Cm7, G7(b9,#11))',
  ],
  tips_off: 'Tipps ausblenden',
});
