// Español
I18N.addLang('es', {
  help: {
    title: '64 Pad Explorer',
    description: 'Herramienta para explorar escalas, acordes y voicings en una cuadrícula de 64 pads.',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Elige entre 12 tonalidades',
    scale_scale: '<strong>Scale</strong> \u2014 Diatónica, Menor Armónica, Menor Melódica, Pentatónica, Bebop y más \u2014 31 tipos',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Muestra los acordes diatónicos de la escala seleccionada. Haz clic para entrar en Chord Mode',
    chord_mode: 'Chord Mode (3 pasos)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selecciona la nota raíz en el teclado de piano',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Elige el tipo de acorde (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Añade tensiones (9, b9, #9, 11, #11, 13, b13, etc.). Selección múltiple OK',
    chord_text: '<strong>Entrada de texto</strong> \u2014 Pulsa "/" para enfocar. Escribe Cm7, G7(b9,#11), Am7/G etc. directamente. Aparecen sugerencias',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usa el botón "/" para acordes con bajo alterno (acorde sobre nota de bajo)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omitir notas',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 para añadir notas)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversiones (Root, 1st, 2nd, 3rd)',
    inv_1: '1.ª inversión',
    inv_2: '2.ª inversión',
    inv_3: '3.ª inversión',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Toca para recorrer las opciones de disposición en el pad (badge pulsante = disposiciones alternativas disponibles)',
    display: 'Visualización',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Activa/desactiva el diapasón de guitarra, el bajo, el teclado de piano y la partitura de forma independiente. Nota: Las posiciones de guitarra/bajo muestran digitaciones tocables del instrumento, no corresponden a la disposición del pad',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Muestra el círculo de quintas. Vinculado a la selección de tonalidad, mostrando acordes diatónicos y funciones (T/SD/D). Compatible con cambio a modo menor',
    display_label: '<strong>Nombre de nota / Grado</strong> \u2014 Alterna entre nombres de notas (C, D, E) y grados (R, 2, 3) en la guitarra y los pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Desplaza el rango de los pads por octava',
    sound: 'Sound',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 presets (Rhodes, FM, Clavinet, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro envolvente (Auto-Wah). 3 tipos: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Saturación analógica. Añade una cálida distorsión al sonido',
    sound_fx: '<strong>Efectos</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Tremolo, Speed, Volume',
    sound_play: 'Haz clic en un pad o en el Voicing Box para reproducir sonido',
    midi: 'MIDI',
    midi_detect: 'Detecta automáticamente dispositivos compatibles con WebMIDI',
    midi_push: 'Compatible con la salida MIDI serial de Ableton Push',
    midi_chord: 'Identifica acordes automáticamente a partir de las notas de entrada',
    color_title: 'Leyenda de colores',
    color_root: '<strong>Root</strong> \u2014 Nota raíz',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notas de la escala / Notas del acorde',
    color_char: '<strong>Nota característica</strong> \u2014 Notas que definen la escala/el acorde',
    color_3rd: '<strong>3rd</strong> \u2014 Nota guía (3.ª)',
    color_7th: '<strong>7th</strong> \u2014 Nota guía (7.ª)',
    color_tension: '<strong>Tension</strong> \u2014 Notas de tensión',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota de la escala a un semitono por encima de una nota del acorde (en Chord Mode)',
    color_palette: 'Paleta de colores: Okabe-Ito (accesible para distintas visiones del color)',
    input_title: 'Entrada por Guitar / Piano',
    input_desc1: 'Haz clic en el diapasón de guitarra o en el teclado de piano para ingresar notas',
    input_desc2: 'Los acordes se identifican automáticamente a partir de la entrada y se reflejan en el pad',
    input_desc3: '<strong>Clear</strong> \u2014 Borrar entrada, <strong>Play \u25B6</strong> \u2014 Reproducir las notas ingresadas',
    input_title: 'Input Mode',
    input_desc1: 'Haz clic en los pads libremente para seleccionar notas \u2192 Identificación de acordes en tiempo real',
    input_desc2: 'Sin filtro de teor\u00EDa. Explora \u2192 descubre \u2192 aprende la teor\u00EDa despu\u00E9s',
    input_desc3: 'Al detectar un acorde, se muestran etiquetas de grado (R, 3, 5, b7, etc.) en los pads. Guitarra, bajo, piano y pentagrama se actualizan autom\u00E1ticamente',
    input_memory: '<strong>Memory</strong> \u2014 Guarda y recupera acordes en 16 ranuras',
    input_banks: '<strong>Banks</strong> \u2014 16 ranuras \u00D7 hasta 16 bancos. Cambiar con <kbd>[</kbd> <kbd>]</kbd>. Duplicar y renombrar compatible',
    input_export: '<strong>MIDI Export</strong> \u2014 Exporta los acordes de memoria como archivo MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> botón o tecla <kbd>p</kbd> para cambiar',
    perform_desc1: 'Toca los acordes de los Memory Slots en tiempo real con un layout de 16 pads',
    perform_desc2: 'Activa mediante teclado (cuadr\u00EDcula 4\u00D74) o pads MIDI',
    perform_desc3: 'Arrastra y suelta Slots para reordenar',
    shortcut_title: 'Atajos de teclado',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Seleccionar acorde diatónico (escalas de 7 notas)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Seleccionar Voicing Box (recorre las alternativas)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Recorrer inversiones (Chord Mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transporte cromático de la raíz',
    sc_omit: '<kbd>o</kbd> \u2014 Alternar Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Alternar Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclar Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclar Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: '<kbd>v</kbd> \u2014 Reflejar en pad / ciclar diseño (estilo guitarra \u2194 compacto)',
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Ciclar posición de guitarra (anterior / siguiente)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Cambiar posición del bajo (anterior / siguiente)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON / siguiente voicing, <kbd>Shift</kbd>+<kbd>t</kbd> \u2014 anterior',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON / siguiente voicing, <kbd>Shift</kbd>+<kbd>k</kbd> \u2014 anterior',
    sc_clear: '<kbd>x</kbd> \u2014 Borrar acorde (Chord Mode)',
    sc_pad_explore: '<b>Pad (modo Chord)</b> \u2014 Clic para activar/desactivar nota \u2014 constructor actualizado automáticamente',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Iniciar Capture / guardar en la siguiente ranura',
    sp_end: '<kbd>e</kbd> \u2014 Finalizar Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recuperar ranura de memoria (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transporte cromático (todas las notas \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversión (nota más grave \u21911oct / nota más aguda \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Borrar todo',
    sp_transfer: '<b>Cambiar a Chord</b> \u2014 Transferir el acorde detectado a Chord Mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Cuadr\u00EDcula 4\u00D74 activa Slots 1\u201316',
    pf_midi: 'Los pads MIDI (notas 36\u201354) tambi\u00E9n activan Slots',
    shortcut_common: 'Com\u00FAn (Todos los modos)',
    sc_perform: '<kbd>p</kbd> \u2014 Alternar vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Deshacer Memory Slots (hasta 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Guardar en ranura de memoria Input (desde cualquier modo)',
    sc_space: '<kbd>Space</kbd> \u2014 Reproducir acorde actual',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deseleccionar Voicing Box / cerrar Ayuda',
    sc_help: '<kbd>?</kbd> \u2014 Mostrar/ocultar Ayuda',
    tips_toggle: 'Mostrar consejos al inicio',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Nota característica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Cerrar',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Shift+#</b> save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Guardar configuración',
    sound_hint: 'Selecciona un preset de sonido para activar el audio',
    tap_to_start: 'Toca para activar el sonido',
    tap_pads: '¡Toca cualquier pad para tocar!',
    load_vst: 'Cargar plugin VST/AU...',
    affiliate_label: '',
    circle: 'Círculo',
    help: 'Ayuda',
    oct_down: 'Bajar octava',
    oct_up: 'Subir octava',
    toggle_guitar: 'Mostrar/ocultar diapas\u00F3n de guitarra (Shift+G)',
    toggle_bass: 'Mostrar/ocultar diapas\u00F3n de bajo (Shift+B)',
    toggle_piano: 'Mostrar/ocultar teclado de piano (Shift+P)',
    mode_scale: 'Modo Scale \u2014 ver notas de la escala en los pads (Tab para cambiar)',
    mode_chord: 'Modo Chord \u2014 construir acordes con voicings (Tab para cambiar)',
    mode_input: 'Modo Input \u2014 tocar pads libremente para detectar acordes (Tab para cambiar)',
    play_chord: 'Reproducir acorde actual (Space)',
    toggle_staff: 'Mostrar/ocultar partitura (Shift+S)',
    toggle_circle: 'Mostrar/ocultar c\u00EDrculo de quintas (Shift+C)',
    toggle_sound: 'Mostrar/ocultar controles de sonido',
    sound_mute: 'Sonido ON/OFF',
    sound_expand: 'Mostrar/ocultar ajustes detallados de sonido',
    input_keys_disabled: 'La selección de tonalidad no se usa en el modo Input',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grado',
    chord_input: 'Introducir acorde',
    chord_hint: 'Tensiones en ( ): C7(b9,#11) | dim, h=m7♭5 soportados',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mi Blog',
    guide: 'Gu\u00EDa',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Pulsa Capture para empezar a construir acordes',
    status_capturing: 'Capturando: Ranura {slot}/16 \u2014 Haz clic en los pads y luego Capture para guardar',
    status_editing: 'Editando: Ranura {slot} \u2014 Haz clic en los pads para modificar',
    notes_label: 'Notas: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Ranura {slot} seleccionada',
    slot_cleared: 'Ranura {slot} borrada',
    undo: 'Deshacer',
    settings_saved: 'Configuración guardada',
    no_chords: 'No hay acordes en las ranuras de memoria',
  },
  info: {
    note_count: '{n} notas',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Selecciona la raíz',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Ranura {slot}: Vacía',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
  },
  bank: {
    click_rename: 'Clic para renombrar',
    rename: 'Renombrar',
    duplicate: 'Duplicar',
    delete: 'Eliminar',
    rename_prompt: 'Nombre del banco:',
    confirm_delete: '\u00BFEliminar "{name}"?',
    limit_reached: 'M\u00E1ximo 16 bancos',
    cannot_delete_last: 'No se puede eliminar el \u00FAltimo banco',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostrar todo',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Gu\u00EDa',
    tagline: 'Una herramienta de navegador para explorar escalas, acordes y voicings en una cuadr\u00EDcula de 64 pads.<br>No necesitas fuente de sonido \u2014 solo Chrome.',
    cta: 'Abrir App',
    features: 'Caracter\u00EDsticas',
    feat_sound: '<strong>Sin fuente de sonido necesaria</strong> \u2014 El sonido se reproduce directamente en Chrome. 4 presets de \u00F3rgano + 8 de piano el\u00E9ctrico integrados. Efectos incluidos (drive, reverb, phaser, flanger, tr\u00E9molo, lo cut, hi cut, auto filter)',
    feat_input: '<strong>Sin habilidades de pad necesarias</strong> \u2014 Construye acordes en 3 pasos. Tensiones mostradas. Haz clic en los pads para ingresar directamente',
    feat_text_input: '<strong>Entrada de texto de acordes</strong> \u2014 Pulsa "/" para escribir Cm7, G7(b9,#11), Am7/G etc. directamente. Autocompletado. Abreviaturas como dim, h(=m7\u266D5)',
    feat_detect: '<strong>Detecci\u00F3n de acordes</strong> \u2014 Detecci\u00F3n en tiempo real del nombre del acorde a partir de las notas clicadas. Soporta omit, acordes con bajo alterno y m\u00FAltiples candidatos',
    feat_instruments: '<strong>Visualizaci\u00F3n de Guitar / Bass / Keyboard</strong> \u2014 Muestra las notas del acorde en el diapas\u00F3n de guitarra, bajo y piano. La entrada de digitaci\u00F3n de guitarra se refleja autom\u00E1ticamente en los pads. En modo Chord, las posiciones se agrupan por cuerda ra\u00EDz',
    feat_scales: '<strong>Visualizaci\u00F3n de escalas</strong> \u2014 31 escalas \u00D7 12 tonalidades. Diat\u00F3nica, Menor Arm\u00F3nica, Menor Mel\u00F3dica, Pentat\u00F3nica, Bebop y m\u00E1s',
    feat_diatonic: '<strong>Visualizaci\u00F3n de acordes diat\u00F3nicos</strong> \u2014 Los acordes diat\u00F3nicos se muestran en una barra para la escala seleccionada. Haz clic o usa atajos para reproducir al instante. Alterna entre tr\u00EDadas y t\u00E9tradas',
    feat_voicing: '<strong>Operaciones de voicing</strong> \u2014 Inversiones, Drop 2/3, Shell Voicing, Omit, Rootless. Teclas de flechas para inversiones, botones para m\u00FAltiples digitaciones',
    feat_memory: '<strong>Memoria de acordes</strong> \u2014 Guarda tus acordes favoritos en 16 ranuras. Exporta como archivos MIDI para tu DAW',
    feat_perform: '<strong>Modo Perform</strong> \u2014 Toca los acordes de memoria en tiempo real usando 16 pads o tu teclado de PC',
    feat_parent: '<strong>B\u00FAsqueda inversa de Available Scale</strong> \u2014 Encuentra escalas que contengan tu acorde. Ve los Available Tensions de un vistazo. Alternancia Practical/Diatonic',
    feat_pivot: '<strong>Pensamiento de acorde pivote</strong> \u2014 Ingresa un acorde manualmente y la barra diat\u00F3nica desaparece, mostrando todas las tonalidades a las que tu acorde podr\u00EDa pertenecer. Ideal para an\u00E1lisis de modulaci\u00F3n',
    feat_dimming: '<strong>Visualizaci\u00F3n pr\u00E1ctica de Tensions</strong> \u2014 Para acordes de 7\u00AA no dominante, las tensiones poco comunes (b9, #9, b13, etc.) se muestran atenuadas. A\u00FAn seleccionables',
    feat_i18n: '<strong>Multiling\u00FCe</strong> \u2014 9 idiomas (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Capturas de pantalla',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Selecciona una tonalidad y escala para ver las notas de la escala codificadas por color en la cuadr\u00EDcula de 64 pads. Elige acordes de la barra diat\u00F3nica.',
    ss_scale_alt: 'Scale Mode \u2014 Visualizaci\u00F3n de la escala C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Ra\u00EDz (naranja), notas de escala (azul), notas caracter\u00EDsticas (amarillo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construye acordes en 3 pasos: Root \u2192 Quality \u2192 Tension. Ajusta voicings con inversiones, Drop, Shell y Omit. Usa el panel Parent Scale para b\u00FAsqueda inversa de escalas.',
    ss_chord_alt: 'Chord Mode \u2014 Visualizaci\u00F3n del acorde Dm7 con cuadr\u00EDcula de tensiones',
    ss_chord_caption: 'Dm7 \u2014 Notas del acorde, 3rd (rosa), 7th (verde). Consulta las opciones de disposici\u00F3n en los Voicing Boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Haz clic en los pads libremente para detecci\u00F3n de acordes en tiempo real. Entiende los acordes incluso sin conocer la teor\u00EDa.',
    ss_input_alt: 'Input Mode \u2014 Detecci\u00F3n en tiempo real de C7',
    ss_input_caption: 'C7 \u2014 Haz clic en los pads para detectar autom\u00E1ticamente nombres de acordes. Se muestran m\u00FAltiples candidatos',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Coloca los acordes guardados en 16 pads para interpretaci\u00F3n en tiempo real usando teclado o pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 ranuras con acordes',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 guardados en ranuras. Toca usando la cuadr\u00EDcula 4\u00D74 del teclado',
    ss_parent: 'Available Scale + Acorde Pivote',
    ss_parent_desc: 'B\u00FAsqueda inversa de escalas que contengan tu acorde. Alterna entre ordenamiento Practical (por usabilidad) y Diatonic (por teor\u00EDa). La entrada manual de acordes oculta la barra diat\u00F3nica para an\u00E1lisis de acordes pivote.',
    ss_parent_alt: 'Panel Parent Scale y visualizaci\u00F3n del diapas\u00F3n de guitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Se muestran los Available Tensions',
    ss_parent_note: '\u203B Las escalas pentat\u00F3nicas/blues son modales (enfoque horizontal) y pertenecen a un sistema diferente de la teor\u00EDa de escalas por acorde (mapeo vertical), por lo que no se incluyen en Available Scale. En la pr\u00E1ctica, la pentat\u00F3nica suele ser la primera opci\u00F3n.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'Funciones de Voicing exclusivas de HPS',
    ss_hps_voicing_intro: 'Los miembros de HPS tienen acceso a 3 herramientas de voicing. Cada una ofrece voicings desde un instrumento y clasificaci\u00F3n diferentes, y todos pueden reflejarse en la disposici\u00F3n de 64 pads con "To Pad".',
    ss_tasty: 'TASTY Voicing \u2014 Clasificado por nota superior',
    ss_tasty_desc: '129 voicings sofisticados mostrados como arrays de grados. Selecciona un acorde, pulsa <kbd>T</kbd> para activar y pulsa de nuevo para recorrer los voicings. Selecci\u00F3n autom\u00E1tica de la posici\u00F3n \u00F3ptima en los pads.',
    ss_tasty_target: 'Objetivo: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'El \u00E1rea de informaci\u00F3n muestra el orden de apilamiento de grados (ej.: <code>m9 (b3-b7-9-5-1)</code>). Esta es la estructura del voicing \u2014 qu\u00E9 notas se apilan de abajo hacia arriba.',
    ss_tasty_labels_title: 'Significado de las etiquetas',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Se omite la fundamental (1er grado). Com\u00FAn en jazz/R&B/neo-soul donde el bajista cubre la fundamental.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 Se omite la 5ta. La 5ta tiene poco car\u00E1cter tonal, por lo que se reemplaza con una tensi\u00F3n para un sonido m\u00E1s rico.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 Se omite la 3ra. Se acerca a un sonido sus o Quartal.',
    ss_tasty_ops_title: 'Controles',
    ss_stock: 'STOCK Voicing \u2014 Colecci\u00F3n de Voicings de piano',
    ss_stock_desc: '154 voicings de piano de materiales educativos, mostrados en notaci\u00F3n de grados. Cubre Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Visualiza las posiciones reales en la pantalla de teclado y usa "To Pad" para mapear a la disposici\u00F3n de pads.',
    ss_stock_ops_title: 'Controles',
    ss_guitar_pos: 'Guitar Position \u2014 Voicings de guitarra',
    ss_guitar_pos_desc: 'Calcula autom\u00E1ticamente las posiciones de acordes en el diapas\u00F3n de guitarra. Haz clic en el diapas\u00F3n para entrada manual. Usa <kbd>V</kbd> "To Pad" para convertir los voicings de guitarra a disposici\u00F3n de pads. Elige entre disposici\u00F3n estilo guitarra (1 nota por fila) y compacta.',
    usecases: 'Casos de uso',
    uc1_q: '"Quiero encontrar c\u00F3mo hacer el voicing de este acorde en los pads"',
    uc1_a: '\u2192 Selecciona Root, Quality y Tension en el modo <span class="mode-badge chord">Chord</span> \u2192 Consulta las disposiciones en los Voicing Boxes',
    uc2_q: '"Quiero ver una escala de mi lecci\u00F3n en los pads"',
    uc2_a: '\u2192 Selecciona tonalidad y escala en el modo <span class="mode-badge scale">Scale</span>. 31 escalas disponibles',
    uc3_q: '"Quiero crear una progresi\u00F3n de acordes para mi DAW"',
    uc3_a: '\u2192 Guarda acordes en las ranuras de memoria \u2192 MIDI Export para importar en tu DAW',
    uc4_q: '"\u00BFA qu\u00E9 tonalidad pertenece este acorde?"',
    uc4_a: '\u2192 B\u00FAsqueda inversa en el panel Available Scale. Alterna entre ordenamiento Practical/Diatonic',
    uc7_q: '"Quiero encontrar acordes pivote para modulaci\u00F3n"',
    uc7_a: '\u2192 Ingresa un acorde manualmente en el modo <span class="mode-badge chord">Chord</span>. La barra diat\u00F3nica desaparece y Available Scale muestra todas las tonalidades posibles',
    uc5_q: '"Quiero comprobar progresiones de acordes toc\u00E1ndolos"',
    uc5_a: '\u2192 Guarda los acordes en los slots de memoria y t\u00F3calos con un controlador MIDI o el teclado del PC',
    uc6_q: '"Quiero verificar acordes de guitarra en los pads"',
    uc6_a: '\u2192 Haz clic en el diapas\u00F3n de guitarra para ingresar \u2192 Se muestra autom\u00E1ticamente en los pads \u2192 Se detecta el nombre del acorde',
    uc8_q: '"Quiero aprender voicings profesionales"',
    uc8_a: '\u2192 Construye un acorde en modo <span class="mode-badge chord">Chord</span>, luego pulsa <kbd>T</kbd> para TASTY (clasificaci\u00F3n por nota superior) o <kbd>K</kbd> para STOCK (voicings de piano). Visualiza con notaci\u00F3n de grados, usa "To Pad" para mapear a los pads, guarda en memoria y exporta a DAW',
    quickstart: 'Inicio r\u00E1pido',
    qs_modes: '3 modos',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Muestra escalas y acordes diat\u00F3nicos<br><span class="mode-badge chord">Chord</span> Construye acordes en 3 pasos. Operaciones de voicing disponibles<br><span class="mode-badge input">Input</span> Haz clic en los pads libremente \u2192 Detecci\u00F3n autom\u00E1tica de nombres de acordes',
    qs_first: 'Primeros pasos',
    qs_step1: 'Elige una tonalidad (ej. C)',
    qs_step2: 'Elige una escala (ej. Major) \u2192 Las notas de la escala aparecen en los pads',
    qs_step3: 'Haz clic en un acorde de la barra diat\u00F3nica (ej. Dm7) \u2192 Se muestran las notas del acorde',
    qs_step4: 'Haz clic en los pads para reproducir sonidos. Cambia disposiciones en los Voicing Boxes',
    qs_step5: 'Guarda tus acordes favoritos con <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Atajos de teclado',
    qs_shortcuts_desc: 'Pulsa <kbd>?</kbd> para ver la lista completa de atajos.<br><kbd>Space</kbd> para reproducir acorde. <kbd>1</kbd>\u2013<kbd>7</kbd> para acordes diat\u00F3nicos, <kbd>\u2191</kbd><kbd>\u2193</kbd> para inversiones, <kbd>\u2190</kbd><kbd>\u2192</kbd> para movimiento crom\u00E1tico.<br>En el modo Perform, usa <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> como cuadr\u00EDcula 4\u00D74.',
    footer_open: 'Abrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'M\u00E1s informaci\u00F3n en el blog \u2192',
    // Iconos del encabezado
    header_icons: 'Iconos del encabezado',
    header_icons_desc: 'Tres botones de icono en la esquina superior derecha.',
    icon_save: '<strong>\uD83D\uDCBE Guardar</strong> \u2014 Guarda la configuración actual (sonido, efectos, opciones de visualización, etc.) en el navegador. Se restaura automáticamente en la próxima visita',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 Explora 11 tutoriales interactivos. Aprende cada función paso a paso',
    icon_help: '<strong>? Ayuda</strong> \u2014 Muestra atajos de teclado, historial de versiones y descripción de modos. También se abre con la tecla <kbd>?</kbd>',
    sound_panel: 'Panel de sonido',
    sound_panel_desc: 'Selecciona presets de sonido y ajusta los efectos. Haz clic en el botón \u25B6 para expandir el panel.',
    sound_presets: 'Presets de sonido',
    sound_presets_desc: 'Elige entre ORGAN (4 tipos) y E.PIANO (8 tipos: Rhodes, FM EP, Clavinet, Sampler).',
    sound_effects: 'Efectos',
    sound_effects_desc: 'Arrastra cada perilla para ajustar los valores.',
    fx_drive: 'Saturación analógica. Distorsión cálida',
    fx_locut: 'Filtro de corte bajo. Elimina graves turbios',
    fx_hicut: 'Filtro de corte alto. Suaviza agudos ásperos',
    fx_reverb: 'Reverberación. Añade profundidad espacial',
    fx_phaser: 'Phaser. Modulación envolvente',
    fx_flanger: 'Flanger. Modulación tipo jet',
    fx_tremolo: 'Trémolo. Modulación periódica del volumen',
    sound_autofilter: 'Auto-Filtro (Auto-Wah)',
    sound_autofilter_desc: 'Filtro de envolvente. Ajusta FREQ, RESO, SENS y DECAY.',
    version_history: 'Historial de versiones',
    vh_335: '<b>V3.35</b> \u2014 Mejoras UX de tutoriales (revisi\u00F3n para principiantes). Todos los tooltips traducidos a 9 idiomas. Gu\u00EDa: secciones de panel de sonido e iconos de encabezado a\u00F1adidas',
    vh_333: '<b>V3.33</b> \u2014 Tutoriales interactivos. 11 temas \u00D7 9 idiomas. Sugerencias contextuales en la primera interacci\u00F3n con cada funci\u00F3n',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 voicings de piano con pantalla de teclado espec\u00EDfica MIDI + reflejo "To Pad". Gu\u00EDa actualizada con secci\u00F3n de funciones de voicing HPS',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 voicings sofisticados ordenados por nota superior. Visualizaci\u00F3n de array de grados + optimizaci\u00F3n autom\u00E1tica de octava. Solo miembros HPS',
    vh_325: '<b>V3.25.0</b> \u2014 Voicing de guitarra \u2192 reflejar en pad (tecla <kbd>V</kbd>). Cambio de dise\u00F1o estilo guitarra (1 nota por fila) / compacto. Filtro "Todos" de posici\u00F3n de guitarra al inicio',
    vh_324: '<b>V3.24</b> \u2014 Presets de Clavinet a\u00F1adidos (2 en E.PIANO). Efecto Auto Filter (filtro envolvente / auto-wah) a\u00F1adido',
    vh_323: '<b>V3.23</b> \u2014 Entrada de texto de acordes con autocompletado. "/" para enfocar, abreviaturas (dim, h=m7\u266D5), ordenaci\u00F3n por tensiones',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Alternancia tr\u00EDada/t\u00E9trada diat\u00F3nica. Posiciones de guitarra/bajo agrupadas por cuerda ra\u00EDz',
    vh_37: '<b>V3.7</b> \u2014 Conservaci\u00F3n de posici\u00F3n de voicing (mantener autom\u00E1ticamente la forma de la digitaci\u00F3n en movimiento crom\u00E1tico). Cuadr\u00EDcula de pads, pentagrama y detecci\u00F3n de acordes durante la reproducci\u00F3n. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 Reproducci\u00F3n de archivo MIDI \u2192 iluminaci\u00F3n de pads (reproducci\u00F3n por l\u00EDnea de tiempo, visualizaci\u00F3n del nombre del acorde, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Rhodes Mark I). 7 presets de EP. Interruptor de sonido ON/OFF. Soporte para iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilidad de velocidad (4 par\u00E1metros + visualizaci\u00F3n de curva). Soporte para el bot\u00F3n de octava de Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 M\u00FAltiples bancos de memoria (16 slots \u00D7 hasta 16 bancos, cambiar/duplicar/renombrar)',
    vh_218: '<b>V2.18</b> \u2014 Guardado/restauraci\u00F3n autom\u00E1tica de todos los ajustes (tonalidad/escala/sonido/MIDI/memoria)',
    vh_213: '<b>V2.13</b> \u2014 Superposici\u00F3n de escala de instrumento (guitarra/bajo/piano muestran Available Scale). Etiquetas de grado en pads. Reproducci\u00F3n vinculada a octava',
    vh_27: '<b>V2.7</b> \u2014 Modo de adici\u00F3n de tensiones (s\u00EDntesis de acordes en pad/guitarra/bajo/teclado \u2192 filtrado por Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, superposici\u00F3n de escala en pads)',
    vh_19: '<b>V1.9</b> \u2014 9 idiomas',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 ranuras de memoria, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Modo Plain, exportaci\u00F3n MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Lanzamiento inicial (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6ªR',
    root_5: '5ªR',
    root_4: '4ªR',
    root_3: '3ªR',
    root_2: '2ªR',
    open: 'Abierta',
    all: 'Todas',
    to_pad: 'Al Pad',
  },
  tips: [
    'Pulsa C para guardar el acorde actual en Memory',
    'Opt+1~V guarda directamente en un slot (16 teclas: 1234 QWER ASDF ZXCV)',
    'Shift+Clic en un slot de Memory para eliminarlo',
    'Opt+Arrastrar para copiar un slot',
    'Pulsa S para alternar Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D alterna Drop 2 / Drop 3',
    'Shift+G muestra el diapasón de guitarra',
    'Shift+C muestra el Círculo de Quintas',
    'Tab alterna entre modos Scale / Chord / Input',
    'Espacio reproduce la escala o acorde actual',
    'Exporta todos los slots de Memory como archivo MIDI',
    'Conecta un controlador MIDI para tocar los pads',
    'Flechas ↓↑ cambian la inversión del acorde',
    'Pulsa R para voicing sin fundamental',
    'Pulsa O para omitir la 5ª',
    'Shift+S muestra la partitura',
    'El icono de guardado preserva tus ajustes entre sesiones',
    '[ ] cambia bancos de Memory — gestiona varias canciones',
    'Modo Perform: Dispara acordes con teclado (1234 / QWER / ASDF / ZXCV) o pads MIDI',
    'Pulsa / en modo Chord para escribir nombres de acordes (ej: Cm7, G7(b9,#11))',
  ],
  tips_off: 'No mostrar consejos',
  whats_new: 'Novedades',
  whats_new_32427: 'Voicing de guitarra \u2192 reflejar en pad (tecla V). Cambio de diseño estilo guitarra / compacto',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: 'Preset de sonido',
    sound_msg: 'Elige un preset de sonido y toca un pad para escucharlo.\nORGAN y E.PIANO \u2014 cada uno tiene m\u00FAltiples presets.',
    sound_done: '\u00A1Suena bien! Pulsa Siguiente para continuar.',
    midi_title: 'Controlador MIDI',
    midi_msg: 'Se ha detectado un controlador MIDI. Selecciona tu dispositivo del men\u00FA desplegable.\nLa sensibilidad de velocidad se puede ajustar en el panel Sound.',
    midi_no_device: 'No se detect\u00F3 controlador MIDI \u2014 no hay problema.\nPuedes usar clics en pads, entrada de guitarra/bajo/piano o entrada de texto de acordes.',
    input_title: 'Tres modos',
    input_msg: 'Scale \u2014 ver notas de escala en la cuadr\u00EDcula de 64 pads\nChord \u2014 construir acordes con voicings, inversiones y tensiones\nInput \u2014 toca los pads libremente para detectar nombres de acordes\n\nCambia con Tab o los botones de modo de arriba.',
    instruments_title: 'Entrada de instrumentos',
    instruments_msg: 'Guitarra, Bajo, Piano \u2014 activa cada visualizaci\u00F3n y haz clic para ingresar notas directamente.\nClic en el diapas\u00F3n \u2192 detecci\u00F3n de acordes \u2192 "Al Pad" (V) para convertir al layout de pads.\nEntrada de texto: pulsa / en modo Chord para escribir nombres de acordes (ej. Cm7, G7(b9,#11)).',
    done_title: '\u00A1Listo!',
    done_msg: 'Todo preparado. Explora libremente \u2014 pulsa ? para la lista completa de atajos.\nLa Gu\u00EDa tiene capturas, videos y casos de uso.',
    next: 'Siguiente',
    skip_step: 'Saltar',
    skip_all: 'Saltar tutorial',
    open_guide: 'Abrir Gu\u00EDa',
    close: 'Empezar',
    reset: 'Reiniciar tutorial',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: 'Tutoriales',
    cat_getting_started: 'Primeros pasos',
    cat_features: 'Funciones',
    cat_advanced: 'Avanzado',
    steps_label: 'pasos',
    reset_all: 'Reiniciar todo el progreso',
    close_selector: 'Cerrar',
    hint_available: 'Tutorial disponible',
    hint_try: 'Probar',
    // Button label
    btn_label: 'Tutoriales',
    // Shared action labels
    next: 'Siguiente',
    skip_step: 'Saltar',
    skip_all: 'Saltar tutorial',
    open_guide: 'Abrir Gu\u00EDa',
    close: 'Listo',
    // Onboarding ask dialog
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: '¿Es tu primera vez aquí? ¿Quieres un recorrido rápido de la app?',
    onboarding_yes: '¡Sí, muéstrame!',
    onboarding_no: 'Saltar',
    // Onboarding
    onboarding_title: 'Primeros pasos',
    onboarding_desc: 'Aprende los fundamentos de 64 Pad Explorer',
    onboarding: {
      sound_title: 'Preset de sonido',
      sound_msg: 'Elige un preset de sonido y toca un pad para escucharlo.\nORGAN y E.PIANO \u2014 cada uno tiene m\u00FAltiples presets.',
      sound_done: '\u00A1Suena bien! Pulsa Siguiente para continuar.',
      midi_title: 'Controlador MIDI',
      midi_msg: 'Se ha detectado un controlador MIDI. Selecciona tu dispositivo del men\u00FA desplegable.\nLa sensibilidad de velocidad se puede ajustar en el panel Sound.',
      midi_no_device: 'No se detect\u00F3 controlador MIDI \u2014 no hay problema.\nPuedes usar clics en pads, entrada de guitarra/bajo/piano o entrada de texto de acordes.',
      input_title: 'Tres modos',
      input_msg: 'Scale \u2014 ver notas de escala en la cuadr\u00EDcula de 64 pads\nChord \u2014 construir acordes con voicings, inversiones y tensiones\nInput \u2014 toca los pads libremente para detectar nombres de acordes\n\nCambia con Tab o los botones de modo de arriba.',
      instruments_title: 'Entrada de instrumentos',
      instruments_msg: 'Guitarra, Bajo, Piano \u2014 activa cada visualizaci\u00F3n y haz clic para ingresar notas directamente.\nClic en el diapas\u00F3n \u2192 detecci\u00F3n de acordes \u2192 "Al Pad" (V) para convertir al layout de pads.\nEntrada de texto: pulsa / en modo Chord para escribir nombres de acordes (ej. Cm7, G7(b9,#11)).',
      done_title: '\u00A1Listo!',
      done_msg: 'Todo preparado. Explora libremente \u2014 pulsa ? para la lista completa de atajos.\nLa Gu\u00EDa tiene capturas, videos y casos de uso.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Modo Scale',
    scale_mode_desc: 'Explora escalas en la cuadr\u00EDcula de 64 pads',
    scale_mode: {
      step1_title: 'Cambiar al modo Scale',
      step1_msg: 'El modo Scale muestra las notas de la escala iluminadas en la cuadr\u00EDcula.\nToca cualquier pad iluminado para escuchar la nota.',
      step2_title: 'Elige una tonalidad',
      step2_msg: 'Elige una tonalidad ra\u00EDz. La cuadr\u00EDcula se actualiza al instante.\nPrueba a cambiar entre C, G, F \u2014 escucha c\u00F3mo cambia el patr\u00F3n de colores.',
      step3_title: 'Elige una escala',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 escalas disponibles. Los pads se actualizan en tiempo real.',
      step4_title: 'Barra diat\u00F3nica',
      step4_msg: 'Los acordes diat\u00F3nicos de tu escala aparecen aqu\u00ED.\nHaz clic en cualquier acorde para ir al modo Chord con ese voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Modo Chord',
    chord_mode_desc: 'Construye acordes paso a paso',
    chord_mode: {
      step1_title: 'Cambiar al modo Chord',
      step1_msg: 'El modo Chord te permite construir cualquier acorde desde cero.\n3 pasos: Root \u2192 Quality \u2192 Tension.',
      step2_title: 'Paso 1: Root',
      step2_msg: 'Elige una nota ra\u00EDz. C, D, E... las 12 notas.\nLa pantalla muestra tu acorde actual.',
      step3_title: 'Paso 2: Quality',
      step3_msg: 'Elige el tipo de acorde: Maj, min, 7, m7, dim, aug...\nLa cuadr\u00EDcula ilumina las notas del acorde.',
      step4_title: 'Paso 3: Tensions',
      step4_msg: 'Elige primero una Quality \u2014 los botones de tensión aparecen automáticamente.\n9, b9, #9, 11, #11, 13, b13. Se pueden seleccionar múltiples tensiones.',
      step5_title: 'Entrada de texto',
      step5_msg: 'Escribe nombres de acordes directamente con la tecla /.\nSlash chords y voicings complejos se introducen rápidamente.',
    },
    // Input Mode tutorial
    input_mode_title: 'Modo Input',
    input_mode_desc: 'Introduce acordes desde controlador MIDI, pads, diapasón o teclado',
    input_mode: {
      step1_title: 'Cambiar al modo Input',
      step1_msg: 'Introduce acordes desde un controlador MIDI, haciendo clic en los pads, el diapasón o el teclado.\nLa detección de acordes funciona en todos los modos.',
      step2_title: 'Toca algunos pads',
      step2_msg: 'Haz clic en cualquier pad de la cuadr\u00EDcula.\nCada toque activa/desactiva una nota.',
      step3_title: 'Detecci\u00F3n de acordes',
      step3_msg: 'El nombre del acorde detectado aparece sobre la cuadr\u00EDcula.\nEtiquetas de grado (R, 3, 5, b7...) se muestran en cada pad.',
      step4_title: 'Guardar con Capture',
      step4_msg: 'La tecla <strong>C</strong> guarda el acorde actual en la siguiente ranura de memoria.\nConstruye progresiones de acordes una por una.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Barra diat\u00F3nica',
    diatonic_desc: 'Acceso con un clic a los acordes diat\u00F3nicos',
    diatonic: {
      step1_title: 'La barra diat\u00F3nica',
      step1_msg: 'Cada escala tiene su propio conjunto de acordes diat\u00F3nicos.\nAparecen aqu\u00ED \u2014 listos para tocar.',
      step2_title: 'Tr\u00EDada / T\u00E9trada',
      step2_msg: 'Alterna entre tr\u00EDadas de 3 notas y acordes de s\u00E9ptima de 4 notas.\nLa barra se actualiza al instante.',
      step3_title: 'Haz clic en un acorde',
      step3_msg: 'Haz clic en un acorde de la barra.\nPuedes transformarlo con tensiones y más en el Chord Builder.',
      step4_title: 'Atajo de teclado',
      step4_msg: 'Pulsa 1\u20137 para seleccionar acordes diat\u00F3nicos al instante.\nSin necesidad de rat\u00F3n.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Guarda acordes y t\u00F3calos en vivo',
    memory: {
      step1_title: 'Guardar un acorde',
      step1_msg: 'Guarda tus acordes favoritos.\nGuardar los voicings que te gustan ayuda con el beat-making y la práctica.',
      step2_title: '16 ranuras de memoria',
      step2_msg: 'Funciona como un layout Drumrack de 16 pads en PUSH, Launchpad, MPC y Maschine — intuitivo de usar.',
      step3_title: 'Bancos de memoria',
      step3_msg: 'En PUSH y Launchpad, el layout Drumrack lo hace intuitivo de usar.',
      step4_title: 'Modo Perform',
      step4_msg: 'Las teclas del teclado del PC también corresponden a los 16 pads.',
      step5_title: 'Exportaci\u00F3n MIDI',
      step5_msg: 'Exporta todos los acordes de memoria como archivo MIDI.\nArr\u00E1stralo a tu DAW y empieza a producir.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Da forma a tus voicings de acordes',
    voicing: {
      step1_title: 'Controles de voicing',
      step1_msg: 'En el modo Chord Builder, varias transformaciones son posibles desde la forma básica.\nOmit, Shell, Inversion, Drop — todo aquí.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> es para Shell voicing. Aprende los voicings R37 y R73 de forma fluida en el pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Los atajos de teclado suelen seguir mnemotecnia.\n<strong>O</strong>mit = omitir la 5ª. <strong>R</strong>ootless = voicing sin fundamental.',
      step4_title: 'Inversiones',
      step4_msg: 'A diferencia de la mayoría del software, puedes crear inversiones ultra-rápido.\nTambién ayuda a entender los slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'Para cuando quieres destacar la nota superior —\nlos Drop voicings también están disponibles.',
      step6_title: 'Voicing Box',
      step6_msg: 'Los pads pueden tener múltiples opciones de posición. El Voicing Box se encarga de esto.\nHaz clic en a, b, c, d etc. en el pad, o escribe la letra, para ver múltiples posibilidades de voicing.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, efectos y volumen',
    sound: {
      step1_title: 'Presets de sonido',
      step1_msg: 'ORGAN (4 tipos) y E.PIANO (8 tipos).\nHaz clic en un pad o usa tu controlador MIDI.',
      step2_title: 'Panel de detalles',
      step2_msg: 'Haz clic en \u25BC para expandir el panel de detalles de sonido.\nEfectos, volumen y controles de filtro est\u00E1n aqu\u00ED.',
      step3_title: 'Efectos',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nAj\u00FAstalos en el panel de detalles.',
      step4_title: 'Sonido ON/OFF',
      step4_msg: 'Activa y desactiva el sonido con el icono del altavoz.\nDesactivarlo puede ser práctico al usar un DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings clasificados por nota superior. Solo miembros HPS',
    tasty: {
      step1_title: 'Activar TASTY',
      step1_msg: '129 voicings sofisticados que la lógica simple no puede producir.\nPensar desde la nota superior es útil para arreglos de cuerdas y vientos.\n(Solo miembros HPS)',
      step2_title: 'Ciclar recetas',
      step2_msg: 'Pulsa T de nuevo para ciclar los voicings.\nShift+T retrocede. El contador muestra tu posici\u00F3n.',
      step3_title: 'Notaci\u00F3n de grados',
      step3_msg: 'El \u00E1rea de info muestra el apilamiento de grados \u2014 ej. m9 (b3-b7-9-5-1).\nEs la estructura del voicing de abajo a arriba.',
      step4_title: 'Al Pad',
      step4_msg: 'Optimización de pads que el software típico no puede hacer.\nDisfruta tocando voicings elegantes en los pads también.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Voicings idiom\u00E1ticos cl\u00E1sicos de piano. Solo miembros HPS',
    stock: {
      step1_title: 'Activar STOCK',
      step1_msg: 'Conocer voicings específicos de piano te ayuda a salir del juego de solo forma básica.\n154 voicings de piano en notación de grados.\n(Solo miembros HPS)',
      step2_title: 'Ciclar voicings',
      step2_msg: 'Pulsa K de nuevo para avanzar por los voicings.\nShift+K retrocede.',
      step3_title: 'Vista de teclado',
      step3_msg: 'Activa la visualizaci\u00F3n de Piano para ver las posiciones reales.\nEl voicing cobra vida en el teclado.',
      step4_title: 'Al Pad',
      step4_msg: 'Haz clic en "Al Pad" para mapear el voicing al layout de pads.\nGuarda en memoria y exporta a tu DAW.',
    },
    // Circle of Fifths tutorial
    circle_title: 'C\u00EDrculo de quintas',
    circle_desc: 'Relaciones entre tonalidades de un vistazo',
    circle: {
      step1_title: 'Abrir el c\u00EDrculo',
      step1_msg: 'Pulsa Shift+C o haz clic en el bot\u00F3n del c\u00EDrculo.\nEl c\u00EDrculo de quintas aparece debajo.',
      step2_title: 'Enlace de tonalidad',
      step2_msg: 'Consulta rápidamente acordes sustitutos y diatónicos importantes para la interpretación y la composición.',
      step3_title: 'Funciones diatónicas',
      step3_msg: 'A diferencia del círculo de quintas típico, 64 Pad Explorer te permite seleccionar 3 tipos de menor (Natural/Harmonic/Melodic) al elegir una tonalidad menor.\nFacilita el dominio de las complicadas tonalidades menores.',
    },
    // Settings tutorial
    settings_title: 'Pantalla y ajustes',
    settings_desc: 'Personaliza tu espacio de trabajo',
    settings: {
      step1_title: 'Paneles de instrumentos',
      step1_msg: 'Guitar muestra voicings de uso común al seleccionar un acorde en el Chord Builder.\nEn el modo Input, también puedes introducir desde guitarra, bajo y teclado.',
      step2_title: 'Nombres / Grados',
      step2_msg: 'Alterna entre nombres de notas (C, D, E) y grados (R, 2, 3).\nSe aplica a los pads y a la visualizaci\u00F3n de guitarra.',
      step3_title: 'Desplazamiento de octava',
      step3_msg: 'Usa \u25B2\u25BC para desplazar el rango de los pads una octava arriba o abajo.\nLos botones de octava de Push 3 se sincronizan autom\u00E1ticamente.',
      step4_title: 'Guardar todo',
      step4_msg: 'Haz clic en el icono de guardar para conservar todos los ajustes.\nTonalidad, escala, sonido, memoria, voicing \u2014 todo se preserva.',
    },
  },
});
